SigmaCodebackup3rdSep/objects/AssetTriggerCheck__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To check the trigger on Asset Price Update.</description>
    <fields>
        <fullName>CheckAssetPriceUpdatetrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CheckAssetPriceUpdatetrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>AssetTriggerCheck</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Business_Calendar__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Business Calendar</label>
    <nameField>
        <label>Business Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <label>Parent Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Package Location</fullName>
                </value>
                <value>
                    <fullName>Receiving Location</fullName>
                </value>
                <value>
                    <fullName>Waste Management Location</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Location</fullName>
                </value>
                <value>
                    <fullName>Storage Location</fullName>
                </value>
                <value>
                    <fullName>Shipping Location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Service_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Resources</relationshipLabel>
        <relationshipName>Service_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Average_Travel_Speed__c</fullName>
        <label>Average Travel Speed</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Calendar</label>
        <referenceTo>Business_Calendar__c</referenceTo>
        <relationshipLabel>Service Resources</relationshipLabel>
        <relationshipName>Service_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Service Resources</relationshipLabel>
        <relationshipName>Service_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <label>Mailing City</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <label>Mailing Country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State_Province__c</fullName>
        <label>Mailing State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street__c</fullName>
        <label>Mailing Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip_Postal_Code__c</fullName>
        <label>Mailing Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>SR_Type__c</fullName>
        <label>SR Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Field</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Showroom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>San Mateo</fullName>
                </value>
                <value>
                    <fullName>Trinity</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Resources1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Another_Visit_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Another Visit Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AssignTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Orders_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Availability_Date__c</fullName>
        <label>Preferred Service Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FFP_MR_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Visit_Date_Time__c</fullName>
        <label>Next Visit Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reason_for_another_Visit__c</fullName>
        <label>Reason for another Visit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insufficient Spares Inventory</fullName>
                </value>
                <value>
                    <fullName>More Service Time Needed</fullName>
                </value>
                <value>
                    <fullName>Customer available for limited time</fullName>
                </value>
                <value>
                    <fullName>Additional Service Support Needed</fullName>
                </value>
                <value>
                    <fullName>Issue different from that reported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_City__c</fullName>
        <label>Service City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Work Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Invoiced to Customer</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Another Visit Needed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>San Mateo</fullName>
                </value>
                <value>
                    <fullName>Trinity</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Order Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Work Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Work_Type__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Work_Type__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Work_Type__c.object
<CustomObject>
    <label>Work Type</label>
    <nameField>
        <label>Work Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/TestWorkOrderTrigger.cls
@isTest
public class TestWorkOrderTrigger { 
    static testMethod void ValidateWorkOrderTrigger() {
        Test.startTest();
        Work_Type__c workType = new Work_Type__c();
        workType.Name = 'Repair';
        insert workType;
        
        DateTime d1 = DateTime.now();
        system.debug('>>.11'+d1);
        d1 = d1.addDays(30);
        system.debug('>>.'+d1);
        //d1.addHours(2);
        //caseRecord.Availability__c =  d1;//DateTime.newInstance(Date.today(), '11:00:00');//DateTime.now();
        d1 = DateTime.parse('10/28/2019 9:00 AM');
        
        Account testAccount = new Account();
        testAccount.Name = 'Test';
        testAccount.BillingCity = 'Bengalore';
        testAccount.BillingCountry = 'India';
        testAccount.BillingPostalCode = '560068';
        testAccount.BillingState = 'Karnataka';
        testAccount.BillingStreet = 'Hosur Main Road';
        testAccount.ShippingCity = 'San Francisco';
        testAccount.ShippingCountry = 'USA';
        testAccount.ShippingState = 'California';
        testAccount.ShippingPostalCode = '94103';
        testAccount.Email__c='abc@gmail.com';
        insert testAccount;
        Work_Order__c w = new Work_Order__c(Status__c = 'Assigned');
        w.Service_City__c = 'TestCity';
        w.Work_Type__c = workType.Id;
        w.Customer_Availability_Date__c = d1;
        w.Status__c = 'Assigned';
        w.Account__c = testAccount.Id;
        insert w;
        //Work_Order__c testWO = [select id,Status__c from Work_Order__c where Service_City__c='TestCity'];
        Work_Order__c testWO = [select id,Status__c from Work_Order__c where id=:w.Id];
        testWO.Status__c = 'Completed';
        Update testWO;
        Work_Order__c testWO1 = [select id,Status__c from Work_Order__c where id =:w.id];
        system.debug('Updated Status  :'+testWO1.Status__c);
        System.assertEquals('Completed', testWO.Status__c);
        Test.stopTest();
        
    }
    
    @isTest(seealldata=false)
    public static void test(){
        Boolean success = true;        
        try {
            System.Test.startTest(); 
            Integer i =0;
            
            AssetTriggerCheck__c cs = new AssetTriggerCheck__c();
            cs.Name='APU';
            cs.CheckAssetPriceUpdatetrigger__c=false;
            //cs.Other fiels values
            insert cs;
            system.debug('AssetTrigger Check');
            
            // creating test account
            Account communityAccount = new Account();
            communityAccount.Name = 'Community Account - Test';
            communityAccount.ShippingCity = 'San Francisco';
            communityAccount.ShippingCountry = 'USA';
            communityAccount.ShippingState = 'California';
            communityAccount.ShippingPostalCode = '94103';
            communityAccount.BillingCity = 'Bengalore';
            communityAccount.BillingCountry = 'India';
            communityAccount.BillingPostalCode = '560068';
            communityAccount.BillingState = 'Karnataka';
            communityAccount.BillingStreet = 'Hosur Main Road';
            communityAccount.Email__c='abc@gmail.com';
            insert communityAccount;
            
            //-- STEP 1 :- INSERT CONTACT
            Contact newContact = new Contact();
            newContact.FirstName='testFN';
            newContact.LastName='testLN';
            newContact.MailingPostalCode='517132';
            
            insert newContact;
            
            Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
            List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
            Id RID1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            Account acc = new Account();
            acc.Name = 'Test';
            acc.RecordTypeId = RID1;
            acc.Email__c='abc@gmail.com';
            insert acc;
            
            
            Default_Parameters__c  dp = new Default_Parameters__c (Name = 'Sample dp',Parent_Id__c = acc.Id);
            insert dp;
            
            
            
            Date dtt = Date.today();
            
            /*//-- STEP 2 :- INSERT ASSET
            
            Asset newAsset = new Asset();
            newAsset.Name = 'Test';
            newAsset.AccountId = communityAccount.Id;
            newAsset.SerialNumber = '1234';
            newAsset.InstallDate = dtt;
            newAsset.PurchaseDate = dtt+1;
            newAsset.UsageEndDate = dtt+2;
            //System.debug('Assert -->'+asse);
            insert newAsset;
            Id AssetId = newAsset.Id;
            system.debug('Asset Inserted');*/
            
            //-- Insert WorkOrder Type
            Work_Type__c workType = new Work_Type__c();
            workType.Name = 'Repair';
            insert workType;
            
            DateTime d1 = DateTime.now();
            system.debug('>>.11'+d1);
            d1 = d1.addDays(30);
            system.debug('>>.'+d1);
            //d1.addHours(2);
            //caseRecord.Availability__c =  d1;//DateTime.newInstance(Date.today(), '11:00:00');//DateTime.now();
            d1 = DateTime.parse('11/02/2019 5:00 PM');
            
            String createOrEdit = '';
            Location__c fromLocation = new Location__c(Location_Name__c = 'Central Warehouse', Location_Type__c='WareHouse');
            Location__c toLocation = new Location__c(Location_Name__c ='Truck 1', Location_Type__c='Truck');
            insert fromLocation;
            insert toLocation;
            
            
            // creating user contact
            Contact userContact = new Contact();
            userContact.firstname = 'Test';
            userContact.lastname = 'User1';
            userContact.MailingPostalCode='517132';
            userContact.email = 'testuser@crmit.com';
            userContact.accountid = communityAccount.id;
            userContact.Location__c = toLocation.Id;
            insert userContact;
            
            // create portal user 
            User portalUser = new User();
            portalUser.profileId = [select Id, Name from Profile where name = 'Partner Community - PC'
                                    limit 1
                                   ].id;
            portalUser.username = userContact.email;
            portalUser.email = userContact.email;
            portalUser.emailencodingkey = 'UTF-8';
            portalUser.localesidkey = 'en_US';
            portalUser.languagelocalekey = 'en_US';
            portalUser.timezonesidkey = 'America/Los_Angeles';
            portalUser.alias = userContact.lastname;
            portalUser.lastname = userContact.lastname;
            portalUser.firstname = userContact.firstname;
            portalUser.contactId = userContact.Id;
            insert portalUser;
            
            Service_Resource__c serviceResource = new Service_Resource__c();
            serviceResource.Name = 'Mr. Test';
            serviceResource.User__c=portalUser.Id;
            //serviceResource.Business_Calendar__c=calendar.Id;
            serviceResource.Active__c=true;
            serviceResource.Account__c=communityAccount.id;
            //serviceResource.Location__c=toLocation.Id;
            serviceResource.SR_Type__c='Field';
            serviceResource.Average_Travel_Speed__c='30';
            serviceResource.Mobile__c='9761898211';
            serviceResource.Email__c ='';
            serviceResource.Territory__c='San Francisco';
            serviceResource.Mailing_Street__c='';
            serviceResource.Mailing_City__c='';
            serviceResource.Mailing_Zip_Postal_Code__c='560018';
            serviceResource.Mailing_State_Province__c='';
            serviceResource.Mailing_Country__c='';
            insert serviceResource;
            system.debug('Service Resource Inserted - '+serviceResource);
            
            Work_Order__c workOrder = new Work_Order__c(FFP_MR_Contact__c=userContact.ID,Account__c=communityAccount.Id,Customer_Availability_Date__c=d1,Work_Type__c=workType.Id,Status__c  = 'Draft');
            Work_Order__c workOrder1 = new Work_Order__c(AssignTo__c=portalUser.Id,FFP_MR_Contact__c=userContact.ID,Account__c=communityAccount.Id,Customer_Availability_Date__c=d1,Work_Type__c=workType.Id,Status__c  = 'In Progress',Another_Visit_Needed__c=true);
            Work_Order__c workOrder2 = new Work_Order__c(AssignTo__c=portalUser.Id,FFP_MR_Contact__c=userContact.ID,Account__c=communityAccount.Id,Customer_Availability_Date__c=d1,Work_Type__c=workType.Id,Status__c  = 'Draft',Another_Visit_Needed__c=true,Reason_for_another_Visit__c='More Service Time Needed',Next_Visit_Date_Time__c=d1);
            insert workOrder2;
            workOrder2.Status__c = 'In Progress';
            update workOrder2;
            workOrder2.Status__c = 'Completed';
            update workOrder2;
            insert workOrder1;
            insert workOrder;
            system.debug('workOrder Test'+workOrder);
            system.debug('workOrder Test Class ***********************************');
            system.debug('workOrder Test'+workOrder1);
            system.debug('workOrder Test Class ***********************************');
            system.debug('workOrder Test'+workOrder2);
           
            

            
            workOrder1.Status__c = 'In Progress';
            update workOrder1;
            workOrder1.Status__c = 'Completed';
            update workOrder1;
            
            
            
            
            system.debug('Update 2'+workOrder);
            
            
            System.Test.stopTest();
            System.assert(true);
        }
        catch(Exception e){
            system.debug('Exception Occurred - '+e);
        }
    } 
}