SigmaCodebackup3rdSep/objects/BP_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Brewery_Producer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brewery Producer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BP_Payments</relationshipLabel>
        <relationshipName>BP_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interval__c</fullName>
        <label>Interval</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>BP_Payment</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BP_Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/BP_Payment_Details__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BP_Payment__c</fullName>
        <label>BP_Payment</label>
        <referenceTo>BP_Payment__c</referenceTo>
        <relationshipLabel>BP_Payment_Details</relationshipLabel>
        <relationshipName>BP_Payment_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commission_Amount__c</fullName>
        <label>Commission Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Final_payable_amount_to_BP__c</fullName>
        <label>Final payable amount to BP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Sales_Amount__c</fullName>
        <label>Total Sales Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BP_Payment_Detail</label>
    <nameField>
        <displayFormat>PDN-{0000}</displayFormat>
        <label>Payment_Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BP_Payment_Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Brewery_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Brewer_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brewer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BreweryCustomers</relationshipLabel>
        <relationshipName>BreweryCustomers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brewery_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brewery Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BreweryCustomers (Brewery Customer)</relationshipLabel>
        <relationshipName>BreweryCustomers1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BreweryCustomer</label>
    <nameField>
        <displayFormat>BC-{00000}</displayFormat>
        <label>Brewery Customers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BreweryCustomers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Brewery_Registry__c.object
<CustomObject>
    <fields>
        <fullName>Brewer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brewer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brewery Registries</relationshipLabel>
        <relationshipName>Brewery_Registries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brewery_Name__c</fullName>
        <label>Brewery Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Date_of_Registration__c</fullName>
        <label>Date of Registration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brewery Registry</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Brewery Registry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brewery Registries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>Brewer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brewer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sigma Orders (Brewer Account)</relationshipLabel>
        <relationshipName>Sigma_Orders5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivary_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Payment_Made__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Payment Made</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <label>Net Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Orders_Status__c</fullName>
        <label>Orders Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Confirmed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Made_to_BP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Made to BP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/FFTBCtrl.cls
public without sharing class FFTBCtrl { 
    @AuraEnabled
    public static List<Sigma_Order__c> getBPData(String bpId, DateTime fromDate, DateTime endDate){
        List<Sigma_Order__c> sigmaOrdList = [select sc.id,sc.name,sc.Delivary_Date__c,
							sc.Net_Quantity__c,sc.TotalAmount__c,sc.Brewer_Account__r.Commision_Fees__c from Sigma_Order__c sc 
                            where sc.Brewer_Account__c = :bpId AND
							sc.CreatedDate >= :fromDate AND sc.CreatedDate <= :endDate 
                            AND sc.Payment_Made_to_BP__c = false AND sc.Is_Payment_Made__c = true ORDER BY Name ASC];
		return sigmaOrdList;
    }       
    
    /*@AuraEnabled
    public static List<Account> getBPsList(){
        List<Account> accList = [select id,Name,sigmaerpdev2__Active__c,sigmaerpdev2__Currency_code__c,CreatedDate,
                                 Email__c,Contact_Person_Mobile__c,Commision_Fees__c 
                                 from Account where recordType.name='Vendor' ORDER BY Name ASC];
		return accList;
    }*/
    
    @AuraEnabled
    public static List<Brewery_Registry__c> getBPsList(){
        List<Brewery_Registry__c> accList = [select name,Brewer_Account__c,Brewery_Name__c,
                                 Date_of_Registration__c,Email__c,Contact_Number__c,
                                 Registration_Status__c from Brewery_Registry__c ORDER BY Name ASC];
		return accList;
    }
    
    @AuraEnabled
    public static String changeBPStatus(String brewID, String status){
        String newStatus = '';
        try{           
            List<User> userList = [select Id,IsActive,Contact.AccountId from User where Contact.AccountId = :brewID];        
            Brewery_Registry__c brObj = [select id,name,Registration_Status__c from Brewery_Registry__c where Brewer_Account__c = :brewID];            
            if(status == 'Active'){
                brObj.Registration_Status__c = 'Inactive';
                update brObj;
                UpdateContacts(brewID, status);          
            }else{
                brObj.Registration_Status__c = 'Active';
                update brObj;
                UpdateContacts(brewID, status);
        	}  
        newStatus = (String) brObj.Registration_Status__c;		  
        }catch(Exception e){
            newStatus = e.getMessage();
        }
        return newStatus; 
    }
    
    @future
    public static void UpdateContacts(String brewID, String status){
        List<User> userList = [select Id,IsActive,Contact.AccountId from User where Contact.AccountId = :brewID]; 
        if(status == 'Active'){
            if(userList.size() > 0){
                for(User userObj : userList){
                    userObj.IsActive = false;
                }
                update userList;    
            } 
        }else{  
            if(userList.size() > 0){
                for(User userObj : userList){
                    userObj.IsActive = true;
                }
                update userList;    
            }
        }  
    }
            
    @AuraEnabled
    public static String makeBPPayments(String bpId, Date fromDate, Date endDate, Decimal totalSalesAmt, Decimal deductCommAmt, List<String> sigOrdsId){
        String msg = 'success';
        try{            
            Account accObj = [select id,Interval__c from Account where id = :bpId];            
        	BP_Payment__c bpObj = new BP_Payment__c();
            bpObj.Brewery_Producer__c = bpId;
            bpObj.Interval__c = accObj.Interval__c;
            insert bpObj;
            
            BP_Payment_Details__c bpdObj = new BP_Payment_Details__c();
            bpdObj.BP_Payment__c = bpObj.Id;
            bpdObj.From_Date__c = fromDate;
            bpdObj.To_Date__c = endDate;
            bpdObj.Total_Sales_Amount__c = totalSalesAmt;
            bpdObj.Commission_Amount__c = deductCommAmt;
            bpdObj.Final_payable_amount_to_BP__c = (totalSalesAmt - deductCommAmt);
            bpdObj.Amount_Paid__c = (totalSalesAmt - deductCommAmt);
            insert bpdObj;            
            
            List<String> lstAlpha = sigOrdsId;
            List<Sigma_Order__c> sigList = [select id,name,Payment_Made_to_BP__c from Sigma_Order__c where id in :lstAlpha];
            for(Sigma_Order__c sordObj : sigList){
                sordObj.Payment_Made_to_BP__c = true;
            }
            update sigList;
            
        	return msg;
        }catch(Exception ex){
            msg = ex.getMessage();
            return msg;
        }
    }
    
    @AuraEnabled
    public static List<Sigma_Order__c> getBPSales(String selVal){ 
        //Contact cntObj = [select AccountId from Contact where id =: UserInfo.getUserId()];
		
        User currentuser = [select Id,Profile.Name,Contact.AccountId from User where Id =: UserInfo.getUserId()];        
        /*List<Sigma_Order__c> sigmaOrdList = [select id,name,sigmaerpdev2__Customer_Formula__c,Delivary_Date__c,
								Net_Quantity__c,TotalAmount__c,Is_Payment_Made__c,Orders_Status__c
                                from Sigma_Order__c where Brewer_Account__c = :cntObj.AccountId
                                ORDER BY Name DESC];

		//from Sigma_Order__c where Brewer_Account__c = '0012x00000FR5bC'
		*/
        List<Sigma_Order__c> sigmaOrdList = new List<Sigma_Order__c>();
        if(selVal.equalsIgnoreCase('All')){
        	sigmaOrdList = [select id,name,sigmaerpdev2__Customer_Formula__c,Delivary_Date__c,
								Net_Quantity__c,TotalAmount__c,Is_Payment_Made__c,Orders_Status__c
                                from Sigma_Order__c where Brewer_Account__c =: currentuser.Contact.AccountId                              
                                ORDER BY Name DESC];    
        }else{
           sigmaOrdList = [select id,name,sigmaerpdev2__Customer_Formula__c,Delivary_Date__c,
								Net_Quantity__c,TotalAmount__c,Is_Payment_Made__c,Orders_Status__c
                                from Sigma_Order__c where Brewer_Account__c =: currentuser.Contact.AccountId 
                           		and Orders_Status__c = :selVal
                                ORDER BY Name DESC];    
        }        
		return sigmaOrdList;
    }
    
    @AuraEnabled
    public static List<Account> getBPCustomers(){
        //Contact cntObj = [select AccountId from Contact where id = :UserInfo.getUserId()];
        User currentuser = [select Id,Profile.Name,Contact.AccountId from User where Id =: UserInfo.getUserId()]; 
        List<Brewery_Customer__c> custList = new List<Brewery_Customer__c>();
        custList = [select id,Brewer_Account__c,Brewery_Customer__c from Brewery_Customer__c];
        Set<Id> custIds = new Set<Id>();
        List<Account> accList = new List<Account>();
        if(custList.size() > 0)
        {
           for(Brewery_Customer__c bcObj : custList){
           	custIds.add(bcObj.Brewery_Customer__c);
           }
           accList = [select id,name,Email__c,Contact_Person_Mobile__c,
                                     ShippingStreet,ShippingCity,ShippingState,ShippingPostalCode,ShippingCountry 
                                     from account where id in :custIds];
        }        
		return accList;
    }
    
    @AuraEnabled
    public static void markAsDelvStatus(String soId){
        Sigma_Order__c soObj = [select id,Orders_Status__c from Sigma_Order__c where id = :soId];        
        soObj.Orders_Status__c = 'Delivered';        
        update soObj;
    }
    
    @AuraEnabled
    public static void deleteSalesOrder(String soId){
        Sigma_Order__c soObj = [select id from Sigma_Order__c where id = :soId];  
        delete soObj;
    }
    
}