SigmaCodebackup3rdSep/objects/Brewery_Registry__c.object
<CustomObject>
    <fields>
        <fullName>Brewer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brewer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brewery Registries</relationshipLabel>
        <relationshipName>Brewery_Registries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Brewery Registry</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Brewery Registry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brewery Registries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sigma Orders (AccountId)</relationshipLabel>
        <relationshipName>Sigma_Orders4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brewer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brewer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sigma Orders (Brewer Account)</relationshipLabel>
        <relationshipName>Sigma_Orders5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/SendEmailToBrewery.cls
public with sharing class SendEmailToBrewery {
	
	public static void emailtobrewery(Id orderId){
	List<String> toMail = new List<String>();	
    Sigma_Order__c orderdata = [Select id,name,Brewer_Account__c,Brewer_Account__r.Name,AccountId__c,AccountId__r.Name,AccountId__r.Email__c,AccountId__r.Phone,Customer_Email__c from Sigma_Order__c where id =:orderId];
	 
		if(orderdata.Brewer_Account__c !=null)
		{
			Brewery_Registry__c BR = [select id,Brewer_Account__c,Email__c from Brewery_Registry__c where Brewer_Account__c=:orderdata.Brewer_Account__c];
			if(BR.Email__c !=null)
			{
				toMail.add(BR.Email__c);
			}
		}
		
		if(toMail.size()>0)
		{
			//String MessageBody = 'Hi '+customerName +',Attached payment receipt along with this email.Thanks & Regards';  
			String completeMailBody='<html>Dear '+orderdata.Brewer_Account__r.Name+',<br/><br/>Payment is received for order number '+ orderdata.name+'<br/>Customer Name : '+orderdata.AccountId__r.Name +'<br/>Email :'+orderdata.AccountId__r.Email__c +'<br/>Phone :'+orderdata.AccountId__r.Phone+'<br/><br/>Regards,<br/>FFTB Team</html>';
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();     
			mail.setToAddresses(toMail); 
			mail.setSubject('Payment Received');
			mail.setHTMLBody(completeMailBody);
			mail.setSaveAsActivity(false);  
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
		}
		
	}

}