SigmaCodebackup3rdSep/objects/Community_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Products_Per_Page__c</fullName>
        <label>Products Per Page</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retailer_Community_URL__c</fullName>
        <label>Retailer Community URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer_Profile_Name__c</fullName>
        <label>Retailer Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Community_URL__c</fullName>
        <label>Vendor Community URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Profile_Name__c</fullName>
        <label>Vendor Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Order_API__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Renewal</label>
        <type>Checkbox</type>
    </fields>
    <label>Order API</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Order_Usage__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sigma_order__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sigma order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_object__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard object</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Usage</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaigns (Agency)</relationshipLabel>
        <relationshipName>Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Client)</relationshipLabel>
        <relationshipName>Campaigns2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Order_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Order Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposal_Name__c</fullName>
        <label>Proposal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Proposed</fullName>
                </value>
                <value>
                    <fullName>Active Negotiation</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Contract Pending</fullName>
                    <isActive>false</isActive>
                    <label>Contract Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <label>Usage Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Proposal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sigma Orders (AccountId)</relationshipLabel>
        <relationshipName>Sigma_Orders4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sigma Orders</relationshipLabel>
        <relationshipName>Sigma_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brewer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brewer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sigma Orders (Brewer Account)</relationshipLabel>
        <relationshipName>Sigma_Orders5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Payment_Made__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Payment Made</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <label>Net Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Created_Via__c</fullName>
        <label>Order Created Via</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Web_Order</fullName>
                    <default>true</default>
                    <label>Web_Order</label>
                </value>
                <value>
                    <fullName>M-POS</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Time Based Inventory</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Service Quote</fullName>
                </value>
                <value>
                    <fullName>Work Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Orders_Status__c</fullName>
        <label>Orders Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Confirmed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paid_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Sigma Orders</relationshipLabel>
        <relationshipName>Sigma_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Time_Base_Inventory__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proposal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposal_for_Products__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proposal for Products</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposal_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proposal to Order</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Base Inventory</label>
</CustomObject>

SigmaCodebackup3rdSep/classes/SigmaOrderHandler.cls
/*=====================================================================================================
Author   : Sandhya
Company  : Mindlinks Solution Pvt Ltd.
Class    : Sigma Order and Order Handlers,Proposal Handler 
Date     : 20-08-2018              
=======================================================================================================*/
public without sharing class SigmaOrderHandler
{
    
    
    // Code For Sigma Order
    @AuraEnabled
    public static SoPaginationHelper fetchSigmaOrderList(Decimal pageNumber)
    {
        SoPaginationHelper r;
        
       /* if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Sigma_Order__c',new set<String>{'id','Name','RecordTypeId','RecordType.Name','sigmaerpdev__AccountId__r.Name','CreatedById','sigmaerpdev__Order_Created_Via__c','sigmaerpdev__Orders_Status__c','sigmaerpdev__Is_Payment_Made__c','sigmaerpdev__Net_Quantity__c'})
          ){ */
			Id UserId= UserInfo.getUserId();
            User currentuser = [select Id,Profile.Name,Contact.AccountId from User where Id =: UserId];
            Community_Configuration__c Custset= [select Id,Name,Retailer_Community_URL__c,Products_Per_Page__c,Retailer_Profile_Name__c,Vendor_Community_URL__c,Vendor_Profile_Name__c from Community_Configuration__c where Name = 'Community Configurations' LIMIT 1];
            
              Integer pageSize = 10;
              Integer offset = ((Integer)pageNumber - 1) * pageSize;
              
              r =  new SoPaginationHelper();
              r.pageSizeSigma = pageSize;
              r.pageSigma = (Integer) pageNumber;
              
              if(currentuser.Profile.Name != Custset.Retailer_Profile_Name__c)
			  {
				 r.sigmaList = [select id,CreatedDate,AccountId__r.Email__c,Name,RecordTypeId,RecordType.Name,AccountId__r.Name,CreatedById,Order_Created_Via__c,Orders_Status__c,Paid_Amount__c,Is_Payment_Made__c,Net_Quantity__c,TotalAmount__c from Sigma_Order__c
                             order by createddate desc limit :pageSize offset :offset];
				r.totalSigma = [SELECT count() FROM Sigma_Order__c];
                r.IsCommunityUser = false;
			  }
			  else
			  {
				  r.sigmaList = [select id,CreatedDate,AccountId__r.Email__c,Name,RecordTypeId,RecordType.Name,AccountId__r.Name,CreatedById,Order_Created_Via__c,Orders_Status__c,Paid_Amount__c,Is_Payment_Made__c,Net_Quantity__c,Brewer_Account__c,Brewer_Account__r.Name from Sigma_Order__c where Brewer_Account__c =: currentuser.Contact.AccountId
                             order by createddate desc limit :pageSize offset :offset];
				  r.totalSigma = [SELECT count() FROM Sigma_Order__c where Brewer_Account__c =: currentuser.Contact.AccountId];
			 	r.IsCommunityUser = true;
              }
         // }
        
        return r;
        
    }
    
    
    @AuraEnabled
    public static String deleteSigmaOrder(Id SigmaOrderId){
        /*if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Sigma_Order__c',new set<String>{'id'})
           && CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev__Sigma_Order__c')
          ){ */
              try{        
                 
                  List<Sigma_Order__c> delSigmaOrderList = [select id,TotalAmount__c,AccountId__c from Sigma_Order__c where id = :SigmaOrderId];
                  Sigma_Order__c so = delSigmaOrderList[0];
                  OrderCountCntrl.SOReduce(so);
                  delete delSigmaOrderList;
                 
              }catch(Exception e){
                  System.debug('Exception in Delete>>>>>'+e.getMessage());
                  return null;
              }
         // }
        return null;
    }
    // Code For Standard Order 
    @AuraEnabled
    public static SoPaginationHelper fetchOrderList(Decimal pageNumberOrder)
    {
        SoPaginationHelper r1;
        /*if(CRUD_FLS_CheckUtility.checkReadPermission('Order',new set<String>{'id','AccountId','OrderNumber','Account.Name','CreatedById','TotalAmount','EffectiveDate','sigmaerpdev__Orders_Status__c','sigmaerpdev__Net_Quantity__c'})
          ){ */
            
              Integer pageSize = 10;
              Integer offset = ((Integer)pageNumberOrder - 1) * pageSize;
              
              r1 =  new SoPaginationHelper();
              r1.pageSizeOrder = pageSize;
              r1.pageOrder = (Integer) pageNumberOrder;
              r1.totalOrder = [SELECT count() FROM Order];
              
              r1.OrderList = [select id,AccountId,OrderNumber,Account.Name,CreatedById,TotalAmount,EffectiveDate,Orders_Status__c,Net_Quantity__c,Is_Payment_Made__c from Order
                              order by createddate desc limit :pageSize offset :offset];
              
          //}
        
        return r1;
        
    }
    @AuraEnabled
    public static String deleteOrder(Id OrderId){
        /*if(CRUD_FLS_CheckUtility.checkReadPermission('Order',new set<String>{'id'})
           && CRUD_FLS_CheckUtility.checkObjCRUD('Order')
          ){*/
              try{        
                   List<Order> delOrderList = [select id from Order where id = :OrderId];
                  delete delOrderList;
              }catch(Exception e){
                  System.debug('Exception in Order Delete>>>>>'+e.getMessage());
                  return null;
              }
          //}
        return null;
    }
    
    //CODE FOR VALIDATION OF SIGMA ORDER FROM CUSTOM SETTINGS 
    @AuraEnabled
    public Static customWrapper  OrderUsage(){
        
        customWrapper cu = new customWrapper();
        /*if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Order_Usage__c',new set<String>{'sigmaerpdev__Sigma_order__c','sigmaerpdev__Standard_object__c'})
           && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Time_Base_Inventory__c',new set<String>{'sigmaerpdev__Order__c','sigmaerpdev__Proposal__c','sigmaerpdev__Proposal_for_Products__c','sigmaerpdev__Proposal_to_Order__c'})
           && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Order_API__c',new set<String>{'sigmaerpdev__Subscription_Product__c','sigmaerpdev__Subscription_Renewal__c'})
          ){*/
              cu.ou = [Select Sigma_order__c,Standard_object__c from Order_Usage__c limit 1];
              cu.tmi = [Select Order__c,Proposal__c,Proposal_for_Products__c,Proposal_to_Order__c from Time_Base_Inventory__c limit 1];
              cu.OP =[select Subscription_Product__c,Subscription_Renewal__c from Order_API__c limit 1] ; 
          //}
        return cu;
    }
    
    public class customWrapper{
        @AuraEnabled
        public Order_Usage__c ou{get;set;}
        @AuraEnabled        
        public Time_Base_Inventory__c tmi{get;set;}
        @AuraEnabled 
        public Order_API__c OP{get;set;}
    }
    
    // Code For handling proposal Component 
    @AuraEnabled
    public static SoPaginationHelper fetchProposalList(Decimal pageNumberProposal)
    {
        SoPaginationHelper Prop;
        /*if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Proposal__c',new set<String>{'id','Name','sigmaerpdev__Usage_Type__c','sigmaerpdev__Proposal_Name__c','sigmaerpdev__Agency__c','sigmaerpdev__Agency__r.Name','sigmaerpdev__Client__c','sigmaerpdev__Client__r.Name','sigmaerpdev__Status__c','sigmaerpdev__Is_Order_Created__c'})
          ){*/
              Integer pageSize = 10;
              Integer offset = ((Integer)pageNumberProposal - 1) * pageSize;
              
              Prop =  new SoPaginationHelper();
              Prop.pageSizeProp = pageSize;
              Prop.pageProp = (Integer) pageNumberProposal;
              Prop.totalProp = [SELECT count() FROM Proposal__c];
              
              Prop.PropList = [select id,Name,Proposal_Name__c,Usage_Type__c,Client__r.Name,Agency__c,Agency__r.Name,Client__c,Status__c,Is_Order_Created__c from 
                               Proposal__c order by createddate desc limit :pageSize offset :offset];
             
          //}
        return Prop;
    }
    
    
    // deleting proposal
    @AuraEnabled
    public static String deleteproposal(Id propId){
        /*if(CRUD_FLS_CheckUtility.checkReadPermission('Order',new set<String>{'id'})
           && CRUD_FLS_CheckUtility.checkObjCRUD('Order')
          ){*/
              try{        
                   List<Proposal__c> delpropList = [select id from Proposal__c where id = :propId];
                  delete delpropList;
                  
              }catch(Exception e){
                  System.debug('Exception in proposal Delete>>>>>'+e.getMessage());
                  return null;
              }
          //}
        return null;
    }
    //CODE FOR VALIDATION OF Proposal FROM CUSTOM SETTINGS 
    @AuraEnabled
    public Static Time_Base_Inventory__c  TBIVal(){
        
        Time_Base_Inventory__c TBI = new Time_Base_Inventory__c();
        /*if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Time_Base_Inventory__c',new set<String>{'sigmaerpdev__Order__c','sigmaerpdev__Proposal__c','sigmaerpdev__Proposal_for_Products__c','sigmaerpdev__Proposal_to_Order__c'})
          ){*/
              TBI = [Select Order__c,Proposal__c,Proposal_for_Products__c,Proposal_to_Order__c from Time_Base_Inventory__c limit 1];
          //}
        return TBI;
    }
    
    @AuraEnabled
    public static Helpmenuwrap fetchJSONHelpMenu()
    {    
        Helpmenuwrap hlpWrap = new Helpmenuwrap();
        Id UserId= UserInfo.getUserId();
            User currentuser = [select Id,Profile.Name,Contact.AccountId from User where Id =: UserId];
            Community_Configuration__c Custset= [select Id,Name,Retailer_Community_URL__c,Products_Per_Page__c,Retailer_Profile_Name__c,Vendor_Community_URL__c,Vendor_Profile_Name__c from Community_Configuration__c where Name = 'Community Configurations' LIMIT 1];
            
                
        StaticResource sr= [select id, body from StaticResource Where Name = 'JSONStructureForSalesOrderModulesHelpMenu'];
        string allContent = sr.body.toString();
        Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(allContent);
        List<Object> trails = (List<Object>) results.get('Menu');
        hlpWrap.TralilsList = trails;
        if(currentuser.Profile.Name != Custset.Retailer_Profile_Name__c)
        	hlpWrap.CommunityUser = false;
        else
            hlpWrap.CommunityUser = true;
        return hlpWrap; 
    }   
    public class Helpmenuwrap
    {
        @AuraEnabled
        public List<object> TralilsList;
        @AuraEnabled
        public boolean CommunityUser;
    }
}