SigmaCodebackup3rdSep/objects/Currency__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <externalId>true</externalId>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Symbol__c</fullName>
        <label>Symbol</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Currency_Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Currency Exchange Rates</relationshipLabel>
        <relationshipName>Currency_Exchange_Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <label>Currency Exchange Rate</label>
    <nameField>
        <displayFormat>XR-{00}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency Exchange Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exchange Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <label>Net Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Partial Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Partial Delivery</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Net Buying Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Discount(%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Exchange_Net_Buying_Price__c</fullName>
        <label>Exchange Net Buying Price</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exchange_Price__c</fullName>
        <label>Exchange Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Order Quantity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <label>Remaining Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Buying_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Buying Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VendorPrice__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VendorPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Order Product</label>
    <nameField>
        <displayFormat>POP-{0000}</displayFormat>
        <label>Purchase Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Vendor_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vender_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Buying Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Stock__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Stock</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Preferred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preferred Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vendor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VendorProductCode__c</fullName>
        <label>Vendor Product Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Vendor Product</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Vendor Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/MultiplePOCtrl.cls
public with sharing class MultiplePOCtrl 
{
    public static Purchase_Order__c POList {get;set;}
    public static List<Purchase_Order_Product__c> POPList{get;set;}
    
    public class MultiplePO{
        @AuraEnabled
        public Vendor_Product__c vpdata;
        @AuraEnabled
        public Boolean isSelected= false;
        @AuraEnabled
        public String productName;
        @AuraEnabled
        public Date OrderDate;
        @AuraEnabled
        public String vendorName;
        @AuraEnabled
        public Integer orderedQty;
        @AuraEnabled
        public Integer discount;
        @AuraEnabled
        public Integer buyingPrice;
        @AuraEnabled
        public Date deliveryDate;
        @AuraEnabled
        public String selectedStatus;
    }
    
    @AuraEnabled
    public static void saveAccounts(List<Account> accList){
        Insert accList;
    }
    @AuraEnabled
    public static List<Vendor_Product__c> getAccountRecord(Id productId)
    {
        MultiplePO mw = new MultiplePO();
        List<Vendor_Product__c> vptlist =[Select id,Name,VendorProductCode__c,Account_Name__c,Current_Stock__c,Product_Name__c,Is_Preferred__c,Buying_Price__c from Vendor_Product__c Where Product_Name__c=:productId];
        
        return vptlist;
    }
    
    @AuraEnabled
    public static Id CreatePO(Purchase_Order__c POObject,String POProductObject) 
    {           
        system.debug('POObject-->>'+POObject);
        insert POObject;
        system.debug('POObject>>'+POObject);
        
        Currency__c currSymbol = null; 
        Currency_Exchange_Rate__c currExRate = null ;
        List<string> pString =new List<string>();   
        List<Purchase_Order__c > pOrder = [select id,Currency__c from Purchase_Order__c where Id = :POObject.Id];
        for(Purchase_Order__c pList :pOrder)
        {
            if(pList.Currency__c!=null)
            {
                pString.add(pList.Currency__c);
            }
        }
        if(pString.size() > 0 )
        {
            currSymbol = [select id,Symbol__c,Currency_Code__c from Currency__c where Id =: pString limit 1];
            system.debug('currSymbol:::'+currSymbol);
            currExRate = [select id,Rate__c,Currency__c from Currency_Exchange_Rate__c where Currency__c =: pString limit 1 ];
            system.debug('currExRate>>'+currExRate);
        }
        
        List<String> selectedIdsList = new List<String>();
        Object[] values = (Object[])System.JSON.deserializeUntyped(POProductObject);
        system.debug('values>>'+values);
        if(values.size()>0)
        {         
            for (Object id : values) 
            {
                selectedIdsList.add(string.valueof(id) );
            }
        }
        String str1 = POProductObject.substring(1, POProductObject.length()-1);
        List<String> stringList = str1.split(',');
        
        List<String> strSplt = str1.split('},');
        List<String> strList = new List<String>();
        for(integer i=0;i<strSplt.size();i++)
        {
            if(i < strSplt.size()-1)
            {
                strList.add(strSplt[i]+'}');
            }
            else
            {
                strList.add(strSplt[i]);
            }
        }
        Integer len = strSplt.size();
        List<Purchase_Order_Product__c> POProductList = new List<Purchase_Order_Product__c>();
        for(Integer j=0; j<strList.size(); j++)
        {
            Purchase_Order_Product__c PoProd = new Purchase_Order_Product__c();
            List<String> stringList2 = strList[j].split(',');
            String str2 = POProductObject.substring(1, POProductObject.length()-1);
            
            String str = strList[j];
            Map<String, Object> root = (Map<String, Object>) JSON.deserializeUntyped(str);
            Purchase_Order__c  scToUpdate = [select id,Net_Quantity__c from Purchase_Order__c where Id =: POObject.Id];
            
            
            for(Integer i=0; i<strList.size(); i++)
            {
                String tempDateForChecking = String.valueOf(root.get('sigmaerpdev2__Expected_Delivery_Date__c'));
                if(!String.isBlank(tempDateForChecking))
                {
                    String[] TempDate = String.valueOf(root.get('sigmaerpdev2__Expected_Delivery_Date__c')).split('T');
                    Date tempExpectedDeliveryDate = Date.valueOf(TempDate[0]);
                    PoProd.Expected_Delivery_Date__c= tempExpectedDeliveryDate;
                }
                PoProd.Product__c = String.valueOf(root.get('sigmaerpdev2__Product__c'));
                String tempBuyingPriceForChecking =String.valueOf(root.get('sigmaerpdev2__Buying_Price__c'));
                if(!String.isBlank(tempBuyingPriceForChecking))
                {
                    PoProd.Buying_Price__c = Double.valueOf(root.get('sigmaerpdev2__Buying_Price__c'));
                }
                PoProd.Quantity__c= String.valueOf(root.get('sigmaerpdev2__Quantity__c'));
                PoProd.Purchase_Order__c = POObject.Id;
                PoProd.Status__c = String.valueOf(root.get('sigmaerpdev2__Status__c'));
                PoProd.Received_Quantity__c = Double.valueOf(root.get('sigmaerpdev2__Quantity__c'));
                if(root.get('sigmaerpdev2__Discount__c') != null){
                    PoProd.Discount__c = Double.valueOf(root.get('sigmaerpdev2__Discount__c'));
                }else{
                    PoProd.Discount__c = 0;  
                }
                
                Double exRate=0;
                string symbol='';
                Double  amt=0;
                if(currExRate!= null){
                    symbol =currSymbol.Symbol__c;
                    string rateEx = currExRate.Rate__c +'';
                    amt= Double.valueOf(rateEx)*PoProd.Buying_Price__c;
                    string currStr=symbol+' '+amt;
                    PoProd.Exchange_Net_Buying_Price__c= currStr;
                    PoProd.Exchange_Price__c = amt;
                    system.debug('sigmaerpdev2__Exchange_Total_Buying_Price_Euro__c>>'+PoProd.Exchange_Net_Buying_Price__c);
                }
                PoProd.Total_Buying_Price__c= Double.valueOf(root.get('sigmaerpdev2__Total_Buying_Price__c'));
                PoProd.VendorPrice__c= Double.valueOf(root.get('sigmaerpdev2__VendorPrice__c'));
            }
            POProductList.add(PoProd);
        }
        
        insert POProductList; 
        return POObject.Id;
    }
}