SigmaCodebackup3rdSep/objects/Currency__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <externalId>true</externalId>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Default_Currency__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Default Currency</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Symbol__c</fullName>
        <label>Symbol</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/HandleCurrencyTest.cls
@isTest
public class HandleCurrencyTest{
@isTest(SeeAllData=false)
    public static void test(){
        
        Currency__c c=new Currency__c();
        c.Name='IL-0224';
        c.Is_Default_Currency__c=true;
         insert c;
         system.assertEquals(c.Is_Default_Currency__c,true);
         
         List<Currency__c> currencies=new List<Currency__c>();  
           currencies.add(c);    
          Test.startTest();
          
          HandleCurrency curr=new HandleCurrency();
          
          curr.onBeforeInsert(currencies);
          Test.stopTest();    
    }
    @isTest(SeeAllData=false)
    public static void test1(){
        
        Currency__c c1=new Currency__c();
        c1.Name='USD Dollar';
        c1.Symbol__c='';
        c1.Is_Default_Currency__c=true;
        c1.Currency_Code__c='qwe';
         insert c1;
         update c1;
         system.assertEquals(c1.Is_Default_Currency__c,true);
         List<Currency__c> currencies1=new List<Currency__c>();  
            currencies1.add(c1);   
          Test.startTest();
          
          HandleCurrency curr=new HandleCurrency();
          
          Test.stopTest();    
    }
    
}