SigmaCodebackup3rdSep/objects/Currency__c.object
<CustomObject>
    <fields>
        <fullName>Symbol__c</fullName>
        <label>Symbol</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Currency_Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Currency Exchange Rates</relationshipLabel>
        <relationshipName>Currency_Exchange_Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <label>Currency Exchange Rate</label>
    <nameField>
        <displayFormat>XR-{00}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency Exchange Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Price__c.object
<CustomObject>
    <label>Product Price</label>
    <nameField>
        <label>Product Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/Product_Trigger_Helper.cls
public with sharing class Product_Trigger_Helper 
{
    public static void insertProduct(List<Product2> listOfpro)
    {
        Map<Id,Id>ProCurrIds=new Map<Id,Id>();
        System.debug('listOfpro=='+listOfpro);
        for(Product2 pro : listOfpro)
        {
            if(pro.Currency__c!=null )
            {
                ProCurrIds.put(pro.Id,pro.Currency__c);
                System.debug('ProCurrIds::'+ProCurrIds);
            }
        }
        System.debug('ProCurrIds::'+ProCurrIds);
        List<Id>currIds=ProCurrIds.values();
        if(currIds!=null &&  currIds.size()>0)
        {
            System.debug('currIds::'+currIds);
            List<Currency_Exchange_Rate__c> currExRate = [select id,Rate__c from Currency_Exchange_Rate__c where Currency__c =:currIds limit 1];
            System.debug('currExRate::'+currExRate);
            List<Currency__c>  crr=[select id,name,Symbol__c from Currency__c where id=:currIds limit 1]; 
            System.debug('crr::'+crr);
            // List<Product2>products= [select Product_Price__c,Exchange_Selling_Price__c,Exchange_Average_Selling_Price__c,Buying_Price__c from  Product2 where id=:ProCurrIds.keySet()];
            List<Product2>productsNew =new List<Product2>();
            System.debug('listOfpro::'+listOfpro);
            for(Product2 pro : listOfpro)
            {
                Product2 p=new Product2();
                if(pro.Product_Price__c!=null && currExRate[0].Rate__c!=null )
                {
                    Double amt=pro.Product_Price__c*currExRate[0].Rate__c;
                    string amtwithSymbol=crr[0].Symbol__c+amt;
                    system.debug('amtwithSymbol>>>'+amtwithSymbol); 
                    // String Rate=currExRate[0].Rate__c+'';
                    //  String ProductPrice= pro.Product_Price__c+'';
                    if(amtwithSymbol!=null)
                    {
                        pro.Exchange_Selling_Price__c=amtwithSymbol;
                    } 
                }
                if(pro.Buying_Price__c!=null && currExRate[0].Rate__c!=null)
                {
                    Double amt2=pro.Buying_Price__c*currExRate[0].Rate__c;
                    string amtwithSymbol2=crr[0].Symbol__c+amt2;
                    system.debug('amtwithSymbol>>>'+amtwithSymbol2);
                    if(amtwithSymbol2!=null)
                    {
                        pro.Exchange_Average_Selling_Price__c=amtwithSymbol2;     
                    }  
                }    
            }
        } 
    }
    public static void updateProduct(List<Product2> listOfpro)
    {
        Map<Id,Id>ProCurrIds=new Map<Id,Id>();
        System.debug('listOfpro=='+listOfpro);
        for(Product2 pro : listOfpro)
        {
            if(pro.Currency__c!=null)
            {
                ProCurrIds.put(pro.Id,pro.Currency__c);
                System.debug('ProCurrIds::'+ProCurrIds);
            }
        }
        System.debug('ProCurrIds::'+ProCurrIds);
        List<Id>currIds=ProCurrIds.values();
        if(currIds!=null &&  currIds.size()>0)
        {
            System.debug('currIds::'+currIds);
            List<Currency_Exchange_Rate__c> currExRate = [select id,Rate__c from Currency_Exchange_Rate__c where Currency__c =:currIds limit 1];
            System.debug('currExRate::'+currExRate);
            List<Currency__c>  crr=[select id,name,Symbol__c from Currency__c where id=:currIds limit 1]; 
            System.debug('crr::'+crr);
            // List<Product2>products= [select Product_Price__c,Exchange_Selling_Price__c,Exchange_Average_Selling_Price__c,Buying_Price__c from  Product2 where id=:ProCurrIds.keySet()];
            List<Product2>productsNew =new List<Product2>();
            System.debug('listOfpro::'+listOfpro);
            for(Product2 pro : listOfpro)
            {
                Product2 p=new Product2();
                if(pro.Product_Price__c!=null && currExRate[0].Rate__c!=null )
                {
                    Double amt=pro.Product_Price__c*currExRate[0].Rate__c;
                    string amtwithSymbol=crr[0].Symbol__c+amt;
                    system.debug('amtwithSymbol>>>'+amtwithSymbol); 
                    // String Rate=currExRate[0].Rate__c+'';
                    //  String ProductPrice= pro.Product_Price__c+'';
                    if(amtwithSymbol!=null)
                    {
                        pro.Exchange_Selling_Price__c=amtwithSymbol;
                    }
                }
                if(pro.Buying_Price__c!=null && currExRate[0].Rate__c!=null)
                {
                    Double amt2=pro.Buying_Price__c*currExRate[0].Rate__c;
                    string amtwithSymbol2=crr[0].Symbol__c+amt2;
                    system.debug('amtwithSymbol>>>'+amtwithSymbol2);
                    if(amtwithSymbol2!=null)
                    {
                        pro.Exchange_Average_Selling_Price__c=amtwithSymbol2;     
                    }  
                }   
            }
        }
    }  
}