SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <label>Parent Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Inventory1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Inventory</relationshipLabel>
        <relationshipName>Product_Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Locations (Location)</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Adjusted_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adjusted Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Delivered_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sold Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Received Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/ChangeCurrentAvailInventTriggerTest.cls
@isTest 
Public class ChangeCurrentAvailInventTriggerTest
{
  @IsTest(seeAllData=false)
   public static void methodOne()
  {
        Test.startTest();
        
        Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos(); 
        Id RID1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
         Account acc = new Account();
        acc.Name = 'Test';
        acc.Email__c = 'cus@gmail.com';
        acc.RecordTypeId = RID1;
        insert acc;
        system.assertEquals(acc.Name,'Test');
        
        Default_Parameters__c  dp = new Default_Parameters__c (Name = 'Sample dp',Parent_Id__c = acc.Id);
        insert dp;
        system.assertEquals(dp.Name,'Sample dp');
        
         Id RID3 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
        Account acc3 = new Account();
        acc3.Name = 'Test1';
        acc3.RecordTypeId = RID3;
        acc3.Type = 'Location';
        acc3.Email__c = 'Test@test.com';
        insert acc3;
        system.assertEquals(acc3.Name,'Test1');
        
        Product2 Pro1 = new Product2(Name='Product - 1',SKU__c = 'TP001',Stock_Item__c=true);
        Insert Pro1;
        system.assertEquals('Product - 1',Pro1.Name);

        Inventory__c i1 = [select id from Inventory__c where ProductCode__c =: Pro1.Id];
        Inventory_Location__c il = new Inventory_Location__c(Location__c = acc3.Id);
        insert il;
        system.assertEquals(il.Location__c,acc3.Id);
        
        Inventory_Location_Product__c ilp1 = new Inventory_Location_Product__c(Inventory_Location__c =il.Id,Adjusted_Quantity__c=1,Received_Quantity__c=100, Products__c = Pro1.Id,Inventory__c = i1.Id, Delivered_Quantity__c = 0 );
        insert ilp1;    
        system.assertEquals(ilp1.Inventory_Location__c,il.Id);
        Test.stopTest();
     
  }
}