SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <label>Parent Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Lot__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lot</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Lot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Lot_Product__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Lot Products</relationshipLabel>
        <relationshipName>Lot_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Lot__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Lot Products</relationshipLabel>
        <relationshipName>Lot_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lot Product</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Lot Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Product_Supplier__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Supplier, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Partial Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Partial Delivery</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Net Buying Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Order Quantity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <label>Remaining Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <formula>Purchase_Order__r.Product_Supplier__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
    <label>Purchase Order Product</label>
    <nameField>
        <displayFormat>POP-{0000}</displayFormat>
        <label>Purchase Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Stock_In__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stock Receiving</relationshipLabel>
        <relationshipName>Stock_In1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Stock Receiving (Purchase Order)</relationshipLabel>
        <relationshipName>Stock_In</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stock Receiving (Vendor)</relationshipLabel>
        <relationshipName>Stock_Receiving</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Stock Receiving</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Stock In Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Receiving</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Stock_In_Product__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <formula>Stock_In__r.Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>temporary Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Stock Receiving Products</relationshipLabel>
        <relationshipName>Stock_Receiving_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order Product</label>
        <referenceTo>Purchase_Order_Product__c</referenceTo>
        <relationshipLabel>Stock Receiving Products</relationshipLabel>
        <relationshipName>Stock_In_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stock_In__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock In</label>
        <referenceTo>Stock_In__c</referenceTo>
        <relationshipLabel>Stock Receiving Products</relationshipLabel>
        <relationshipName>Stock_In_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <formula>Stock_In__r.Vendor__r.Name</formula>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
    <label>Stock Receiving Product</label>
    <nameField>
        <displayFormat>SIP-{0000}</displayFormat>
        <label>Stock In Products Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Receiving Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Vendor_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vender_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Buying Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Preferred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preferred Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vendor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vendor Product</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Vendor Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/ManageInventoryLocationTriggerTest.cls
@isTest 
Public class ManageInventoryLocationTriggerTest
{
   @IsTest(seeAllData=false)
   public static void methodOne()
  {
            Test.startTest();

            List<Stock_In__c> stk = new List<Stock_In__c>{};

            Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
            List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();

            String RID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();

            String RID1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();

             String RID2 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();

            Account testaccmerchant = new Account(Name= 'Test Merchant 4', Type = 'Merchant',Email__c='suhasn91@gmail.com',Web_Order_Type__c= 'Percentage', Web_Order_Value__c =40);
            insert testaccmerchant;
            System.assertEquals(testaccmerchant.Name,'Test Merchant 4');  

            Account accNew = new Account();
            accNew.Name = 'Test';
            accNew.Type = 'Location';
            accNew.Email__c='df@gmail.com';
            insert accNew;
            system.assertEquals('Test',accNew.Name);
            
          

            Default_Parameters__c  dftPr = new Default_Parameters__c ();
            dftPr.Name = 'ELift Merchant';
            dftPr.Parent_Id__c  = accNew.Id;
            insert dftPr;    
            system.assertEquals('ELift Merchant',dftPr.Name);

            Account acc = new Account();
            acc.name ='xyz';
            acc.Type='Location';
            acc.RecordTypeID =RID  ;
            insert acc;
            system.assertEquals('xyz',acc.Name);

            Account acc1 = new Account();
            acc1.name ='xy44z';
            acc1.Type='Location';
            acc1.RecordTypeID =RID1  ;
            insert acc1;
            system.assertEquals('xy44z',acc1.Name);

            Account acc2 = new Account();
            acc2.name ='xyz11';
            acc2.Type='Vendor';
            acc2.Email__c='kj@gmail.com';
            acc2.RecordTypeID =RID2  ;
            insert acc2;
            system.assertEquals('xyz11',acc2.Name);

            Product2  pro=new  Product2();
            pro.Name='JMTEST';
            pro.Attribute_Type__c = 'SERIALIZED';
            insert pro;
            system.assertEquals('JMTEST',pro.Name);
            Account accVendor = new Account();
            accVendor.Name = 'TestaccVendor';
            accVendor.Email__c='sdf@gmail.com';
            accVendor.Type = 'Vendor';
            insert accVendor;
            system.assertEquals(accVendor.Type,'Vendor');
            
        Vendor_Product__c vp  = new Vendor_Product__c();
        vp.Product_Name__c = pro.id;
        vp.Account_Name__c = accVendor.Id;
        vp.Buying_Price__c = 200;
        vp.Is_Preferred__c=true;
        insert vp;
        system.assertEquals(vp.Buying_Price__c , 200);

              
            Purchase_Order__c PO = new Purchase_Order__c();
            PO.Product_Supplier__c =acc2.Id;
            insert PO;
            System.assertEquals( PO.Product_Supplier__c,acc2.Id);

            Purchase_Order_Product__c POP = new Purchase_Order_Product__c();
            POP.Purchase_Order__c =PO.ID;
            POP.Received_Quantity__c=10;
            POP.Quantity__c = '1';
            POP.Product__c = pro.Id;
            insert POP;
            System.assertEquals( POP.Purchase_Order__c,PO.ID);

            Stock_In__c s = new Stock_In__c();
            s.Location__c = acc.ID;
            s.Vendor__c = acc2.Id;
            s.Purchase_Order__c = PO.Id;
            s.Status__c = 'Open';
            insert s;
            System.assertEquals(s.Location__c,acc.ID);

            dftPr.StockReceiving_ID__c = s.Id;
            update dftPr;
            System.assertEquals(dftPr.StockReceiving_ID__c,s.Id);         


            Lot__c lot1 = new Lot__c();
            lot1.Lot_Name__c = 'Test Lot';
            lot1.Product__c = pro.Id;
            lot1.Quantity__c = 10;
            lot1.Created_Date__c = system.today();
            lot1.Expiry_Date__c =  system.today()+5;
            insert lot1;
            System.assertEquals(lot1.Lot_Name__c,'Test Lot');   

            Lot_Product__c lotProd1 = new Lot_Product__c();
            lotProd1.Lot__c = lot1.Id;
            lotProd1.Product__c = pro.Id;
            lotProd1.Quantity__c = 10; 
            insert lotProd1;
            System.assertEquals(lotProd1.Lot__c,lot1.Id); 

            List<Lot__c> lt = new List<Lot__c>();
            Lot__c lot = new Lot__c();
            lot.Lot_Name__c = 'test';
            lot.Product__c = pro.Id;
            lot.Created_Date__c = system.today();
            lot.Expiry_Date__c =  system.today()+5;
            lt.add(lot);
            insert lt;
            System.assertEquals(lot.Lot_Name__c,'test'); 



            List<Lot_Product__c> lp = new  List<Lot_Product__c>();
            Lot_Product__c lprd = new Lot_Product__C();
            lprd.Lot__c = lt[0].Id;
            lp.add(lprd);
            insert lp;
            System.assertEquals(lprd.Lot__c,lt[0].Id); 

            Stock_In_Product__c stkPrd = new Stock_In_Product__c();
            stkPrd.Stock_In__c =s.Id ;
            stkPrd.Quantity_Received__c =4;
            stkPrd.Status__c ='Open';
            stkPrd.Putaway_location__c = acc1.ID;
            stkPrd.Purchase_Order__c =POP.Id ;
            stkPrd.pur_Order__c =PO.Id;
            stkPrd.Product__c = pro.Id;
            stkPrd.Lot__c = lot1.Id;
            insert stkPrd;
            System.assertEquals(stkPrd.Lot__c,lot1.Id);

            stkPrd.Status__c = 'Verified';
            update stkPrd;
            System.assertEquals(stkPrd.Lot__c,lot1.Id);



            Test.stopTest();
        }
        
        @IsTest(seeAllData=false)
   public static void methodTwo()
  {
                Test.startTest();

                List<Stock_In__c> stk = new List<Stock_In__c>{};

                Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
                List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();

                String RID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();

                String RID1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();

                String RID2 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();


                Account testaccmerchant = new Account(Name= 'Test Merchant 4', Type = 'Merchant',Email__c='suhasn91@gmail.com',Web_Order_Type__c= 'Percentage', Web_Order_Value__c =40);
                insert testaccmerchant;
                System.assertEquals(testaccmerchant.Name,'Test Merchant 4');  

                Account accNew = new Account();
                accNew.Name = 'Test';
                accNew.Type = 'Location';
                accNew.Email__c='svd@gmail.com';
                insert accNew;
                system.assertEquals('Test',accNew.Name);

                Default_Parameters__c  dftPr = new Default_Parameters__c ();
                dftPr.Name = 'ELift Merchant';
                dftPr.Parent_Id__c  = accNew.Id;
                insert dftPr;    
                system.assertEquals('ELift Merchant',dftPr.Name);

                Account acc = new Account();
                acc.name ='xyz';
                acc.Type='Location';
                acc.RecordTypeID =RID  ;
                insert acc;
                system.assertEquals('xyz',acc.Name);

                Account acc1 = new Account();
                acc1.name ='xyz1';
                acc1.Type='Location';
                acc1.RecordTypeID =RID1  ;
                insert acc1;
                system.assertEquals('xyz1',acc1.Name);

                Account acc2 = new Account();
                acc2.name ='xyz11';
                acc2.Type='Vendor';
                acc2.Email__c='hjh@gmail.com';
                acc2.RecordTypeID =RID2  ;
                insert acc2;
                system.assertEquals('xyz11',acc2.Name);

                Product2  pro=new  Product2();
                pro.Name='JMTEST';
                pro.Attribute_Type__c = 'SERIALIZED';
                insert pro;
                system.assertEquals('JMTEST',pro.Name);
                
            Account accVendor = new Account();
            accVendor.Name = 'TestaccVendor';
            accVendor.Type = 'Vendor';
            accVendor.Email__c='sg@gmail.com';
            insert accVendor;
            system.assertEquals(accVendor.Type ,'Vendor');
                
        Vendor_Product__c vp  = new Vendor_Product__c();
        vp.Product_Name__c = pro.id;
        vp.Account_Name__c = accVendor.Id;
        vp.Buying_Price__c = 200;
        vp.Is_Preferred__c=true;
        insert vp;
        system.assertEquals(vp.Is_Preferred__c,true);

                
                

                Purchase_Order__c PO = new Purchase_Order__c();
                PO.Product_Supplier__c =acc2.Id;
                insert PO;
                System.assertEquals( PO.Product_Supplier__c,acc2.Id);

                Purchase_Order_Product__c POP = new Purchase_Order_Product__c();
                POP.Purchase_Order__c =PO.ID;
                POP.Received_Quantity__c=10;
                POP.Quantity__c = '1';
                POP.Product__c = pro.Id;
                insert POP;
                System.assertEquals( POP.Purchase_Order__c,PO.ID);

                Stock_In__c s = new Stock_In__c();
                s.Location__c = acc.ID;
                s.Vendor__c = acc2.Id;
                s.Purchase_Order__c = PO.Id;
                s.Status__c = 'Open';
                insert s;
                System.assertEquals(s.Location__c,acc.ID);

                dftPr.StockReceiving_ID__c = s.Id;
                update dftPr;
                System.assertEquals(dftPr.StockReceiving_ID__c,s.Id);         


                Lot__c lot1 = new Lot__c();
                lot1.Lot_Name__c = 'Test Lot';
                lot1.Product__c = pro.Id;
                lot1.Quantity__c = 10; 
                lot1.Created_Date__c = system.today();
                lot1.Expiry_Date__c =  system.today()+5;
                insert lot1;
                System.assertEquals(lot1.Lot_Name__c,'Test Lot');   

                Lot_Product__c lotProd1 = new Lot_Product__c();
                lotProd1.Lot__c = lot1.Id;
                lotProd1.Product__c = pro.Id;
                lotProd1.Quantity__c = 10; 
                insert lotProd1;
                System.assertEquals(lotProd1.Lot__c,lot1.Id); 

                List<Lot__c> lt = new List<Lot__c>();
                Lot__c lot = new Lot__c();
                lot.Lot_Name__c = 'test';
                lot.Product__c = pro.Id;
                lot.Created_Date__c = system.today();
                lot.Expiry_Date__c =  system.today()+5;
                lt.add(lot);
                insert lt;
                System.assertEquals(lot.Lot_Name__c,'test'); 

                List<Lot_Product__c> lp = new  List<Lot_Product__c>();
                Lot_Product__c lprd = new Lot_Product__C();
                lprd.Lot__c = lt[0].Id;
                lp.add(lprd);
                insert lp;
                System.assertEquals(lprd.Lot__c,lt[0].Id); 

                Stock_In_Product__c stkPrd = new Stock_In_Product__c();
                stkPrd.Stock_In__c =s.Id ;
                stkPrd.Quantity_Received__c =4;
                stkPrd.Status__c ='Open';
                stkPrd.Putaway_location__c = acc1.ID;
                stkPrd.Purchase_Order__c =POP.Id ;
                stkPrd.pur_Order__c =PO.Id;
                stkPrd.Product__c = pro.Id;
                stkPrd.Lot__c = lot1.Id;
                insert stkPrd;
                System.assertEquals(stkPrd.Lot__c,lot1.Id);


                System.assertEquals(stkPrd.Lot__c,lot1.Id);

                delete stkPrd;
                System.assertEquals(stkPrd.Lot__c,lot1.Id);

                Test.stopTest();
        }
}