SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>POId__c</fullName>
        <label>POId</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <label>Parent Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Supplier__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Supplier, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Partial Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Partial Delivery</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Net Buying Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Order Quantity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order Product</label>
    <nameField>
        <displayFormat>POP-{0000}</displayFormat>
        <label>Purchase Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Vendor_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vender_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Buying Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Preferred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preferred Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vendor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vendor Product</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Vendor Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/TriggerTo_Delete_ChildRecordsOf_PO_Test.cls
/*------------------------------------------------------------
    Company: Mindlinks Solution
    Module Name : Inventory History
    Description: A Test Class for the class TriggerTo_Delete_ChildRecordsOf_P0
    Author :<Banu Prakash>  
    Elift version 1.0 
    since :Winter 17 Force.com IDE, API version "38.0"
   Date : 10-01-2017
  ------------------------------------------------------------*/


@isTest
public class TriggerTo_Delete_ChildRecordsOf_PO_Test
{       
    @isTest(SeeAllData=false)
      static void test() 
      {
        Test.startTest();
        Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
        String RID2 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
            
        Account acc1 = new Account();
        acc1.name ='xyz';
        acc1.Type='Merchant';
        acc1.RecordTypeID =RID2  ;
        acc1.Email__c='abcd@gmail.com';
        insert acc1;
        System.assertequals(acc1.Type,'Merchant');
        
        Account  acc=new Account();
        acc.Name='Testvendor';
        acc.Type='vendor';
        acc.Email__c='abcd@gmail.com';
        acc.RecordTypeID =RID2  ;
        insert acc;
        System.assertequals(acc.Type,'vendor');
    
        Default_Parameters__c DP = new Default_Parameters__c();
        DP.name ='test';
        DP.Parent_Id__c = acc1.Id;
        DP.POId__c ='/a0h/o'; 
        insert DP;
        System.assertequals(DP.name,'test');
    
        Product2  pro=new  Product2();
        pro.Name='JMTEST';
        pro.Attribute_Type__c = 'SERIALIZED';
        insert pro;
     System.assertequals(pro.Name,'JMTEST');
     
        Vendor_Product__c VP = new Vendor_Product__c();
        VP.Account_Name__c = acc.Id;
        VP.Product_Name__c = pro.Id;
        vp.Buying_Price__c = 200;
        vp.Is_Preferred__c=true;
        insert VP;
        System.assertequals(VP.Account_Name__c,acc.Id);
        
        Purchase_Order__c po = new Purchase_Order__c(); 
        PO.Product_Supplier__c = acc.Id;
        PO.Status__c = 'Open';
        PO.Order_Date__c = Date.today();
        insert po;
        System.assertequals(po.Status__c,'Open');
        
        List<Purchase_Order_Product__c> POP = new List<Purchase_Order_Product__c>(); 
        Purchase_Order_Product__c POindiv = new Purchase_Order_Product__c();
        POindiv.Product__c = pro.Id;
        POindiv.Quantity__c ='10';
        POindiv.Status__c = 'Open';
        POindiv.Purchase_Order__c = PO.Id;
        POP.add(POindiv);
        insert POP;
        System.assertequals(POindiv.Status__c,'Open');
        
        try 
        {  
         delete po;  
         System.Assert(true, 'POP successfully deleted upon deletion of respective PO');  
        }
         catch(DMLException e)
         {  
          System.assert(false, 'Deletion failed ');
         }
         Test.stopTest();
      }
 }