SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Vendor__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Create Auto Po from the Default vendor of the product when Product Inventory quantity goes below threshold quantity</inlineHelpText>
        <label>AutoPO Based On Default Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inventory_Status__c</fullName>
        <label>Inventory Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Expenditure__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Expenditures</relationshipLabel>
        <relationshipName>Expenditures</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Expenditures</relationshipLabel>
        <relationshipName>Expenditures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Travel_Expenditure__c</fullName>
        <label>Travel Expenditure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Expenditure</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ExpenditureNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenditures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Consumed_Quantity__c</fullName>
        <label>Consumed Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Consumptions</relationshipLabel>
        <relationshipName>Inventory_Consumptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Inventory Consumptions</relationshipLabel>
        <relationshipName>Inventory_Consumptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reserve_Quantity__c</fullName>
        <label>Reserve Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Consumption</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>IC-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Consumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Quantity__c</fullName>
        <label>Actual Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Locations (Location)</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <formula>TEXT( Products__r.Attribute_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <label>Attribute Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BULK</fullName>
                </value>
                <value>
                    <fullName>SERIALIZED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <formula>(Received_Quantity__c +Adjusted_Quantity__c +AdjustedReceivedqty_c__c  +  Rental_Adjustment_Quantity__c ) -(Used_Quantity__c  +  Reserved_Quantity__c  + Rental_Reserved_Quantity__c +  AvailableAdjustedQty__c +Adjusted_Quantity1__c + Reduced_Adjusted_Quantity__c +Delivered_Quantity__c+Package_Quantity__c+Shipped_Quantity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location Product Line Item</label>
    <nameField>
        <displayFormat>ILPLI-{0}</displayFormat>
        <label>Inventory Location Product LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Product Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Project2__c.object
<CustomObject>
    <fields>
        <fullName>Expenditure_Record_Count__c</fullName>
        <label>Expenditure Record Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Expenditure__c</fullName>
        <label>Total Expenditure</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Po Approval Submission</description>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Supplier__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Supplier, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Partial Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Partial Delivery</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/CreateInventoryConversionHelperTest.cls
@isTest
public class CreateInventoryConversionHelperTest {
    @IsTest(seeAllData=false)
    public static void Test(){
    
    Account Ven= new Account();
        Ven.Name = 'Test Vendor';
        Ven.ShippingStreet = 'Test Street';
        Ven.ShippingCity = 'Test City';
        Ven.ShippingState = 'Test State';
        Ven.ShippingPostalCode = 'Test Code'; 
        Ven.Address__c ='Address';  
        Ven.ShippingCountry  = 'Test Country';
        Ven.Email__c = 'customer@gmail.com';
        Ven.RecordTypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId(); 
        insert Ven; 
        System.assertEquals(Ven.ShippingCity , 'Test City');
    
    Account loc= new Account();
        loc.Name = 'Test Location';
        loc.ShippingStreet = 'Street';
        loc.ShippingCity = 'City';
        loc.ShippingState = 'State';
        loc.ShippingPostalCode = 'Code'; 
        loc.Address__c ='Address1';  
        loc.ShippingCountry  = 'Country';
        loc.RecordTypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();   
        insert loc; 
        System.assertEquals( loc.Address__c ,'Address1');
    
     Default_Parameters__c dfp=new Default_Parameters__c();
         dfp.Default_Vendor__c=true;
         dfp.Company_Name__c='mindlinks';
         dfp.Inventory_Status__c='recieved';
         dfp.Name='Default';
         insert dfp;
         System.assertEquals(dfp.Inventory_Status__c,'recieved');
    
    Product2 pd2=new Product2();
pd2.IsActive=true;
pd2.Attribute_Type__c='BULK';
pd2.Name='po-01';
insert pd2;
System.assertEquals(pd2.Attribute_Type__c,'BULK');

Inventory_Location__c il=new Inventory_Location__c();
il.Actual_Quantity__c=20;
il.Available_Quantity__c=10;
il.Location__c=loc.id;
insert il;
System.assertEquals(il.Available_Quantity__c,10);

Purchase_Order__c po=new Purchase_Order__c();
po.Approved__c=true;
po.Expected_Delivery_Date__c=System.today();
po.Product_Supplier__c=ven.id;
insert po;
System.assertEquals(po.Product_Supplier__c,ven.id);


Project2__c p=new Project2__c();
p.Status__c='Open';
p.Template__c=true;
p.Total_Expenditure__c=4000;
p.Expenditure_Record_Count__c=1000;
insert p;
System.assertEquals(p.Total_Expenditure__c,4000);

Expenditure__c exp=new Expenditure__c();
exp.Project__c=p.id;
exp.Travel_Expenditure__c=16;
insert exp;
System.assertEquals(exp.Travel_Expenditure__c,16);


    
    Inventory_Consumption__c ic=new Inventory_Consumption__c();
    ic.Reserve_Quantity__c=10;
    ic.Product__c=pd2.id;
    ic.Project__c=p.id;
     ic.Consumed_Quantity__c=2;
    
    insert ic;
    System.assertEquals(ic.Reserve_Quantity__c,10);
    
    Inventory_Location_Product_Line_Item__c ilpli=new Inventory_Location_Product_Line_Item__c();
    ilpli.Allocated_Quantity__c=29;
    ilpli.Inventory_Location__c=il.id;
    ilpli.Product__c=pd2.id;
    ilpli.Purchase_Order__c=po.id;
    insert ilpli;
    System.assertEquals(ilpli.Allocated_Quantity__c,29);
    
    
    Inventory_Location_Product__c ilp=new Inventory_Location_Product__c();
    ilp.Inventory_Location__c=il.id;
    ilp.Products__c=pd2.id;   
    ilp.Start_Date__c=System.today();
    insert ilp;
    System.assertEquals(ilp.Products__c,pd2.id);
    
    List<Inventory_Consumption__c> ic1=new List<Inventory_Consumption__c>();
    ic1.add(ic);
    List<Id> ilpIds=new List<Id>();
    ilpIds.add(ilp.id);
    List<Id>  pro=new List<Id>();
    pro.add(p.id);
    Map<Id,Decimal> IlpliQty=new Map<Id,Decimal>();
    IlpliQty.put(ilp.id,20);
    IlpliQty.put(pd2.id,1);
    Map<Id,Decimal> reserveQty=new Map<Id,Decimal>();
    reserveQty.put(ic.id,20.00);
    reserveQty.put(pd2.id,20);
    
    Test.startTest(); 
    CreateInventoryConversionHelper.getMapOfQty2(ic1,'CONSUME');
    CreateInventoryConversionHelper.getMapOfQty(ic1,'CONSUME');
     CreateInventoryConversionHelper.getMapOfQty2(ic1,'RESERVE');
    CreateInventoryConversionHelper.getMapOfQty(ic1,'RESERVE');
    CreateInventoryConversionHelper.getMapOfIds(ilpIds,pro,IlpliQty,reserveQty,'RESERVECONSUME');
    Test.stopTest();
    }
    }