SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Company_Email__c</fullName>
        <label>Company Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Phone__c</fullName>
        <label>Company Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <type>Url</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Service_Contract__c.object
<CustomObject>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC{0000}</displayFormat>
        <label>Service Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Service_Quote__c.object
<CustomObject>
    <label>Service Quote</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Service Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Service_Quote_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Quote Line Items</relationshipLabel>
        <relationshipName>Service_Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>Service_Contract__c</referenceTo>
        <relationshipLabel>Service Quote Line Items</relationshipLabel>
        <relationshipName>Service_Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Quote__c</fullName>
        <label>Service Quote</label>
        <referenceTo>Service_Quote__c</referenceTo>
        <relationshipLabel>Service Quote Line Items</relationshipLabel>
        <relationshipName>Service_Quote_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Quote Line Item</label>
    <nameField>
        <displayFormat>SQLI-{0000}</displayFormat>
        <label>Service Quote Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Service_Quote_Payment_Terms__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Payment_Terms_1__c</fullName>
        <label>Payment Terms 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Terms_2__c</fullName>
        <label>Payment Terms 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Terms_3__c</fullName>
        <label>Payment Terms 3</label>
        <type>TextArea</type>
    </fields>
    <label>Service Quote Payment Terms</label>
</CustomObject>

SigmaCodebackup3rdSep/classes/GenerateQuotePDFContrl.cls
public with sharing class GenerateQuotePDFContrl {
    public static List<Service_Quote_Line_Item__c> PropLineItem{get; set;}
    public static Default_Parameters__c defaultparam{get;set;}
  public static Service_Quote_Payment_Terms__c servicequotepaymentterms{get;set;}
    public String orderId;
    public decimal lineItemsTotal{get;set;}
    public decimal SLNo{get;set;}
    public String dt {get;set;}
   public String servicequotename {get;set;}
    
  
  
    public GenerateQuotePDFContrl(ApexPages.StandardController controller) 
    {   
        orderId = System.currentPageReference().getParameters().get('id');
       // this.getdefaultparameter();
        this.PropLineItemMethod();
    this.servicepaymentterms();
       
    }
    public pagereference PropLineItemMethod()
  {
        lineItemsTotal = 0;
       // SLNo = 0;
        Date d = date.today();
        dt = DateTime.newInstance(d.year(),d.month(),d.day()).format('dd-MM-YYYY');
        
    if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Service_Quote_Line_Item__c')
    && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Service_Quote_Line_Item__c',new set<String>{'id','Name','sigmaerpdev2__Service_Quote__c','sigmaerpdev2__Service_Quote__r.Name','sigmaerpdev2__Service_Contract__c','sigmaerpdev2__Service_Contract__r.Name','sigmaerpdev2__Quantity__c','sigmaerpdev2__Product__c','sigmaerpdev2__Product__r.name','sigmaerpdev2__Price__c','sigmaerpdev2__Unit_Price__c'})
    && CRUD_FLS_CheckUtility.checkFLScreateAccess('sigmaerpdev2__Service_Quote_Line_Item__c',new set<String>{'sigmaerpdev2__Service_Quote__c'}))
    
    {
      PropLineItem = [select id,Name,Service_Quote__c,Service_Quote__r.Name,Service_Contract__c,Service_Contract__r.Name,Quantity__c,Product__c,Product__r.name,Price__c,Unit_Price__c from Service_Quote_Line_Item__c where Service_Quote__c =: orderId];
      for(Service_Quote_Line_Item__c SCLI : PropLineItem )
            {
                lineItemsTotal = lineItemsTotal+SCLI.Price__c;
                servicequotename =SCLI.Service_Quote__r.Name; 
            }
            
         }
       return null;
    }
    
    public static Default_Parameters__c getdefaultparameter()
    {
    if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Default_Parameters__c')
    && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Default_Parameters__c',new set<String>{'sigmaerpdev2__Company_Name__c','sigmaerpdev2__Company_Email__c','sigmaerpdev2__Company_Phone__c','sigmaerpdev2__Logo__c'})
    )
    {
      defaultparam = [SELECT Company_Name__c,Company_Email__c,Company_Phone__c,Logo__c from Default_Parameters__c Limit 1];
      
    }
        return defaultparam;
    }
  
   public pagereference  servicepaymentterms()
    {
    if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Service_Quote_Payment_Terms__c')
    && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Service_Quote_Payment_Terms__c',new set<String>{'sigmaerpdev2__Payment_Terms_1__c','sigmaerpdev2__Payment_Terms_2__c','sigmaerpdev2__Payment_Terms_3__c'})
    )
    {
      servicequotepaymentterms = [SELECT Payment_Terms_1__c,Payment_Terms_2__c,Payment_Terms_3__c from Service_Quote_Payment_Terms__c Limit 1];
    }
        return null;
    }
  
}