SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <label>Parent Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Package Location</fullName>
                </value>
                <value>
                    <fullName>Receiving Location</fullName>
                </value>
                <value>
                    <fullName>Waste Management Location</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Location</fullName>
                </value>
                <value>
                    <fullName>Storage Location</fullName>
                </value>
                <value>
                    <fullName>Shipping Location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Request__c.object
<CustomObject>
    <fields>
        <fullName>FromLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Request</relationshipLabel>
        <relationshipName>Product_Request_From_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Transfer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer</label>
        <referenceTo>Product_transfer__c</referenceTo>
        <relationshipLabel>Product Request</relationshipLabel>
        <relationshipName>Product_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transfer Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>To Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Request (To Location)</relationshipLabel>
        <relationshipName>Product_Request_To_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PRE-{0000}</displayFormat>
        <label>Product Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Request</label>
        <referenceTo>Product_Request__c</referenceTo>
        <relationshipName>Product_Request_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Transfer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer</label>
        <referenceTo>Product_transfer__c</referenceTo>
        <relationshipName>Product_Transfer_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Request_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Required Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending Transfer</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Request Line Item</label>
    <nameField>
        <displayFormat>PRLI-{0000}</displayFormat>
        <label>Product Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Request Line Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_transfer__c.object
<CustomObject>
    <fields>
        <fullName>ProductTransferToLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer To Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Transfer To Location</relationshipLabel>
        <relationshipName>Product_Transfer_To_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Request</label>
        <referenceTo>Product_Request__c</referenceTo>
        <relationshipLabel>Product Transfer</relationshipLabel>
        <relationshipName>Product_Transfer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Transfer_From_location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer From location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Transfer From Location</relationshipLabel>
        <relationshipName>Product_Transfer_From_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_Status__c</fullName>
        <label>Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Product Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Transfer</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Product Transfer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Transfer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/TestProductTransferLineItems.cls
@isTest
public class TestProductTransferLineItems {
    @isTest 
    static void test(){
        try{
            Test.startTest();
            Integer i=0;
            
            Location__c fromLocation = new Location__c(Location_Name__c = 'Central Warehouse', Location_Type__c='WareHouse');
            Location__c toLocation = new Location__c(Location_Name__c ='Truck 1', Location_Type__c='Truck');
            insert fromLocation;
            insert toLocation;
            
            system.debug('fromLocation inserted - '+fromLocation);
            system.debug('toLocation inserted - '+toLocation);
            
            List<Product_Request__c> listProductRequest = new List<Product_Request__c>();
            
            for(i=0;i<4;i++){
                if(i==0){
                    Product_Request__c tempPR = new Product_Request__c();
                    tempPR.FromLocation__c = fromLocation.Id;
                    tempPR.To_Location__c = toLocation.Id;
                    
                    tempPR.Status__c = 'Approved';
                    listProductRequest.add(tempPR);
                }
                else if(i==2){
                    Product_Request__c tempPR = new Product_Request__c();
                    tempPR.FromLocation__c = fromLocation.Id;
                    tempPR.To_Location__c = toLocation.Id;
                    
                    tempPR.Status__c = 'Approved';
                    listProductRequest.add(tempPR);
                }
                else{
                    Product_Request__c tempPR = new Product_Request__c();
                    tempPR.FromLocation__c = fromLocation.Id;
                    tempPR.To_Location__c = toLocation.Id;
                    
                    tempPR.Status__c = 'Draft';
                    listProductRequest.add(tempPR);
                }
            }
            insert listProductRequest;
            system.debug('Product Request Inserted - '+listProductRequest);
            
            Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
            List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
            Id RID1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            Account acc = new Account();
            acc.Name = 'Test';
            acc.Email__c='vid@gmail.com';
            acc.RecordTypeId = RID1;
            insert acc;
            
            
            Default_Parameters__c  dp = new Default_Parameters__c (Name = 'Sample dp',Parent_Id__c = acc.Id);
            insert dp;
            
            List<Product2> products = new List<Product2>();
            for(i=0;i<3;i++){
                
                Product2 temp = new Product2();
                temp.Name = 'Product'+i;
                temp.SKU__c = 'su2871'+i;
                temp.Active__c = True;
                temp.Minimum_Inventory__c = 10;
                temp.Maximum_Inventory__c = 15;
                temp.Replinishment_Stock__c = 10;
                products.add(temp);
                
            }
            insert products;
            system.debug('Products - '+products);
            
            Product_transfer__c productTransfer = new Product_transfer__c();
            productTransfer.Product_Transfer_From_location__c = fromLocation.Id;
            productTransfer.ProductTransferToLocation__c = toLocation.Id;
            productTransfer.Product_Request__c = listProductRequest[2].Id;
            productTransfer.Transfer_Status__c = 'Transfer Completed';
            
            insert productTransfer;
            system.debug('Product Transfer Inserted - '+productTransfer);  
            
            /*List<Product_Request_Line_Item__c> listPRLI = new List<Product_Request_Line_Item__c>();
for(i=0;i<3;i++){
if(i==1){
Product_Request_Line_Item__c tempPRLI = new Product_Request_Line_Item__c();
tempPRLI.Product__c = products[i].Id;
//tempPRLI.Product_Transfer__c = productTransfer.Id;
tempPRLI.Product_Request__c = listProductRequest[i].Id;
tempPRLI.Quantity__c = 10+i;
listPRLI.add(tempPRLI);
}
else{
Product_Request_Line_Item__c tempPRLI = new Product_Request_Line_Item__c();
tempPRLI.Product__c = products[i].Id;
tempPRLI.Product_Request__c = listProductRequest[i].Id;
tempPRLI.Quantity__c = 10+i;
listPRLI.add(tempPRLI);
}
}*/
            Product_Request_Line_Item__c tempPRLI = new Product_Request_Line_Item__c();
            tempPRLI.Product__c = products[0].Id;
            tempPRLI.Product_Request__c = listProductRequest[0].Id;
            tempPRLI.Quantity__c = 10;
            insert tempPRLI;
            system.debug('listPRLI - '+tempPRLI);
            
            Product_Request_Line_Item__c tempPRLI1 = new Product_Request_Line_Item__c();
            tempPRLI1.Id = tempPRLI.Id;
            
            try{
                tempPRLI1.Quantity__c = 12;
                update tempPRLI1;
            }
            catch(Exception e){
                system.debug('Exception in Updating - '+e);
            }
            system.debug('Update1 - '+tempPRLI1);
            Product_Request_Line_Item__c tempPRLIPT = new Product_Request_Line_Item__c();
            tempPRLIPT.Product__c = products[0].Id;
            tempPRLIPT.Product_Transfer__c = productTransfer.Id;
            tempPRLIPT.Quantity__c = 10;
            insert tempPRLIPT;
            system.debug('Insert 1 - '+tempPRLIPT);
            Product_Request_Line_Item__c tempPRLI2 = new Product_Request_Line_Item__c();
            tempPRLI2.Id = tempPRLIPT.Id;
            tempPRLI2.Quantity__c = 13;
            update tempPRLI2;
            system.debug('Update 2 - '+tempPRLI2);
            Test.stopTest();
            System.assert(true);
        }
        catch(Exception e){
            system.debug('Exception Occurred - '+e);
        }
    }
}