SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <label>Parent Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Price__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Price</label>
    <nameField>
        <label>Product Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Product_Supplier__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Supplier, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Partial Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Partial Delivery</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Net Buying Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Order Quantity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order Product</label>
    <nameField>
        <displayFormat>POP-{0000}</displayFormat>
        <label>Purchase Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Vendor_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vender_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Buying Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Preferred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preferred Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vendor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Price__c</fullName>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vendor Product</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Vendor Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/TriggerTo_Delete_ChildRecordsOf_POTest.cls
@isTest(seeAllData=false)
public class TriggerTo_Delete_ChildRecordsOf_POTest 
{
     @IsTest(seeAllData=false)
    public static void TestingForMethod4()
    {   
        Test.startTest();
       
        Account testaccmerchant = new Account(Name= 'Test Merchant 4', Type = 'Merchant',Email__c='Manun91@gmail.com', Web_Order_Value__c =40);
        insert testaccmerchant;   
        System.assertEquals(testaccmerchant.name, 'Test Merchant 4');
        
        
        Account testAccount = new Account();
        testAccount.Type = 'Vendor';
        testAccount.Name = 'TestAccountName';
        testAccount.Email__c='abc@gmail.com';
        insert testAccount;
        System.assertequals('Vendor',testAccount.Type);
        
        System.assertEquals(testAccount.name, 'TestAccountName');
        
        Purchase_Order__c testPurchaseOrder = new Purchase_Order__c();
        testPurchaseOrder.Status__c = 'Open';
        testPurchaseOrder.Product_Supplier__c = testAccount.Id;
        insert testPurchaseOrder;
        System.assertequals('Open',testPurchaseOrder.Status__c);
        
        Default_Parameters__c  dp = new Default_Parameters__c (Name = 'Sample dp',Parent_Id__c = testAccount.Id);
        insert dp;
        System.assertEquals(dp.Name,'Sample dp');
        
       /* Product2 testproduct =  new Product2 (Name= 'Test product', SKU__c='sku12345',Product_Price__c=15);
        insert testproduct;
       
        System.assertEquals(testproduct.Name,'Test product');
        
        Vendor_Product__c  vendor = new Vendor_Product__c ();
        vendor.Account_Name__c = testAccount.Id;
        vendor.Product_Name__c = testproduct.Id;
        vendor.Buying_Price__c = 500;
        insert vendor;
        
        System.assertEquals(vendor.Buying_Price__c,500); */
        
        Product2 testproduct = new Product2();
        testproduct.Name='Product - 1';
        testproduct.SKU__c = 'TP001';
        testproduct.Type__c = 'BOM';
        //testproduct.RecordTypeId = RID4;
        testproduct.Selling_Price__c= 10;
        testproduct.Product_Price__c = 100;
        testproduct.Buying_Price__c = 150;
        testproduct.Max_Discount__c = 2;        
        testproduct.Attribute_Type__c = 'SERIALIZED';
        Insert testproduct;
        system.assertEquals('Product - 1',testproduct.Name);
        
        Vendor_Product__c vp  = new Vendor_Product__c();
        vp.Product_Name__c = testproduct.id;
        vp.Account_Name__c = testAccount.Id;
        vp.Buying_Price__c = 200;
        vp.Is_Preferred__c=true;
        insert vp;
        system.assertEquals(testproduct.id,vp.Product_Name__c);
        
       
        
        Purchase_Order_Product__c testPurchaseOrderProduct = new Purchase_Order_Product__c();
        testPurchaseOrderProduct.Purchase_Order__c = testPurchaseOrder.Id;
        testPurchaseOrderProduct.Quantity__c = '1';
        insert testPurchaseOrderProduct;
        System.assertequals(testPurchaseOrder.Id,testPurchaseOrderProduct.Purchase_Order__c);
         delete testPurchaseOrderProduct ;
         delete testPurchaseOrder;
              
      
        Test.stopTest();
    }

}