SigmaCodebackup3rdSep/objects/Default_Parameters__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Vendor__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Create Auto Po from the Default vendor of the product when Product Inventory quantity goes below threshold quantity</inlineHelpText>
        <label>AutoPO Based On Default Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <label>Parent Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Rating__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Create Auto Po from the vendor name based on the Vendor Rating System when Product Inventory quantity goes below threshold quantity</inlineHelpText>
        <label>AutoPO Based On Vendor Rating</label>
        <type>Checkbox</type>
    </fields>
    <label>Default Parameters</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Available_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Inventory1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Inventory</relationshipLabel>
        <relationshipName>Product_Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>ProductCode__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Locations (Location)</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Inventory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Product_Supplier__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Supplier, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Partial Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Partial Delivery</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Net Buying Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Orderd_Quantity__c</fullName>
        <label>Ordered Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Order Quantity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <label>Remaining Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remaining_to_come__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Received Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order Product</label>
    <nameField>
        <displayFormat>POP-{0000}</displayFormat>
        <label>Purchase Order Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Vendor_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vender_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buying_Price__c</fullName>
        <label>Buying Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Preferred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Preferred Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vendor Products</relationshipLabel>
        <relationshipName>Vendor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Price__c</fullName>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vendor Product</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Vendor Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/ManageInventoryTransactionsTriggerTest.cls
@isTest 
Public class ManageInventoryTransactionsTriggerTest
{
  @IsTest(seeAllData=false)
   public static void methodOne()
  {
        Test.startTest(); 
        
        Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
        Id RID1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        
        Account acc = new Account();
        acc.Name = 'Test';
        acc.RecordTypeId = RID1;
        acc.Email__c='sg@gmail.com';
        insert acc;
        system.assertEquals(acc.Name,'Test');
        
        Default_Parameters__c  dp = new Default_Parameters__c (Name = 'Sample dp',Parent_Id__c = acc.Id,Default_Vendor__c = true,Vendor_Rating__c = true);
        insert dp;
        system.assertEquals(dp.Name,'Sample dp');
        
        Id RID3 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
        Id RID45 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        
        Account acc3 = new Account();
        acc3.Name = 'Test1';
        acc3.RecordTypeId = RID3;
        acc3.Type = 'Location';
        insert acc3;
        system.assertEquals(acc3.Name,'Test1');
        
        Product2 Pro2 = new Product2(Name='Product - 2',SKU__c = 'TP003',Stock_Item__c=true,Reorder_Quantity__c = 50,Quantity__c = 10);
        Insert Pro2;
        system.assertEquals('Product - 2',Pro2.Name);
        
        Account Accs = new Account();
        Accs.Name = 'Test2';
        Accs.RecordTypeId = RID45;
        Accs.Type = 'Vendor';
        Accs.Email__c = 'Test@test.com';
        insert Accs;
        system.assertEquals(Accs.Name,'Test2');
        
        Product2 Pro1 = new Product2(Name='Product - 1',SKU__c = 'TP001',Stock_Item__c=true,Create_AutoPO__c = true,Threshold_Quantity__c = 50);
        Insert Pro1;
        system.assertEquals('Product - 1',Pro1.Name);
        
        
        
        Vendor_Product__c VendProd = new Vendor_Product__c();
        VendProd.Product_Name__c = Pro1.Id;
        VendProd.Account_Name__c = Accs.Id;
        VendProd.Selling_Price__c = 100;
        VendProd.Buying_Price__c = 100;
        VendProd.Is_Preferred__c = true;
        
        insert VendProd;
        system.assertEquals(VendProd.Selling_Price__c,100);
        
        Inventory__c i1 = [select id,Available_Qty__c from Inventory__c where ProductCode__c =: Pro1.Id];
        Inventory_Location__c il = new Inventory_Location__c(Location__c = acc3.Id);
        insert il;
        i1.Available_Qty__c = 50;
        update i1;
        system.assertEquals(il.Location__c,acc3.Id);
        
        
        
        Test.stopTest();
     
   }
   @IsTest(seeAllData=false)
    public static void methodOneTwo()
  {
        Test.startTest(); 
        
        Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
        Id RID1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        
        Account acc = new Account();
        acc.Name = 'Test';
        acc.RecordTypeId = RID1;
        acc.Email__c='gf@gmail.com';
        insert acc;
        system.assertEquals(acc.Name,'Test');
        
        Default_Parameters__c  dp = new Default_Parameters__c (Name = 'Sample dp',Parent_Id__c = acc.Id,Default_Vendor__c = true,Vendor_Rating__c = true);
        insert dp;
        system.assertEquals(dp.Name,'Sample dp');
        
        Id RID3 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
        Id RID45 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        
        Account acc3 = new Account();
        acc3.Name = 'Test1';
        acc3.RecordTypeId = RID3;
        acc3.Type = 'Location';
        insert acc3;
        system.assertEquals(acc3.Name,'Test1');
        
        Product2 Pro2 = new Product2(Name='Product - 2',SKU__c = 'TP003',Stock_Item__c=true,Reorder_Quantity__c = 50,Quantity__c = 10);
        Insert Pro2;
        system.assertEquals('Product - 2',Pro2.Name);
        
        Account Accs = new Account();
        Accs.Name = 'Test2';
        Accs.RecordTypeId = RID45;
        Accs.Type = 'Vendor';
        Accs.Email__c = 'Test@test.com';
        insert Accs;
        system.assertEquals(Accs.Name,'Test2');
        
        Product2 Pro1 = new Product2(Name='Product - 1',SKU__c = 'TP001',Stock_Item__c=true,Create_AutoPO__c = true,Threshold_Quantity__c = 50);
        Insert Pro1;
        system.assertEquals('Product - 1',Pro1.Name);
       
        Vendor_Product__c VendProd = new Vendor_Product__c();
        VendProd.Product_Name__c = Pro1.Id;
        VendProd.Account_Name__c = Accs.Id;
        VendProd.Selling_Price__c = 100;
        VendProd.Buying_Price__c = 100;
        VendProd.Is_Preferred__c = true;
        
        insert VendProd;
        system.assertEquals(VendProd.Selling_Price__c,100);
        
        Purchase_Order__c PO= new Purchase_Order__c();
        PO.Product_Supplier__c = Accs.Id;
        PO.Status__c = 'Open';
        
        insert PO;
        system.assertEquals(PO.Status__c,'Open');
        
        Purchase_Order_Product__c POLine = new Purchase_Order_Product__c();
        POLine.Product__c = Pro1.Id;
        POLine.Purchase_Order__c = PO.Id;
        POLine.Orderd_Quantity__c = 20;
        POLine.Remaining_to_come__c = 10;    
        POLine.Received_Quantity__c = 10;
        POLine.Status__c = 'Partial Delivery';
        
        insert POLine;
        
        system.assertEquals(POLine.Status__c,'Partial Delivery');
        
        Inventory__c i1 = [select id,Available_Qty__c from Inventory__c where ProductCode__c =: Pro1.Id];
        System.debug('i1>> '+i1);
        Inventory_Location__c il = new Inventory_Location__c(Location__c = acc3.Id);
        insert il;
        i1.Available_Qty__c = 50;
        update i1;
        system.assertEquals(il.Location__c,acc3.Id);
        Test.stopTest();
     
   }
  
  
}