SigmaCodebackup3rdSep/objects/Dimension_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit User Details</relationshipLabel>
        <relationshipName>Dimension_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ordered_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Ordered Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sigma_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sigma Order</label>
        <referenceTo>Sigma_Order__c</referenceTo>
        <relationshipLabel>Dimension Tags</relationshipLabel>
        <relationshipName>Dimension_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit User Details</label>
    <nameField>
        <displayFormat>CRD-{0000}</displayFormat>
        <label>Credit User Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dimension Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Inventory (Account)</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Inventory1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Inventory</relationshipLabel>
        <relationshipName>Product_Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Order_Price_Book__c.object
<CustomObject>
    <fields>
        <fullName>Delivary_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <label>Line Item Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Order Confirmed</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Request for cancel</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Packaged</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ordered_Amount__c</fullName>
        <label>Ordered Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Order Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remaining_Qty_To_Package__c</fullName>
        <label>Remaining Qty To Package</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sigma_Order__c</fullName>
        <label>Sigma Order</label>
        <referenceTo>Sigma_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tax_amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>POPB-{0000}</displayFormat>
        <label>Product Order Price Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sigma Orders (AccountId)</relationshipLabel>
        <relationshipName>Sigma_Orders4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>Sigma Orders</relationshipLabel>
        <relationshipName>Sigma_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Customer</fullName>
                </value>
                <value>
                    <fullName>Credit Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivary_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <label>Net Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sigma Orders</relationshipLabel>
        <relationshipName>Sigma_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Created_Via__c</fullName>
        <label>Order Created Via</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Web_Order</fullName>
                    <default>true</default>
                    <label>Web_Order</label>
                </value>
                <value>
                    <fullName>M-POS</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Time Based Inventory</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Service Quote</fullName>
                </value>
                <value>
                    <fullName>Work Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Orders_Status__c</fullName>
        <label>Orders Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Confirmed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sigma Orders</relationshipLabel>
        <relationshipName>Sigma_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShippingCity__c</fullName>
        <label>ShippingCity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingCountry__c</fullName>
        <label>ShippingCountry</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingPostalCode__c</fullName>
        <label>ShippingPostalCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingState__c</fullName>
        <label>ShippingState</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tax(%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Tax__c.object
<CustomObject>
    <description>This is built for Magento Platform integration. Do not delete.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Taxes</relationshipLabel>
        <relationshipName>Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                    <default>true</default>
                    <label>Percentage</label>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/ConvertOpptoSO.cls
global with sharing class ConvertOpptoSO 
{
    @AuraEnabled
    public static Opportunity getOpportunity(Id Proposalid)
    {
     Opportunity campObject ; 
     /*if(CRUD_FLS_CheckUtility.checkObjCRUD('Opportunity') && 
        CRUD_FLS_CheckUtility.checkObjCRUD('OpportunityLineItem') &&
        CRUD_FLS_CheckUtility.checkReadPermission('Opportunity',new set<String>{'id','Name','AccountId','Amount','Account.Name','StageName','Is_Order_Created__c'})  &&
        CRUD_FLS_CheckUtility.checkReadPermission('OpportunityLineItem',new set<String>{'id','Name'})
          ){ */
       
         campObject=[Select Id,Name,AccountId,Amount,Account.Name,StageName,Is_Order_Created__c,(select id,name from OpportunityLineItems) from Opportunity where Id =: Proposalid];
       // }
        return campObject;        
    }  
    
    @AuraEnabled
    webservice static Id saveOrder(Id Orderid)
    {
    Sigma_Order__c orderObj ;
    
    /*if(CRUD_FLS_CheckUtility.checkObjCRUD('Sigma_Order__c') && 
       CRUD_FLS_CheckUtility.checkObjCRUD('Opportunity') &&
       CRUD_FLS_CheckUtility.checkObjCRUD('Account') &&
       CRUD_FLS_CheckUtility.checkObjCRUD('Dimension_Tag__c') &&
       CRUD_FLS_CheckUtility.checkObjCRUD('Product_Order_Price_Book__c') &&
       CRUD_FLS_CheckUtility.checkObjCRUD('Inventory__c')&&
       CRUD_FLS_CheckUtility.checkObjCRUD('OpportunityLineItem')&&
       CRUD_FLS_CheckUtility.checkObjCRUD('Tax__c') &&
       
       CRUD_FLS_CheckUtility.checkReadPermission('Sigma_Order__c',new set<String>{'id','Name','AccountId','Amount','Account.Name','Is_Order_Created__c'})  &&
       CRUD_FLS_CheckUtility.checkReadPermission('Account',new set<String>{'id','Name','Customer_Type__c','Exchange_Currency__c','ShippingStreet','ShippingCity','ShippingState','ShippingPostalcode','ShippingCountry'}) &&
       CRUD_FLS_CheckUtility.checkFLScreateAccess('Sigma_Order__c',new Set<String>{'AccountId__c'}) &&
       CRUD_FLS_CheckUtility.checkReadPermission('OpportunityLineItem',new set<String>{'Id','Product2Id','OpportunityId','Quantity','UnitPrice','TotalPrice','ListPrice'}) &&
       CRUD_FLS_CheckUtility.checkReadPermission('Dimension_Tag__c' ,new set<String>{'id','Ordered_Amount__c','Account__c','AccountId__c'}) &&
       CRUD_FLS_CheckUtility.checkReadPermission('Inventory__c',new set<String>{'id','ProductCode__c','Available_Qty__c'}) &&
       CRUD_FLS_CheckUtility.checkReadPermission('Opportunity',new set<String>{'Id','Name','AccountId','Amount','Account.Name','Is_Order_Created__c'}) &&
    
       CRUD_FLS_CheckUtility.checkFLS('Sigma_Order__c',new set<String>{'Opportunity__c','Net_Amount__c','Order_Created_Via__c','Customer_Type__c','Orders_Status__c','Shipping_Street__c','ShippingCity__c','ShippingState__c','ShippingCountry__c','ShippingPostalCode__c','Currency__c','Delivary_Date__c','Tax_Amount__c','Tax__c','TotalAmount__c'}) &&
       CRUD_FLS_CheckUtility.checkFLS('Dimension_Tag__c',new set<String>{'Ordered_Amount__c'})&&
       CRUD_FLS_CheckUtility.checkFLS('Opportunity',new set<String>{'Is_Order_Created__c'})&&
         
       CRUD_FLS_CheckUtility.checkFLScreateAccess('Product_Order_Price_Book__c',new Set<String>{'Sigma_Order__c'})
    ){ */
    
        Double TaxOnBillAmount = 0;
        
        Account Acc;
        orderObj = new Sigma_Order__c() ;
        Opportunity opp=[Select Id,Name,AccountId,Amount,Account.Name,Is_Order_Created__c from Opportunity where Id =: Orderid];
        Acc=[Select id,name,Customer_Type__c,Exchange_Currency__c,ShippingStreet,ShippingCity,ShippingState,ShippingPostalcode,ShippingCountry from Account where id =:opp.AccountId];
        Id oppid=opp.Id;
        orderObj.Opportunity__c=opp.id;
        orderObj.AccountId__c = opp.AccountId;
        orderObj.Net_Amount__c = opp.Amount;
        orderObj.Order_Created_Via__c='Opportunity';
        orderObj.Customer_Type__c = Acc.Customer_Type__c;
        orderObj.Orders_Status__c = 'Pending';
        if(ACC.ShippingStreet != null)
        orderObj.Shipping_Street__c = ACC.ShippingStreet;
        if(ACC.ShippingCity != null)
        orderObj.ShippingCity__c = ACC.ShippingCity;
        if(ACC.ShippingState != null)
        orderObj.ShippingState__c = ACC.ShippingState ;
        if(ACC.ShippingCountry != null)
        orderObj.ShippingCountry__c = ACC.ShippingCountry;
        if(ACC.ShippingPostalcode != null)
        orderObj.ShippingPostalCode__c = ACC.ShippingPostalcode;
        if(ACC.Exchange_Currency__c != null)
        orderObj.Currency__c = ACC.Exchange_Currency__c;
        orderObj.Delivary_Date__c = System.today();
        List<Tax__c> taxObj = TaxCntr.getTax(opp.AccountId);
        Double federalTax = Double.valueOf(taxObj.get(0).Tax_Amount__c);
        String fedTaxType = String.valueOf(taxObj.get(0).Type__c);
        Double stateTax = Double.valueOf(taxObj.get(1).Tax_Amount__c);
        String stateTaxType = String.valueOf(taxObj.get(1).Type__c);
        if(fedTaxType == 'Percentage'){
        TaxOnBillAmount = (orderObj.Net_Amount__c * federalTax)/100;
        }else{
        TaxOnBillAmount = orderObj.Net_Amount__c + federalTax;
        }               
        if(stateTaxType == 'Percentage'){
        TaxOnBillAmount = (TaxOnBillAmount + (orderObj.Net_Amount__c * stateTax)/100);
        }else{
        TaxOnBillAmount = (TaxOnBillAmount + (orderObj.Net_Amount__c + stateTax));
        }        
        orderObj.Tax_Amount__c = TaxOnBillAmount;   
        orderObj.Tax__c = federalTax+stateTax;
        orderObj.TotalAmount__c = orderObj.Net_Amount__c + TaxOnBillAmount;
        insert orderObj;
  
        if(orderObj.Customer_Type__c=='Credit Customer')
        {
            Dimension_Tag__c creditdetails;
            creditdetails = [select id,Ordered_Amount__c from Dimension_Tag__c where Account__c=:orderObj.AccountId__c limit 1];
            if(creditdetails!=null){
            if(orderObj.TotalAmount__c!=null){
            if(creditdetails.Ordered_Amount__c==null)
            creditdetails.Ordered_Amount__c=0;
            creditdetails.Ordered_Amount__c+=orderObj.TotalAmount__c;
            
        }

        }
        update creditdetails;
        
        }
        
        List<Product_Order_Price_Book__c> OrderLineItems =new List<Product_Order_Price_Book__c>();
        List<OpportunityLineItem> OppLineItems;
        List<Inventory__c> PI = new List<Inventory__c>();
        List<Id>prod = new List<Id>();
        Map<id,Decimal> orderlinepro=new  Map<id,Decimal>();
        decimal netQunt=0;
        decimal totalprice = 0;
        OppLineItems=[Select Id,Product2Id,OpportunityId,Quantity,UnitPrice,TotalPrice,ListPrice from OpportunityLineItem where OpportunityId =:opp.Id];

        for(OpportunityLineItem opplineitem :OppLineItems)  
        {
        prod.add(opplineitem.Product2Id);
        }       
        PI = [Select id,ProductCode__c,Available_Qty__c from Inventory__c where ProductCode__c =:prod];
        for(OpportunityLineItem Oppline:OppLineItems)
        {
            for(Inventory__c proinv : PI)
            {
                if(proinv.ProductCode__c == Oppline.Product2Id)
                {
                    if(Oppline.Quantity > proinv.Available_Qty__c)
                    {
                    decimal remainqunt=Oppline.Quantity - proinv.Available_Qty__c;
                    Product_Order_Price_Book__c orderline = new Product_Order_Price_Book__c(); 
                    orderline.Product__c=Oppline.Product2Id;
                    orderline.Quantity__c=Oppline.Quantity; 
                    orderline.Net_Quantity__c=proinv.Available_Qty__c;
                    orderline.Remaining_Qty_To_Package__c=orderline.Net_Quantity__c;
                    orderline.Sigma_Order__c=orderObj.Id;
                    orderline.Order_Status__c = 'Pending';
                    orderline.Total_Amount__c=Oppline.UnitPrice;
                    orderline.Total_Price__c = orderline.Net_Quantity__c*Oppline.ListPrice;

                    totalprice=orderline.Net_Quantity__c*Oppline.ListPrice;
                    netQunt+=orderline.Net_Quantity__c;
                    OrderLineItems.add(orderline);





                    Product_Order_Price_Book__c orderline1 = new Product_Order_Price_Book__c();
                    orderline1.Net_Quantity__c=remainqunt;
                    orderline1.Remaining_Qty_To_Package__c=orderline1.Net_Quantity__c;
                    orderline1.Product__c=Oppline.Product2Id;
                    orderline1.Total_Price__c=orderline1.Net_Quantity__c*Oppline.ListPrice;
                    orderline1.Sigma_Order__c=orderObj.Id;
                    orderline1.Order_Status__c = 'Pending';
                    orderline1.Total_Amount__c=Oppline.UnitPrice;
                    orderline1.Back_Order__c =true;
                    orderline1.Stock_Fulfilled__c = false;  
                    OrderLineItems.add(orderline1);

                    }
                    else
                    {
                    Product_Order_Price_Book__c orderline2 = new Product_Order_Price_Book__c();
                    orderline2.Product__c=Oppline.Product2Id;
                    orderline2.Quantity__c=Oppline.Quantity;
                    orderline2.Net_Quantity__c=Oppline.Quantity;
                    orderline2.Remaining_Qty_To_Package__c=orderline2.Net_Quantity__c;
                    orderline2.Total_Amount__c=Oppline.UnitPrice;
                    orderline2.Total_Price__c=Oppline.TotalPrice;
                    orderline2.Sigma_Order__c=orderObj.Id;
                    orderline2.Order_Status__c = 'Pending';
                    orderlinepro.put(orderline2.Product__c,orderline2.Quantity__c);
                    netQunt+=orderline2.Quantity__c;
                    OrderLineItems.add(orderline2);  
                    }      
                }
            }


        } 
        upsert OrderLineItems;
        opp.Is_Order_Created__c =true;
        update opp;
       // }
        return orderObj.Id;
}

}