SigmaCodebackup3rdSep/objects/domainURL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To display invoice on Preview Invoice Pop Up.</description>
    <fields>
        <fullName>IframeUrl__c</fullName>
        <label>IframeUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>domainURL</label>
</CustomObject>

SigmaCodebackup3rdSep/classes/CommunityURL.cls
public with sharing class CommunityURL {
@AuraEnabled 
    public static string RetrievecommmunityURL(){
       domainURL__c settings = domainURL__c.getInstance('CommunityURL');
  String UrlValue = settings.IframeUrl__c;
        UrlValue= UrlValue  +'/resource/sigmaerpdev2__lcins1_pdfjs/web/viewer.html';  
  /*List<Domain> DomainURL = [SELECT Domain FROM Domain] ;
       List<Network> URLPrefix = [SELECT UrlPathPrefix FROM Network where name like '%Community%'];
        String UrlValue ;
        if(URLPrefix[0].UrlPathPrefix!= null && URLPrefix[0].UrlPathPrefix !=''){
        UrlValue = DomainURL[0].Domain + URLPrefix[0].UrlPathPrefix;
         UrlValue= 'https://'+UrlValue+'/resource/lcins1_pdfjs/web/viewer.html';
        system.debug('UrlValue : '+ UrlValue);
        } else {
              UrlValue= DomainURL[0].Domain;
        UrlValue= 'https://'+UrlValue  +'/resource/lcins1_pdfjs/web/viewer.html';
        system.debug('UrlValue : '+ UrlValue);                
            }        */
        return UrlValue;        
    }
    
}