SigmaCodebackup3rdSep/objects/Expenditure__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Expenditures</relationshipLabel>
        <relationshipName>Expenditures</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Expenditure__c</fullName>
        <label>Resource Expenditure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Travel_Expenditure__c</fullName>
        <label>Travel Expenditure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Expenditure</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ExpenditureNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenditures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Consumed_Quantity__c</fullName>
        <label>Consumed Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Inventory Consumptions</relationshipLabel>
        <relationshipName>Inventory_Consumptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reserve_Quantity__c</fullName>
        <label>Reserve Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Consumption</label>
    <nameField>
        <displayFormat>IC-{0000}</displayFormat>
        <label>IC-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Consumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Project2__c.object
<CustomObject>
    <fields>
        <fullName>Project2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/updateExpendituretest.cls
@isTest
public class updateExpendituretest {
 @IsTest(seeAllData=false)
  public static void updateExpenditure1()
    {
 Test.startTest();
   
   Project2__c prg=new Project2__c();
   prg.Status__c='Open';
   insert prg; 
   system.assertEquals(prg.Status__c,'Open');
   
    
   Expenditure__c ec=new Expenditure__c ();
    ec.Travel_Expenditure__c=123;
    ec.Resource_Expenditure__c=1345;
    ec.Project__c=prg.id;
    insert ec;
    system.assertEquals(ec.Resource_Expenditure__c,1345);
        
     Inventory_Consumption__c uc=new Inventory_Consumption__c();
    uc.Consumed_Quantity__c=5;
    uc.Reserve_Quantity__c=10;
    uc.Project__c=prg.id;
    insert uc;
    system.assertEquals(uc.Reserve_Quantity__c,10);
    
     
 Test.stopTest();
}
}