SigmaCodebackup3rdSep/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Inventory1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location_Description__c</fullName>
        <label>Location Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Package Location</fullName>
                </value>
                <value>
                    <fullName>Receiving Location</fullName>
                </value>
                <value>
                    <fullName>Waste Management Location</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Location</fullName>
                </value>
                <value>
                    <fullName>Storage Location</fullName>
                </value>
                <value>
                    <fullName>Shipping Location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sub Locations</relationshipLabel>
        <relationshipName>Sub_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product_Transfer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer</label>
        <referenceTo>Product_transfer__c</referenceTo>
        <relationshipName>Product_Transfer_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Request_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Required Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Request Line Item</label>
    <nameField>
        <displayFormat>PRLI-{0000}</displayFormat>
        <label>Product Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Request Line Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Stock__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Inventory(Number of Units)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Stocks</relationshipLabel>
        <relationshipName>Product_Stocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location_Lookup__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Stock</relationshipLabel>
        <relationshipName>Product_Stock</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Minimum_Inventory_Units__c</fullName>
        <formula>Product_Lookup__r.Minimum_Inventory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Minimum Inventory(Number of Units)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Stocks</relationshipLabel>
        <relationshipName>Product_Stocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Stock</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Product Stock Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_transfer__c.object
<CustomObject>
    <fields>
        <fullName>Automatic_Replenishment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automatic Replenishment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductTransferToLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer To Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Transfer To Location</relationshipLabel>
        <relationshipName>Product_Transfer_To_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Transfer_From_location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer From location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Transfer From Location</relationshipLabel>
        <relationshipName>Product_Transfer_From_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Transfer</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Product Transfer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Transfer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/ProductTransferBatch.cls
global with sharing class ProductTransferBatch /*implements 
Database.Batchable<sObject>, Database.Stateful */{
  /*   
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        /*
        //List<Location__c> locations = [SELECT Id, Location_Name__c, Location_Description__c, Location_Type__c, Parent_Location__c FROM Location__c where Location_Type__c = 'Truck'];
        return Database.getQueryLocator(
            'SELECT ID, Location_Name__c,Name,Location_Description__c, Location_Type__c,Parent_Location__c  ' +
            'FROM Location__c ' + 
            'Where Location_Type__c = \'Truck\'' 
        );
    }
    global void execute(Database.BatchableContext bc, List<Location__c> locationList){
        // process each batch of records
        
        /*List<Product_Stock__c> productStock = [SELECT Id, Name, Location_Lookup__c, Product_Lookup__c, Inventory__c, Minimum_Inventory_Units__c FROM Product_Stock__c];
        Map<String,List<Product_Stock__c>> locProductStck = new Map<String,List<Product_Stock__c>>();
        
        //Defining Map with Key as Location Name and its value as ProductStock at its Location.
        for(Location__c location : locationList){
            List<Product_Stock__c> tempPS = new List<Product_Stock__c>();
            for(Product_Stock__c eachProductStock : productStock){
                if(location.Id == eachProductStock.Location_Lookup__c){
                    tempPS.add(eachProductStock);
                }
            }
            if(tempPS.size()!=0){
                locProductStck.put(location.Name,tempPS);
            }
        }
        
    List<Product2> products = [SELECT Id, Name, Minimum_Inventory__c, Maximum_Inventory__c, Replinishment_Stock__c FROM Product2];        
        
        //Creating a ProductTransfer Based on the Minimum Inventory of Products at every Location.
        for(String key : locProductStck.keySet()){
            
            for(Location__c eachLocation : locationList){
                if(key == eachLocation.Name){
                    
                    //Fetching the Product Stock Detials of the Location as per the current Iteration's Location.
                    List<Product_Stock__c> temp = locProductStck.get(key);
                    
                    //Creating a product Transfer.
                    Product_transfer__c productTransfer = new Product_transfer__c();
                    productTransfer.Product_Transfer_From_location__c = eachLocation.Parent_Location__c;
                    productTransfer.ProductTransferToLocation__c = eachLocation.Id;
                    productTransfer.Automatic_Replenishment__c = True;
                    insert productTransfer;
                    
                    //creating ProductLineItems as per the Inventory of Products and the Inventory at the Location.
                    list<Product_Request_Line_Item__c> listPRLI = new list<Product_Request_Line_Item__c>();
                    for(Product_Stock__c eachProductStck : temp){
                        for(Product2 eachProduct : products){
                            if(eachProduct.Id == eachProductStck.Product_Lookup__c){
                                Product_Request_Line_Item__c productRequestLineItem = new Product_Request_Line_Item__c();
                            productRequestLineItem.Product__c = eachProductStck.Product_Lookup__c;
                                productRequestLineItem.Product_Transfer__c = productTransfer.Id;
                                if(eachProductStck.Inventory__c < eachProduct.Minimum_Inventory__c){
                                    
                                    //The Quantity of PRLI of every product should not cross its Product's Max Inventory.
                                    if((eachProductStck.Inventory__c+eachProduct.Replinishment_Stock__c)>eachProduct.Maximum_Inventory__c){
                                        productRequestLineItem.Quantity__c = eachProduct.Maximum_Inventory__c;
                                    }
                                    else{
                                        productRequestLineItem.Quantity__c = eachProduct.Replinishment_Stock__c;
                                    }
                                   listPRLI.add(productRequestLineItem); 
                                }
                            }
                        } 
                    }
                    if(listPRLI.size()!=0){
                        insert listPRLI;
                    }
                }
                
            }
        } 
    }
    global void finish(Database.BatchableContext bc){
    }  */ 
}