SigmaCodebackup3rdSep/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Package_Product_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Package Product Line Items</relationshipLabel>
        <relationshipName>Package_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packaged_Product__c</fullName>
        <label>Packaged Product</label>
        <referenceTo>PackagedProducts__c</referenceTo>
        <relationshipLabel>Package Product Line Items</relationshipLabel>
        <relationshipName>Package_Product_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Package Product Line Item</label>
    <nameField>
        <displayFormat>PPLI-{0000}</displayFormat>
        <label>Package Product Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Product Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/PackagedProducts__c.object
<CustomObject>
    <fields>
        <fullName>Auto_allocate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto allocate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PackagedProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Consumed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Packaged Product</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Packaged Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packaged Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Price__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Prices (Location)</relationshipLabel>
        <relationshipName>Product_Prices2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Price</label>
    <nameField>
        <label>Product Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sales_Order_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Order Confirmed</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Ready To Ship</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Allocation</label>
    <nameField>
        <displayFormat>SOA-{0}</displayFormat>
        <label>Sales Order Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sales_Order_Allocation_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order_Allocation__c</fullName>
        <label>Sales Order Allocation</label>
        <referenceTo>Sales_Order_Allocation__c</referenceTo>
        <relationshipLabel>Sales Order Allocation Line Items</relationshipLabel>
        <relationshipName>Sales_Order_Allocation_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Ready To Ship</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Order Confirmed</fullName>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Allocation Line Item</label>
    <nameField>
        <displayFormat>SOALI-{0}</displayFormat>
        <label>Sales Order Allocation Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Allocation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Truck_No__c</fullName>
        <label>Truck No</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Shipment_Products__c.object
<CustomObject>
    <fields>
        <fullName>Orderd_Quantity__c</fullName>
        <label>Orderd Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Products</relationshipLabel>
        <relationshipName>Shipment_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Product</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Shipment Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Stock_Adjustment_Product__c.object
<CustomObject>
    <fields>
        <fullName>Adjusted_Quantity__c</fullName>
        <label>Adjusted Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Adjustment__c</fullName>
        <label>Stock Adjustment</label>
        <referenceTo>StockAdjustment__c</referenceTo>
        <relationshipLabel>Stock Adjustment Products</relationshipLabel>
        <relationshipName>Stock_Adjustment_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stock Adjustment Product</label>
    <nameField>
        <displayFormat>SAP-{00000}</displayFormat>
        <label>Stock Adjustment Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Adjustment Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Stock_Moment_Product__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity Received</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor_Email__c</fullName>
        <label>Vendor Email</label>
        <type>Email</type>
    </fields>
    <label>Stock Movement Product</label>
    <nameField>
        <label>Stock Movement Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Movement Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/StockAdjustment__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Stock Adjustments</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Stock Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Vendor_Product__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vendor Product</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Vendor Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/TestLinkerPPLI.cls
@isTest
public  class TestLinkerPPLI {
    
     @isTest static void TestPPLI() {
          Test.startTest();
         PackagedProducts__c pack = new PackagedProducts__c();
         pack.Auto_allocate__c = false;
         pack.Quantity__c = 10;
         insert pack;
         system.assertEquals(pack.Quantity__c ,10);

        Package_Product_Line_Item__c  pp = new Package_Product_Line_Item__c();
        pp.Packaged_Product__c= pack.id;
        insert pp;
        system.assertEquals(pp.Packaged_Product__c,pack.id);
        
        StockAdjustment__c SA = new StockAdjustment__c();
        SA.Comments__c='hii';
        SA.Quantity__c = 10;
        insert SA;
        system.assertEquals(SA.Quantity__c , 10);
        
        Stock_Adjustment_Product__c SAP = new Stock_Adjustment_Product__c();
        SAP.Stock_Adjustment__c = SA.id;
        SAP.Adjusted_Quantity__c =5;
        insert SAP; 
        system.assertEquals(SAP.Adjusted_Quantity__c ,5);

        Shipment__c Ship = new Shipment__c();
        Ship.Truck_No__c = '123';
        insert Ship;
        system.assertEquals(Ship.Truck_No__c ,'123');

        
        Shipment_Products__c Shipproduct = new Shipment_Products__c();
        Shipproduct.Shipment__c=Ship.id;
        Shipproduct.Orderd_Quantity__c  =10;
        insert Shipproduct;
        system.assertEquals(Shipproduct.Orderd_Quantity__c ,10);
        
        Stock_Moment_Product__c SM = new Stock_Moment_Product__c();
        SM.Quantity__c = 10;
        SM.Vendor_Email__c = 'haris@gmail.com';
        insert SM;
        system.assertEquals(SM.Vendor_Email__c ,'haris@gmail.com');
        
        Sales_Order_Allocation__c SOA = new Sales_Order_Allocation__c();
        SOA.Status__c= 'Order Confirmed';
        insert SOA;
        system.assertEquals(SOA.Status__c,'Order Confirmed');
        
        Sales_Order_Allocation_Line_Item__c SOAL = new Sales_Order_Allocation_Line_Item__c();
        SOAL.Sales_Order_Allocation__c = SOA.id;
        insert SOAL;
        system.assertEquals( SOAL.Sales_Order_Allocation__c ,SOA.id);
        
         //defualt parameter
         Default_Parameters__c DP = new Default_Parameters__c();
         DP.Name='defualt';
         DP.Inventory_Status__c='Reserve';
         DP.Auto_Reserve_Stock__c=true;
         insert DP;
         System.assertEquals( DP.Auto_Reserve_Stock__c,true);
        
        Account accloc = new Account();
        accloc.name='bagalore';
        accloc.Type = 'Location';
        accloc.Email__c='abc@gmail.com';
        insert accloc;
         Account accvendor = new Account();
        accvendor.name='bagaloreVendor';
        accvendor.Type = 'Vendor';
        accvendor.Email__c='abx@gmail.com';
        insert accvendor;
        system.assertEquals(accvendor.Type , 'Vendor');
        
        Id RIDBOM = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('BOM').getRecordTypeId();
        Product2 prod= new Product2();
        prod.Name='test';
        prod.Product_Description__c='test description';
        prod.Product_Price__c=100;
        prod.Buying_Price__c=20;
        prod.Max_Discount__c=30;
        prod.Product_Weight__c = 3 ;
        prod.SKU__c = 'testing';
        prod.Type__c = 'BOM';
        prod.RecordtypeId = RIDBOM;
        insert prod;
        System.assertEquals(prod.name, 'test');
        
        //Product Inventory
        Inventory__c PI = new Inventory__c();
        PI.ProductCode__c=prod.id;
        PI.Available_Qty__c = 10;
        insert PI;
        System.assertEquals(PI.Available_Qty__c,10);
        
        
        
        Product_Price__c PP1 = new Product_Price__c();
        PP1.Status__c= 'Active';
        PP1.Cost__c = 10;
        PP1.End_Date__c = system.today()+5;
        PP1.Location__c = accloc.id;
        PP1.Product_Id__c = prod.id;
        PP1.Start_Date__c = system.today();
        insert PP1;
        system.assertEquals(PP1.Location__c , accloc.id);
        
        Vendor_Evaluation__c  VE = new Vendor_Evaluation__c ();
        VE.Order_Quantity__c= 10;
        insert VE;
        system.assertEquals(VE.Order_Quantity__c,10);
        
        Inventory__c Inventory = new Inventory__c();
        Inventory.Total_Qty__c=10;
        insert Inventory;
        system.assertEquals(Inventory.Total_Qty__c,10);
        
         Vendor_Product__c vp2=   new Vendor_Product__c();
       vp2.Account_Name__c = accvendor .id;
      vp2.Product_Name__c = prod.id;
        vp2.Buying_Price__c = 100;
        vp2.Discount__c = 10;
        vp2.Quantity__c = 1;
        vp2.Is_Preferred__c=true;
        insert vp2;
        system.assertEquals(vp2.Quantity__c , 1);
        
        Test.stopTest();
        
        
     }
}