SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Locations (Location)</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/TestDeleteLocations.cls
@isTest
public class TestDeleteLocations {

    @isTest(SeeAllData=false)
    public static void test(){        
      Test.startTest();
    Account a1=new Account();
    a1.Name='abc';
    Id stExam = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
    a1.Email__c='abc@gmail.com';
    a1.NumberofLocations__c=2;
    insert a1;
    system.assertEquals(a1.NumberofLocations__c,2);
    
    Account a=new Account();
    a.Name='Harish';
    //a.Location__c = a1.id;
    a.NumberofLocations__c=2;
    a.RecordtypeId=stExam;
    insert a;
    system.assertEquals(a.Name,'Harish');
    
    Inventory_Location__c il=new Inventory_Location__c();
    il.Location__c=a.Id;
    il.Available_Quantity__c=1;
    insert il;
    system.assertEquals(il.Available_Quantity__c,1);
    delete il;
    
  
     
    Test.stopTest();    
}
}