SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Locations (Location)</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Location_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location Product</label>
        <referenceTo>Inventory_Location_Product__c</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturing Run</label>
        <referenceTo>Manufacturing_Run__c</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Serial_Number_Code__c</fullName>
        <formula>Product_Serial_Number__r.Serial_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number Code</label>
        <type>Text</type>
    </fields>
    <label>Inventory Location Product Line Item</label>
    <nameField>
        <displayFormat>ILPLI-{0}</displayFormat>
        <label>Inventory Location Product LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Product Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Lot__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Lots</relationshipLabel>
        <relationshipName>Lots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lot</label>
    <nameField>
        <displayFormat>LT-{0000}</displayFormat>
        <label>Lot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Manufacturing_Run__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Manufacturing Run</relationshipLabel>
        <relationshipName>Manufacturing_Run</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Name__c</fullName>
        <label>Manufacturing Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturing Run</label>
        <referenceTo>Manufacturing_Run__c</referenceTo>
        <relationshipLabel>Manufacturing Run</relationshipLabel>
        <relationshipName>Manufacturing_Run</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Manufacturing Run</relationshipLabel>
        <relationshipName>Manufacturing_Run</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Manufacturing Run</relationshipLabel>
        <relationshipName>Manufacturing_Run</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Quantity__c</fullName>
        <label>Required Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Run_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Manufacturing Run</label>
    <nameField>
        <displayFormat>Rec-{0000}</displayFormat>
        <label>Manufacturing Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manufacturing Run</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Manufacturing_Run_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Manufacturing_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturing Run</label>
        <referenceTo>Manufacturing_Run__c</referenceTo>
        <relationshipLabel>Manufacturing Run Allocations</relationshipLabel>
        <relationshipName>Manufacturing_Run_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Manufacturing Run Allocations</relationshipLabel>
        <relationshipName>Manufacturing_Run_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Manufacturing Run Allocation</label>
    <nameField>
        <displayFormat>MRA-{0000}</displayFormat>
        <label>Manufacturing Run Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manufacturing Run Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Manufacturing_Run_Allocation_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Location_Product_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location Product Line Item</label>
        <referenceTo>Inventory_Location_Product_Line_Item__c</referenceTo>
        <relationshipLabel>Manufacturing Run Allocation Line Items</relationshipLabel>
        <relationshipName>Manufacturing_Run_Allocation_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Location_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location Product</label>
        <referenceTo>Inventory_Location_Product__c</referenceTo>
        <relationshipLabel>Manufacturing Run Allocation Line Items</relationshipLabel>
        <relationshipName>Manufacturing_Run_Allocation_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Manufacturing Run Allocation Line Items</relationshipLabel>
        <relationshipName>Manufacturing_Run_Allocation_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Run_Allocation__c</fullName>
        <label>Manufacturing Run Allocation</label>
        <referenceTo>Manufacturing_Run_Allocation__c</referenceTo>
        <relationshipLabel>Manufacturing Run Allocation Line Items</relationshipLabel>
        <relationshipName>Manufacturing_Run_Allocation_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Manufacturing Run Allocation Line Item</label>
    <nameField>
        <displayFormat>MRALI-{0000}</displayFormat>
        <label>Manufacturing Run Allocation Line Items</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manufacturing Run Allocation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Recipe__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sublevel_location__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Sublevel-locations</relationshipLabel>
        <relationshipName>Sublevel_locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sublevel-locations</relationshipLabel>
        <relationshipName>Sublevel_locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sublevel-location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sublevel-locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/BSSPickDocument.cls
public with sharing class BSSPickDocument{
    List<BSSPickDocument.listOfProductsWrapper> container;
    Manufacturing_Run__c headerDetailsList; 
    public BSSPickDocument() {        
        String manfId = ApexPages.currentPage().getParameters().get('manfId');      
        headerDetailsList = [select Manufacturing_Name__c,Run_Date__c,Recipe__r.Name,Required_Quantity__c,Recipe__c from Manufacturing_Run__c where id = :manfId];
        Recipe__c recpObj = [select Quantity__c from Recipe__c where Id = :headerDetailsList.Recipe__c];
        headerDetailsList.Required_Quantity__c = (headerDetailsList.Required_Quantity__c * recpObj.Quantity__c).setScale(2);
        //fetch all the reserved stock to show in pdf
        List<listOfProductsWrapper> wrapProdListOuter = new List<listOfProductsWrapper>();  
        Map<Id,Decimal> prodMap = new Map<Id,Decimal>();
        Set<Id> manfRunAllocIds = new Set<Id>();
        List<ProductWrapper> wrapProdListManual = new List<ProductWrapper>(); //list of indiv. Products and its ilpli list
        Id ProdId;
        String prodName; 
        String status;
        String prodAttrType;
        String prodBomType; 
        String productUOM;
        Decimal totalAvailableQty; 
        
        List<Manufacturing_Run_Allocation__c> mraList = new List<Manufacturing_Run_Allocation__c>();
        mraList = [select id,name,Product__c,Product__r.Name,Quantity__c
                   from Manufacturing_Run_Allocation__c where Manufacturing_Run__c = : manfId];      
        for(Manufacturing_Run_Allocation__c mraItr : mraList){
            prodMap.put(mraItr.Product__c, mraItr.Quantity__c);
            manfRunAllocIds.add(mraItr.Id);
        }
        
        List<Manufacturing_Run_Allocation_Line_Items__c> mraLineItemsList = new List<Manufacturing_Run_Allocation_Line_Items__c>();
        mraLineItemsList = [select id,name,Inventory_Location_Product__c,Inventory_Location_Product_Line_Item__c,                                                                                    
                            Inventory_Location_Product_Line_Item__r.Serial_Number_Code__c,                           
                            Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Inventory_Location__r.name,
                            Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Name,                            
                            Inventory_Location_Product_Line_Item__r.Name,                            
                            Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Products__c,Location__c,Unit_Price__c,
                            Inventory_Location_Product_Line_Item__r.Bin__r.Name,
                            Inventory_Location_Product_Line_Item__r.Bin__r.Zone__r.Name,
                            Lot__c,Quantity__c from Manufacturing_Run_Allocation_Line_Items__c
                            where Manufacturing_Run_Allocation__c In : manfRunAllocIds];
        
        for(Product2 prd :[select id,name,Attribute_Type__c,Product_UOM__c from Product2 where id in : prodMap.keySet()]){
            List<innerWrapper> wrapProdListSelected = new List<innerWrapper>();
            ProdId = prd.id;
            prodName = prd.name;
            prodAttrType = prd.Attribute_Type__c;            
            totalAvailableQty = 0.0;
            if(prd.Product_UOM__c != null){
                productUOM = prd.Product_UOM__c;
            }
            for(Manufacturing_Run_Allocation_Line_Items__c mraliIteration : mraLineItemsList){
                if(mraliIteration.Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Products__c == ProdId){
                    innerWrapper iwrap = new innerWrapper(null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);                                                            
                    if(mraliIteration.Inventory_Location_Product_Line_Item__r.Bin__r.Name == null)
                        iwrap.lotName = 'NA';
                    else
                        iwrap.lotName = mraliIteration.Inventory_Location_Product_Line_Item__r.Bin__r.Name;                    
                    
                    if(mraliIteration.Inventory_Location_Product_Line_Item__r.Bin__r.Zone__r.Name == null)
                        iwrap.zoneName = 'NA';
                    else
                        iwrap.zoneName = mraliIteration.Inventory_Location_Product_Line_Item__r.Bin__r.Zone__r.Name;                                        
                                       
                    iwrap.ilpAvailQuantity = null;                                         
                    if(mraliIteration.Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Inventory_Location__r.name == null)
                        iwrap.ilName = 'NA';
                    else
                        iwrap.ilName = mraliIteration.Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Inventory_Location__r.name;                                         
                    
                    if(mraliIteration.Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Name == null)
                        iwrap.ilpName = 'NA';
                    else
                        iwrap.ilpName = mraliIteration.Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Name;                  
                                        
                    iwrap.ilpliName = mraliIteration.Inventory_Location_Product_Line_Item__r.Name;                    
                    iwrap.ilpId = mraliIteration.Inventory_Location_Product_Line_Item__r.Inventory_Location_Product__r.Id; 
                    iwrap.ilpliId = mraliIteration.Inventory_Location_Product_Line_Item__c;                                   
                    iwrap.srNumName = mraliIteration.Inventory_Location_Product_Line_Item__r.Serial_Number_Code__c;                    
                    
                    iwrap.selQuantity = mraliIteration.Quantity__c;                                        
                    iwrap.unitPrice = mraliIteration.Unit_Price__c;
                    iwrap.ppId = null;
                    iwrap.ppliId = null;                    
                    iwrap.prodUOM = null;
                    iwrap.prodExpDate = null;                    
                    wrapProdListSelected.add(iwrap);
                }
            }
            wrapProdListManual.add(new ProductWrapper(ProdId,prodName,prodMap.get(prd.id),prodAttrType,prodBomType,wrapProdListSelected,productUOM,null,true,totalAvailableQty,null));               
        }   
        wrapProdListOuter.add(new listOfProductsWrapper(wrapProdListManual));
        container = wrapProdListOuter;                                                      
    }
    
    public List<BSSPickDocument.listOfProductsWrapper> getcontainer(){
        return container;
    }    
    
    public Manufacturing_Run__c getheaderDetailsList(){
        return headerDetailsList;
    }
    
    public class listOfProductsWrapper{
        @AuraEnabled
        public List<ProductWrapper> mainWrapProdList{get;set;}
        public listOfProductsWrapper(List<ProductWrapper> mainWrapProdList){
            this.mainWrapProdList = mainWrapProdList;
        }
    }
    
    //Wrapper class to store Product Details
    public class ProductWrapper {       
        @AuraEnabled            
        public Id prodId {get;set;}
        @AuraEnabled            
        public String prodName {get;set;}
        @AuraEnabled          
        public Decimal requiredQnt{get;set;}           
        @AuraEnabled
        public String prodAttributeType{get;set;}                         
        @AuraEnabled
        public String prodBomType{get;set;}
        @AuraEnabled
        public List<innerWrapper> wrapProdList{get;set;}
        @AuraEnabled
        public String prodUOM{get;set;}        
        @AuraEnabled            
        public Id manufRunId {get;set;}
        @AuraEnabled
        public Boolean allocatedViaAutopickOrManual{get;set;}
        @AuraEnabled
        public Decimal totalAvailQty{get;set;}
        @AuraEnabled
        public Decimal avgUnitPrice{get;set;}
        public ProductWrapper(Id ProdId, String ProdName, Decimal requiredQnt,String prodAttributeType,String pBom,List<innerWrapper> wrapProdList,String prodUOM,Id manufRunId,Boolean allocatedViaAutopickOrManual, Decimal totalAvailQty, Decimal avgUnitPrice) {                           
            this.prodId = prodId;
            this.ProdName = ProdName;
            this.requiredQnt = requiredQnt;            
            this.prodAttributeType = prodAttributeType;
            this.prodBomType = pBom;
            this.wrapProdList = wrapProdList;       
            this.prodUOM = prodUOM;                     
            this.manufRunId = manufRunId;
            this.allocatedViaAutopickOrManual = allocatedViaAutopickOrManual; 
            this.totalAvailQty = totalAvailQty;
            this.avgUnitPrice = avgUnitPrice;
        }       
    }
    
    //Wrapper class to store ILPLI Details
    public class innerWrapper { 
        @AuraEnabled
        public Decimal selQuantity{get;set;}
        @AuraEnabled         
        public Id srNumId {get; set;}
        @AuraEnabled         
        public String srNumName {get; set;}
        @AuraEnabled        
        public String lotName {get;set;}
        @AuraEnabled        
        public Date lotExpiryDate {get;set;}
        @AuraEnabled        
        public String ilpName {get;set;}
        @AuraEnabled
        public Decimal ilpAvailQuantity {get;set;}
        @AuraEnabled
        public Id lotId {get;set;}
        @AuraEnabled
        public Id ilpId {get;set;}
        @AuraEnabled
        public Id ilpliId {get;set;}
        @AuraEnabled
        public Id locationId {get;set;}
        @AuraEnabled
        public Id ppId {get;set;}
        @AuraEnabled
        public Id ppliId {get;set;}
        @AuraEnabled
        public String prodUOM{get;set;}
        @AuraEnabled
        public Date prodExpDate{get;set;}
        @AuraEnabled
        public ID recordID{get;set;}  
        @AuraEnabled        
        public String ilpliName {get;set;}
        @AuraEnabled        
        public String ilName {get;set;}
        @AuraEnabled        
        public Decimal unitPrice {get;set;}
        
        @AuraEnabled        
        public String zoneName {get;set;}
                
        public innerWrapper(Decimal selQn,Id srNumId, String ltName, Date ltExpiryDate, String ilpName, Decimal avlQn, Id lotId, Id ilpId, Id ilpliId, Id locationId, String srNumName, Id ppId, Id ppliId, String prodUOM,Date prodExpDate,ID recID,String ilpliName, String ilName, Decimal unitPrice, String zoneName) {
            this.selQuantity = selQn;
            this.srNumId = srNumId;          
            this.lotName = ltName;
            this.lotExpiryDate = ltExpiryDate;
            this.ilpName = ilpName;
            this.ilpAvailQuantity = avlQn;   
            this.lotId = lotId; 
            this.ilpId = ilpId;
            this.ilpliId = ilpliId;         
            this.locationId = locationId;
            this.srNumName = srNumName;
            this.ppId = ppId;
            this.ppliId = ppliId;
            this.prodUOM = prodUOM;
            this.prodExpDate = prodExpDate;
            this.recordID=recID;
            this.ilpliName = ilpliName;
            this.ilName = ilName;
            this.unitPrice = unitPrice;
            this.zoneName = zoneName;
        }
    }   
    
}