SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/DuplicateILP.cls
public with sharing class DuplicateILP
{
  public void CheckILP(List<Inventory_Location_Product__c> ILPData)
  {
	set<Id>ILIds = new set<Id>();
	set<Id>ProIds = new set<Id>();
	for(Inventory_Location_Product__c ILP:ILPData)
	{
		ILIds.add(ILP.Inventory_Location__c);
		ProIds.add(ILP.Products__c);
	}
	
	if(ILIds.size()>0 && ProIds.size()>0 )
	{
		List<Inventory_Location_Product__c>ILPRecord = [Select Id,Inventory_Location__c,Products__c from Inventory_Location_Product__c where Inventory_Location__c=:ILIds and Products__c =:ProIds];
		if(ILPRecord.size()>0)
		{
			ILPData[0].addError('Inventory Location already exist');
		}
	}
	
	
  }

}