SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Locations (Location)</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Delivered_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sold Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <formula>(Received_Quantity__c + Increased_Adjusted_Quantity__c +AdjustedReceivedqty__c  +  Rental_Adjustment_Quantity__c ) - (Delivered_Quantity__c + Rental_Delivered_Quantity__c + AvailableAdjustedQty__c+ Reduced_Adjusted_Quantity__c +Reserved_Quantity__c + Deliver_Quantity__c+Picked_Quantity__c+Package_Quantity__c+Shipped_Quantity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Received Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/OrderLineLocation__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inventory_Allocated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inventory Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inventory_Location_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location Product</label>
        <referenceTo>Inventory_Location_Product__c</referenceTo>
        <relationshipLabel>OrderLineItemLocations</relationshipLabel>
        <relationshipName>OrderLineItemLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OrderLineItemLocations</relationshipLabel>
        <relationshipName>OrderLineItemLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Line__c</fullName>
        <label>Order Line</label>
        <referenceTo>Product_Order_Price_Book__c</referenceTo>
        <relationshipLabel>OrderLineItemLocations</relationshipLabel>
        <relationshipName>OrderLineItemLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>OrderLineItemLocations</relationshipLabel>
        <relationshipName>OrderLineItemLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>OrderLineItemLocation</label>
    <nameField>
        <displayFormat>OLL-{0000}</displayFormat>
        <label>OrderLineLocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItemLocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Order_Price_Book__c.object
<CustomObject>
    <fields>
        <fullName>Delivered_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Delivered Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsInventoryUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stock Allocated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Lines (Location)</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <label>Line Item Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Order Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sigma_Order__c</fullName>
        <label>Sigma Order</label>
        <referenceTo>Sigma_Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>POPB-{0000}</displayFormat>
        <label>Product Order Price Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <label>Net Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sigma Orders</relationshipLabel>
        <relationshipName>Sigma_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/AllocateInventoryCntrl1.cls
public with sharing class AllocateInventoryCntrl1 
{

public static boolean DeAllocateInventoryforOrder()
    {
        List<Id> productId = new List<Id>();
        List<Id> ProposalItemId = new List<Id>();
        List<Id> locationIdList = new List<Id>();
        List<Product_Order_Price_Book__c> orderItemList = new List<Product_Order_Price_Book__c>();
        List<Product_Order_Price_Book__c> LineItemList;
       
     /*   if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Product_Order_Price_Book__c')
        && CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__OrderLineLocation__c')
        && CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Inventory_Location_Product__c')
        && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Product_Order_Price_Book__c',new set<String>{'id','Name','sigmaerpdev2__Product__c','sigmaerpdev2__Start_Date__c','sigmaerpdev2__End_Date__c','sigmaerpdev2__Sigma_Order__c'})
        && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__OrderLineLocation__c',new set<String>{'id','sigmaerpdev2__Location__c','sigmaerpdev2__Order_Line__c','sigmaerpdev2__Inventory_Allocated__c'})
        && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Inventory_Location_Product__c',new set<String>{'id','sigmaerpdev2__Products__c','sigmaerpdev2__Inventory_Location__r.sigmaerpdev2__Location__c','sigmaerpdev2__Delivered_Quantity__c','sigmaerpdev2__Received_Quantity__c','sigmaerpdev2__Net_Quantity__c','sigmaerpdev2__End_Date__c','sigmaerpdev2__Start_Date__c'})
        && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Product_Order_Price_Book__c',new set<String>{'id','sigmaerpdev2__Product__c','sigmaerpdev2__Start_Date__c','sigmaerpdev2__End_Date__c'})
        && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__OrderLineLocation__c',new set<String>{'id','sigmaerpdev2__Location__c','sigmaerpdev2__Quantity__c'})
        && CRUD_FLS_CheckUtility.checkFLS('sigmaerpdev2__Inventory_Location_Product__c',new set<String>{'sigmaerpdev2__Delivered_Quantity__c'})
        && CRUD_FLS_CheckUtility.checkFLS('sigmaerpdev2__OrderLineLocation__c',new set<String>{'sigmaerpdev2__Inventory_Allocated__c'})
        )
        { */
           
            LineItemList = [select id, Name, Product__c, Start_Date__c, End_Date__c,Sigma_Order__c from Product_Order_Price_Book__c where sigmaerpdev2__Sigma_Order__r.sigmaerpdev2__Order_Created_Via__c='Time Based Inventory' and IsInventoryUpdated__c = true and End_Date__c =: system.today()];
        for(Product_Order_Price_Book__c pi : LineItemList)
        {
            productId.add(pi.Product__c);
            ProposalItemId.add(pi.Id);
        }
        List<OrderLineLocation__c> toGetLocList = [select id, Location__c, Order_Line__c,Inventory_Allocated__c from OrderLineLocation__c where ((Order_Line__c In : ProposalItemId) AND (Inventory_Allocated__c = true))];
        for(OrderLineLocation__c clil : toGetLocList)
        {
            locationIdList.add(clil.Location__c);
        }
        
        List<Inventory_Location_Product__c> ilpList = [select id, Products__c, Inventory_Location__r.Location__c, Delivered_Quantity__c, Received_Quantity__c, Net_Quantity__c, End_Date__c, Start_Date__c from Inventory_Location_Product__c where ((Inventory_Location__r.Location__c In: locationIdList) And (Products__c In: productId ))];
        
        orderItemList = [select id, Product__c, Start_Date__c, End_Date__c, (select id, Location__c, Quantity__c from OrderLineItemLocations__r where Inventory_Allocated__c = true) from Product_Order_Price_Book__c where id In: ProposalItemId];
        
        Map<Id, List<WrapperForIlpAndQuantity>> invenAllocation = new Map<Id, List<WrapperForIlpAndQuantity>>();
        for(Product_Order_Price_Book__c pItem : orderItemList)
        {
            //to get start and end date
            Date firstDayOfMonth = (pItem.Start_Date__c).toStartOfMonth();
            Date getLastMonthDate = (pItem.End_Date__c);
            Integer dayNumbers = Date.daysInMonth((getLastMonthDate).year(), (getLastMonthDate).month());
            Date lastDayOfMonth = Date.newInstance(getLastMonthDate.year(), getLastMonthDate.month(), dayNumbers);
            
            for(OrderLineLocation__c cil : pItem.OrderLineItemLocations__r)
            {
                for(Inventory_Location_Product__c ilp : ilpList)
                {
                    if((ilp.Products__c == pItem.Product__c) && (cil.Location__c == ilp.Inventory_Location__r.Location__c) && (ilp.Start_Date__c >= firstDayOfMonth) && (ilp.End_Date__c <= lastDayOfMonth))
                    {
                        if(invenAllocation.containsKey(pItem.Product__c))
                        {
                            invenAllocation.get(pItem.Product__c).add(new WrapperForIlpAndQuantity(ilp, Integer.valueOf(cil.Quantity__c)));
                        }
                        else
                        {
                            List<WrapperForIlpAndQuantity> WrapList = new List<WrapperForIlpAndQuantity>();
                            WrapList.add(new WrapperForIlpAndQuantity(ilp, Integer.valueOf(cil.Quantity__c)));
                            invenAllocation.put((pItem.Product__c),WrapList);
                        }
                    }
                }
            }
        }
        
        List<Inventory_Location_Product__c> ilpListToUpdate = new List<Inventory_Location_Product__c>();
        for(Id proId : invenAllocation.keySet())
        {
            List<WrapperForIlpAndQuantity> ilpQuantityList = invenAllocation.get(proId);
            for(WrapperForIlpAndQuantity wiaq : ilpQuantityList)
            {
                Inventory_Location_Product__c ilp = wiaq.ilpRecord;
                ilp.Delivered_Quantity__c = ilp.Delivered_Quantity__c - wiaq.quantity;
                ilpListToUpdate.add(ilp);
            }
        }
        update ilpListToUpdate;
        
        for(OrderLineLocation__c clil : toGetLocList)
        {
            clil.Inventory_Allocated__c = false;
        }
        update toGetLocList;
        
       // }
        
        return true;
    }
    
    public class WrapperForIlpAndQuantity
    {
        Inventory_Location_Product__c ilpRecord;
        integer quantity;
        public WrapperForIlpAndQuantity(Inventory_Location_Product__c ilpRecord, integer quantity)
        { 
       
            this.ilpRecord = ilpRecord;
            this.quantity = quantity;
        
        }
    }
    
}