SigmaCodebackup3rdSep/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Available_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Delivered_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Delivered Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Inventory1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>ProductCode__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reserved_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reserved Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipped_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Shipped Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Locations (Location)</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Inventory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivered_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sold Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory_Location_Name__c</fullName>
        <formula>Inventory_Location__r.Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <formula>(Received_Quantity__c + Increased_Adjusted_Quantity__c +AdjustedReceivedqty__c  +  Rental_Adjustment_Quantity__c ) - (Delivered_Quantity__c + Rental_Delivered_Quantity__c + AvailableAdjustedQty__c+ Reduced_Adjusted_Quantity__c +Reserved_Quantity__c + Deliver_Quantity__c+Picked_Quantity__c+Package_Quantity__c+Shipped_Quantity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Products__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Received Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reserved_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reserved Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <formula>(Received_Quantity__c +Adjusted_Quantity__c +AdjustedReceivedqty_c__c  +  Rental_Adjustment_Quantity__c ) -(Used_Quantity__c  +  Reserved_Quantity__c  + Rental_Reserved_Quantity__c +  AvailableAdjustedQty__c +Adjusted_Quantity1__c + Reduced_Adjusted_Quantity__c +Delivered_Quantity__c+Package_Quantity__c+Shipped_Quantity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bin</label>
        <referenceTo>Sublevel_location__c</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivered_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Delivered Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory_Location_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location Product</label>
        <referenceTo>Inventory_Location_Product__c</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Product Line Items</relationshipLabel>
        <relationshipName>Inventory_Location_Product_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Received Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reserved_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reserved Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Location Product Line Item</label>
    <nameField>
        <displayFormat>ILPLI-{0}</displayFormat>
        <label>Inventory Location Product LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Product Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sublevel_location__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Sublevel-locations</relationshipLabel>
        <relationshipName>Sublevel_locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sublevel-locations</relationshipLabel>
        <relationshipName>Sublevel_locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sublevel-location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sublevel-locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/Inventroymaintainctrl.cls
public with sharing class Inventroymaintainctrl {
    @AuraEnabled
    public static wrap fetchIP(string productName, string LocationName){
        wrap wp;
        System.debug('productName>>'+productName);
        System.debug('LocationName>>>'+LocationName);
        /*if(CRUD_FLS_CheckUtility.checkObjCRUD('Product2')
            && CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Inventory__c')
            && CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Inventory_Location_Product__c')
            && CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Inventory_Location_Product_Line_Item__c')
            && CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Inventory_Location__c')
            && CRUD_FLS_CheckUtility.checkReadPermission('Product2',new set<String>{'id','Name'})
            && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Inventory__c',new set<String>{'id','name','sigmaerpdev2__Product_Name__c','sigmaerpdev2__Available_Qty__c','sigmaerpdev2__Shipped_Qty__c','sigmaerpdev2__Reserved_Qty__c','sigmaerpdev2__Delivered_Qty__c'})
            && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Inventory_Location_Product__c',new set<String>{'id','Name','sigmaerpdev2__Products__r.Name','sigmaerpdev2__Net_Quantity__c','sigmaerpdev2__Availability__c','sigmaerpdev2__Received_Quantity__c','sigmaerpdev2__Delivered_Quantity__c','sigmaerpdev2__Inventory_Location__c','sigmaerpdev2__Reserved_Quantity__c'})
            && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Inventory_Location_Product_Line_Item__c',new set<String>{'id','name','sigmaerpdev2__Product__r.Name','sigmaerpdev2__Available_Quantity__c','sigmaerpdev2__Reserved_Quantity__c','sigmaerpdev2__Received_Quantity__c'})
            && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Inventory_Location__c',new set<String>{'id','name','sigmaerpdev2__Location__r.Name'})
          ){*/
              list<wrap>  wrapList = new list<wrap>();
              wp = new wrap();
              Product2 prod = new Product2();
              List<Product2> prodctList = new List<Product2> ();
              List<Inventory_Location__c> invLocList = new  List<Inventory_Location__c>();
              List<Inventory__c> pIList = new List<Inventory__c>();
              List<Inventory_Location_Product__c> invLocPrdList = new List<Inventory_Location_Product__c>();
              List<Inventory_Location_Product_Line_Item__c> prdLIList = new List<Inventory_Location_Product_Line_Item__c>();
              
              Inventory_Location__c iloc =new Inventory_Location__c();
              //if((productName != null || productName =='') && (LocationName!=null || LocationName ==''))
              if(String.isNotBlank(productName) && String.isNotBlank(LocationName))
              {
                system.debug('Inside if>>');  
                prodctList = [select id, name, (select id,name,Product_Name__c,Available_Qty__c,Shipped_Qty__c,Reserved_Qty__c,Delivered_Qty__c from Product_Inventory__r  ),
                                               (select id, Name,Products__r.Name, Net_Quantity__c,Received_Quantity__c,Delivered_Quantity__c,Inventory_Location__c,Inventory_Location_Name__c,Reserved_Quantity__c from Inventory_Location_Products__r where Inventory_Location_Name__c LIKE:LocationName),
                                               (select id, name,Product__r.Name,Available_Quantity__c,Reserved_Quantity__c,  Received_Quantity__c,Bin__r.name,Inventory_Location_Product__r.Inventory_Location_Name__c  from Inventory_Location_Product_Line_Items__r where Inventory_Location_Product__r.Inventory_Location_Name__c LIKE:LocationName) from Product2  where Name LIKE: productName];  
              }
              else if(String.isNotBlank(productName)){
                  system.debug('Inside else>>');
                  prodctList = [select id, name, (select id,name,Product_Name__c,Available_Qty__c,Shipped_Qty__c,Reserved_Qty__c,Delivered_Qty__c from Product_Inventory__r  ),
                                               (select id, Name,Products__r.Name, Net_Quantity__c,Received_Quantity__c,Delivered_Quantity__c,Inventory_Location__c,Inventory_Location_Name__c,Reserved_Quantity__c from Inventory_Location_Products__r),
                                               (select id, name,Product__r.Name,Available_Quantity__c,Reserved_Quantity__c,  Received_Quantity__c,Bin__r.name,Inventory_Location_Product__r.Inventory_Location_Name__c  from Inventory_Location_Product_Line_Items__r) from Product2  where Name LIKE: productName  ];
                 
              }
              else
              {
                system.debug('else>>');
                invLocList = [select id,name,(select id,name,Products__r.Name,Net_Quantity__c,Availability__c,Received_Quantity__c,Delivered_Quantity__c,Inventory_Location__c,Inventory_Location_Name__c,Reserved_Quantity__c  from Inventory_Location_Products__r),(select id,name,Product__r.Name,Available_Quantity__c,Reserved_Quantity__c, Received_Quantity__c,Bin__r.name,Inventory_Location_Product__r.Inventory_Location_Name__c  from Inventory_Location_Product_Line_Items__r ) from Inventory_Location__c where Location__r.Name  LIKE:LocationName ];  
              }
              system.debug('prodctList>>'+prodctList);
              system.debug('invLocList>>'+invLocList);
                if(prodctList.size() > 0) 
                {
                 for(Product2 pr:prodctList){
                      if(pr.Product_Inventory__r.size() > 0){
                          for(Inventory__c pi : pr.Product_Inventory__r){
                              PIList.add(pi);
                          }
                      }
                      if(pr.Inventory_Location_Products__r.size() > 0){
                          for(Inventory_Location_Product__c pi : pr.Inventory_Location_Products__r){
                              invLocPrdList.add(pi);
                          }
                      }
                      if(pr.Inventory_Location_Product_Line_Items__r.size() > 0){
                          for(Inventory_Location_Product_Line_Item__c pi : pr.Inventory_Location_Product_Line_Items__r){
                              prdLIList.add(pi);
                          }
                      }
                  }
                }
                if(invLocList.size()>0)
                {                    
                  for(Inventory_Location__c il:invLocList){
                      
                      if(il.Inventory_Location_Products__r.size() > 0){
                          for(Inventory_Location_Product__c pi : il.Inventory_Location_Products__r){
                              invLocPrdList.add(pi);
                          }
                      }
                      if(il.Inventory_Location_Product_Line_Items__r.size() > 0){
                          for(Inventory_Location_Product_Line_Item__c pi : il.Inventory_Location_Product_Line_Items__r){
                              prdLIList.add(pi);
                          }
                      }
                      
                  }
                }
                  wp.prodinv=pIList;
                  wp.invlocpod=invLocPrdList;
                  wp.ilpli=prdLIList;    
     
              
         // }
        return wp;
    }
    
    public Class wrap
    {
        @AuraEnabled 
        public  list<Inventory__c> prodinv {set;get;}
        @AuraEnabled 
        public list<Inventory_Location_Product__c> invlocpod {set;get;}
        @AuraEnabled
        public list<Inventory_Location_Product_Line_Item__c> ilpli{set;get;}
    }  
}