SigmaCodebackup3rdSep/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Inventory1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Inventory</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Proposal__c.object
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Proposal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Purchase_Order__c.object
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Sigma Orders</relationshipLabel>
        <relationshipName>Sigma_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Stock_In__c.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Stock Receiving (Purchase Order)</relationshipLabel>
        <relationshipName>Stock_In</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stock Receiving</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Stock In Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Receiving</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/SoPaginationHelper.cls
/*=====================================================================================================
Author   : Samad , Sandhya
Company  : Mindlinks Solution Pvt Ltd.
Class    : SoPaginationHelper
Date     : 21/8/2018              
=======================================================================================================*/
public with sharing class SoPaginationHelper {
    
    @AuraEnabled
    public Integer pageSize { get;set; }
    
    @AuraEnabled
    public Integer page { get;set; }
    
    @AuraEnabled
    public Integer total { get;set; }
    
    @AuraEnabled
    public List<Inventory__c> soList { get;set; }
    
    // code used for SigmaOrderHandler , added by sandhya,20/8/2018
    @AuraEnabled
    public Integer pageSizeSigma { get;set; }
    
    @AuraEnabled
    public Integer pageSigma { get;set; }
    
    @AuraEnabled
    public Integer totalSigma { get;set; }
    
    @AuraEnabled
    public List<Sigma_Order__c> sigmaList { get;set; }
    
     @AuraEnabled
     public List<Purchase_Order__c> purchaselist{ get;set; }
    
    @AuraEnabled
     public List<Stock_In__c> stockList{ get;set; }
    
    // code used for OrderHandler , added by sandhya,21/8/2018
    @AuraEnabled
    public Integer pageSizeOrder { get;set; }
    
    @AuraEnabled
    public Integer pageOrder { get;set; }
    
    @AuraEnabled
    public Integer totalOrder { get;set; }
    
    @AuraEnabled
    public List<Order> OrderList { get;set; }
    
    
    // code used for Inventory Location , added by sandhya,27/8/2018
    @AuraEnabled
    public Integer pageSizeIL { get;set; }
    
    @AuraEnabled
    public Integer pageIL { get;set; }
    
    @AuraEnabled
    public Integer totalIL { get;set; }
    
    @AuraEnabled
    public List<Inventory_Location__c> ILList { get;set; }
    
    // code used for ProposalHandling , added by sandhya,28/8/2018
    @AuraEnabled
    public Integer pageSizeProp { get;set; }
    
    @AuraEnabled
    public Integer pageProp { get;set; }
    
    @AuraEnabled
    public Integer totalProp { get;set; }
    
    @AuraEnabled
    public List<Proposal__c> PropList { get;set; }
    
     @AuraEnabled
    public boolean IsCommunityUser { get;set; }
}