SigmaCodebackup3rdSep/objects/Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Locations (Location)</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Inventory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Inventory Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivered_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sold Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory_Location_Name__c</fullName>
        <formula>Inventory_Location__r.Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <formula>(Received_Quantity__c + Increased_Adjusted_Quantity__c +AdjustedReceivedqty__c  +  Rental_Adjustment_Quantity__c ) - (Delivered_Quantity__c + Rental_Delivered_Quantity__c + AvailableAdjustedQty__c+ Reduced_Adjusted_Quantity__c +Reserved_Quantity__c + Deliver_Quantity__c+Picked_Quantity__c+Package_Quantity__c+Shipped_Quantity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Products__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Received Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Stock_Check__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>InProgress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Stock Check</label>
    <nameField>
        <displayFormat>SCN-{0000}</displayFormat>
        <label>Stock Check Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Check</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Stock_Check_Details__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory_Location_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location Product</label>
        <referenceTo>Inventory_Location_Product__c</referenceTo>
        <relationshipName>Stock_Check_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location</label>
        <referenceTo>Inventory_Location__c</referenceTo>
        <relationshipLabel>Stock Check  LineItems</relationshipLabel>
        <relationshipName>Stock_Check_LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <label>Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Damaged Stock</fullName>
                </value>
                <value>
                    <fullName>Missing Stock</fullName>
                </value>
                <value>
                    <fullName>Not Known</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verified - Not Matched</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StockCheckbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>StockCheckbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stock_Check_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stock Check Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Check__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Check</label>
        <referenceTo>Stock_Check__c</referenceTo>
        <relationshipName>Stock_Check_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stock Check LineItems</label>
    <nameField>
        <displayFormat>SCD-{0000}</displayFormat>
        <label>Stock Check Details Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Check  LineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/StockCheckController.cls
public with sharing class StockCheckController {


@AuraEnabled
    public static List<Inventory_Location_Product__c> fetchILP(){
    
    List<Inventory_Location_Product__c> ILPlist;
    
    /*if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Inventory_Location_Product__c',new Set<String>{'id','name','sigmaerpdev2__Delivered_Quantity__c','sigmaerpdev2__Inventory_Location_Name__c','sigmaerpdev2__Product_Name__c','sigmaerpdev2__Net_Quantity__c','sigmaerpdev2__Products__c','sigmaerpdev2__Products__r.Name','sigmaerpdev2__Inventory_Location__c','sigmaerpdev2__Received_Quantity__c'})
     )
     {*/
    ILPlist = [select id, name, Products__c, Products__r.Name,Products__r.Product_Bar_Code__c,Delivered_Quantity__c,Inventory_Location_Name__c, Inventory_Location__c,Received_Quantity__c,Product_Name__c,Net_Quantity__c from Inventory_Location_Product__c where  Products__c!=NULL order by Products__r.Name];    
     system.debug('ILPlist1>>>>>'+ILPlist);
     //}
  return ILPlist;
  }
  
  @AuraEnabled
    public static List<Inventory_Location_Product__c> fetchselectILP(String locname){
    
    List<Inventory_Location_Product__c> ILPlist;
    
     /*if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Inventory_Location_Product__c',new Set<String>{'id','name','sigmaerpdev2__Delivered_Quantity__c','sigmaerpdev2__Inventory_Location_Name__c','sigmaerpdev2__Product_Name__c','sigmaerpdev2__Net_Quantity__c','sigmaerpdev2__Products__c','sigmaerpdev2__Products__r.Name','sigmaerpdev2__Inventory_Location__c','sigmaerpdev2__Received_Quantity__c'})
     )
     {*/
    ILPlist = [select id, name, Products__c,Code__c,Products__r.Name,Products__r.Product_Bar_Code__c,Delivered_Quantity__c,Inventory_Location_Name__c, Inventory_Location__c,Received_Quantity__c,Product_Name__c,Net_Quantity__c from Inventory_Location_Product__c where  Products__c!=NULL and Inventory_Location__r.Location__r.id =: locname order by Products__r.Name];    
     system.debug('ILPlist2>>>>'+ILPlist);
     //}
  return ILPlist;
  }
  
  
  @AuraEnabled
  public static string SaveStockCheck(String StockDetails,Stock_Check__c StockCheck)
  {
  /*if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Stock_Check__c')
      && CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Stock_Check_Details__c')
      && CRUD_FLS_CheckUtility.checkFLS('sigmaerpdev2__Stock_Check_Details__c',new set<String>{'sigmaerpdev2__Reason_Code__c','sigmaerpdev2__Stock_Check__c','sigmaerpdev2__StockCheckbox__c','sigmaerpdev2__Stock_Check_Quantity__c','sigmaerpdev2__Status__c','sigmaerpdev2__Available_Quantity__c'})
      && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Stock_Check__c',new set<String>{'id'})
     && CRUD_FLS_CheckUtility.checkFLS('sigmaerpdev2__Stock_Check__c',new set<String>{'sigmaerpdev2__Status__c'})
   )
   {*/
        
        if(StockCheck != null){        
            insert StockCheck;
           
        }        
         
        List<Stock_Check_Details__c> scdToInsert = new List<Stock_Check_Details__c>();
        Type  objectType =Type.forName('List<Stock_Check_Details__c>');
        List<Stock_Check_Details__c> scDetails=(List<Stock_Check_Details__c>) JSON.deserialize(StockDetails, objectType);
        if(!scDetails.isEmpty()){
            for(Stock_Check_Details__c scd:scDetails){
               // added by babji (scd.StockCheckbox__c==true)
                if(StockCheck.Id != null){
                    scd.Stock_Check__c = StockCheck.Id;
                    if(scd.Reason_Code__c =='--None--'){
                        scd.Reason_Code__c = null;
                    }
                    
                    if(scd.StockCheckbox__c == true && scd.Available_Quantity__c!= scd.Stock_Check_Quantity__c){
                        scd.Status__c ='Verified - Not Matched';
                        
                    }
                    if(scd.StockCheckbox__c == true && scd.Available_Quantity__c== scd.Stock_Check_Quantity__c){
                        scd.Status__c ='Verified';
                    }
                    if(scd.StockCheckbox__c == true && scd.Available_Quantity__c== 0){
                        scd.Status__c ='Verified';
                    }
                    if(scd.StockCheckbox__c == false ){
                        scd.Status__c ='Not Verified';
                    }
                  scdToInsert.add(scd);
                }
                
            }
            if(!scdToInsert.isEmpty()){
                insert scdToInsert;
                Boolean chckFlag = false;
                for(Stock_Check_Details__c scd:scdToInsert){
                    if(scd.StockCheckbox__c){
                        chckFlag = true;
                    }
                    else{
                    chckFlag = false;
                       break;
                    }
                }
                Stock_Check__c  scToUpdate = [select id,Status__c from Stock_Check__c where Id =: StockCheck.Id];

                if(chckFlag){
                    scToUpdate.Status__c = 'Completed';
                    update scToUpdate;
                    return scToUpdate.Id;
                }
                else{
                scToUpdate.Status__c = 'InProgress';
                    update scToUpdate;
                    return scToUpdate.Id;
                }
               
                
            }
        }
        //}
    
        return null;
  }

}