SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Location_Name__c</fullName>
        <formula>Inventory_Location__r.Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <formula>(Received_Quantity__c + Increased_Adjusted_Quantity__c +AdjustedReceivedqty__c  +  Rental_Adjustment_Quantity__c ) - (Delivered_Quantity__c + Rental_Delivered_Quantity__c + AvailableAdjustedQty__c+ Reduced_Adjusted_Quantity__c +Reserved_Quantity__c + Deliver_Quantity__c+Picked_Quantity__c+Package_Quantity__c+Shipped_Quantity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/Stockcheckpage.cls
public with sharing class Stockcheckpage {
    public string stckid{get;set;}
    public string pkgid{get;set;}
    public Date Date1{get;set;}
    public Stockcheckpage (ApexPages.StandardController objStockcheckpage){
        stckid=System.currentPageReference().getParameters().get('name');
        pkgid=System.currentPageReference().getParameters().get('packagedBy');
        Date1=Date.valueOf(System.currentPageReference().getParameters().get('selDate'));
     //   Date1=System.currentPageReference().getParameters().get('selDate');
        
    }
    List<Inventory_Location_Product__c> stcklist=new List<Inventory_Location_Product__c>();
    public List<Inventory_Location_Product__c> getStockList(){
        if(stckid!=null && stckid!='' && stckid!='undefined'){
            
            stcklist=[select Inventory_Location_Name__c ,Products__r.name,Net_Quantity__c,Message__c,Availability__c from Inventory_Location_Product__c where Inventory_Location_Name__c =:stckid and Net_Quantity__c>0];
        }
        else 
        {
            stcklist=[select Inventory_Location_Name__c ,Products__r.name,Net_Quantity__c,Message__c,Availability__c from Inventory_Location_Product__c where Net_Quantity__c>0];  
            system.debug('stcklist>>'+stcklist);
        }
        return stcklist; 
    }
    
}