SigmaCodebackup3rdSep/objects/Inventory_Location_Product__c.object
<CustomObject>
    <fields>
        <fullName>Delivered_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sold Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Location Products</relationshipLabel>
        <relationshipName>Inventory_Location_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reserved_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reserved Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inventory Location Product</label>
    <nameField>
        <displayFormat>ILP-{00000}</displayFormat>
        <label>Inventory Location Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Location Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/OrderLineLocation__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inventory_Location_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Location Product</label>
        <referenceTo>Inventory_Location_Product__c</referenceTo>
        <relationshipLabel>OrderLineItemLocations</relationshipLabel>
        <relationshipName>OrderLineItemLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Line__c</fullName>
        <label>Order Line</label>
        <referenceTo>Product_Order_Price_Book__c</referenceTo>
        <relationshipLabel>OrderLineItemLocations</relationshipLabel>
        <relationshipName>OrderLineItemLocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>OrderLineItemLocations</relationshipLabel>
        <relationshipName>OrderLineItemLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderLineItemLocation</label>
    <nameField>
        <displayFormat>OLL-{0000}</displayFormat>
        <label>OrderLineLocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderLineItemLocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/SalesOrderTBIScheduler.cls
//code to revert back TBI inventory
//Author -  Harish 13-05-2021
global class SalesOrderTBIScheduler implements Schedulable {

    global void execute(SchedulableContext sc)
    {
        try
        {
			Map<Id,Map<Id,decimal>> ProLocQty = new Map<Id,Map<Id,decimal>>();
			
			for(OrderLineLocation__c OLL : [Select id,name,Product__c,Inventory_Location_Product__c,Quantity__c,Order_Line__c from OrderLineLocation__c where End_Date__c = TODAY])
			{
				if(ProLocQty.containskey(OLL.Product__c))
				{
					if(ProLocQty.get(OLL.Product__c).containskey(OLL.Inventory_Location_Product__c))
					{
						Decimal Qty = ProLocQty.get(OLL.Product__c).get(OLL.Inventory_Location_Product__c);
						ProLocQty.get(OLL.Product__c).put(OLL.Inventory_Location_Product__c,OLL.Quantity__c+Qty);
					}
					else
					{
						ProLocQty.get(OLL.Product__c).put(OLL.Inventory_Location_Product__c,OLL.Quantity__c);
					}
					
				}
				else
				{
					Map<Id,Decimal>LocQty = new Map<Id,Decimal>{OLL.Inventory_Location_Product__c => OLL.Quantity__c};
					ProLocQty.put(OLL.Product__c,LocQty);
				}
				System.debug('ProLocQtyMap@@@'+ProLocQty);
				
				
			}
			
			List<Inventory_Location_Product__c>ILPList = [Select Id,Name,Products__c,Reserved_Quantity__c,Delivered_Quantity__c from Inventory_Location_Product__c where Products__c=:ProLocQty.keyset()];
			for(Inventory_Location_Product__c ILP:ILPList)
			{
				if(ProLocQty.containskey(ILP.Products__c)&&ProLocQty.get(ILP.Products__c).containskey(ILP.Id))
				{
					ILP.Delivered_Quantity__c -=ProLocQty.get(ILP.Products__c).get(ILP.Id);
					
				}
				
			}
			if(ILPList.size()>0)
			Update ILPList;
		}
		catch(Exception e) {
        System.debug('An exception occurred: at line number '+e.getLineNumber()+' Message ' + e.getMessage());
        }
	}
}