SigmaCodebackup3rdSep/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>Truck</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Package Location</fullName>
                </value>
                <value>
                    <fullName>Receiving Location</fullName>
                </value>
                <value>
                    <fullName>Waste Management Location</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Location</fullName>
                </value>
                <value>
                    <fullName>Storage Location</fullName>
                </value>
                <value>
                    <fullName>Shipping Location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_transfer__c.object
<CustomObject>
    <fields>
        <fullName>ProductTransferToLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer To Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Transfer To Location</relationshipLabel>
        <relationshipName>Product_Transfer_To_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Transfer_From_location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Transfer From location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Product Transfer From Location</relationshipLabel>
        <relationshipName>Product_Transfer_From_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_Status__c</fullName>
        <label>Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Transfer Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Product Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Transfer</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Product Transfer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Transfer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/TestTransferStatusCompleted.cls
@isTest
public class TestTransferStatusCompleted { 
  @isTest
    public static void test(){
        test.startTest();
        Location__c fromLocation = new Location__c(Location_Name__c = 'Central Warehouse', Location_Type__c='WareHouse');
        Location__c toLocation = new Location__c(Location_Name__c ='Truck 1', Location_Type__c='Truck');
        insert fromLocation;
        insert toLocation;
        
        Product_transfer__c productTransfer = new Product_transfer__c(Product_Transfer_From_location__c=fromLocation.Id,ProductTransferToLocation__c=toLocation.Id);
        insert productTransfer;
        
        productTransfer.Transfer_Status__c = 'Transfer Completed';
        update productTransfer;
        test.stopTest();
         System.assert(true);
    }
}