SigmaCodebackup3rdSep/objects/Manufacturing_Run__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturing Run</label>
        <referenceTo>Manufacturing_Run__c</referenceTo>
        <relationshipLabel>Manufacturing Run</relationshipLabel>
        <relationshipName>Manufacturing_Run</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Manufacturing Run</label>
    <nameField>
        <displayFormat>Rec-{0000}</displayFormat>
        <label>Manufacturing Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manufacturing Run</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Project_Resource__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interval__c</fullName>
        <label>Interval</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hour</fullName>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturing Run</label>
        <referenceTo>Manufacturing_Run__c</referenceTo>
        <relationshipName>Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Resource Name</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Allocate Resources</relationshipLabel>
        <relationshipName>Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QA</fullName>
                </value>
                <value>
                    <fullName>Developer Level-1</fullName>
                </value>
                <value>
                    <fullName>Developer Level-2</fullName>
                </value>
                <value>
                    <fullName>Developer Level-3</fullName>
                </value>
                <value>
                    <fullName>Business Analyst</fullName>
                </value>
                <value>
                    <fullName>Requirement Designer</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>UI Developer</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Allocate Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>resource</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocate Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Human Resource</fullName>
                </value>
                <value>
                    <fullName>Business Analyst</fullName>
                </value>
                <value>
                    <fullName>Quality Analyst</fullName>
                </value>
                <value>
                    <fullName>Salesforce Developer</fullName>
                </value>
                <value>
                    <fullName>Software Engineer</fullName>
                </value>
                <value>
                    <fullName>Machine</fullName>
                </value>
                <value>
                    <fullName>Web Developer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <recordTypes>
        <fullName>Resources</fullName>
        <active>true</active>
        <label>Resources</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/AddResourcesController.cls
//code added to handle Resource allocation for MR module Gantt Usage by Rashmi on 20-12-2020
public with sharing class AddResourcesController {
    
     @AuraEnabled
    public static Project_Resource__c saveResourceObject(String resource, String ManuID)
    {
        system.debug('resource>>'+resource);
        system.debug('ManuID>>'+ManuID);
        Project_Resource__c resourceRecord;
      if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Project_Resource__c')
        && CRUD_FLS_CheckUtility.checkFLS('sigmaerpdev2__Project_Resource__c',new set<String>{'sigmaerpdev2__Manufacturing_Run__c','sigmaerpdev2__Resource__c'}))
        {
       
          
           try{
           
            Type otype = Type.forName('sigmaerpdev2__Project_Resource__c');
            resourceRecord = (Project_Resource__c )JSON.deserialize(resource,otype);
           
            resourceRecord.Resource__r = null;
        
            resourceRecord.Manufacturing_Run__c=ManuID;
            upsert resourceRecord;
            
          }
          catch (Exception ex){
            
          }
          }
        return resourceRecord;
    }
    @AuraEnabled
    public static Resource__c fetchResourceData(String resourceid)
    { 
    Resource__c res;
    if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Resource__c')
        &&  CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Resource__c',new set<String>{'id','Name','sigmaerpdev2__Last_Name__c','sigmaerpdev2__Roles__c'})){
        
        res=[select id,Name,Last_Name__c,Roles__c from Resource__c where id=:resourceid limit 1];
        }
        return res; 
    }
    @AuraEnabled  
    public static Resource__c getResData(String resourceid)
    {
        Resource__c res;
        if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Resource__c')
              &&  CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Resource__c',new set<String>{'id','Name','sigmaerpdev2__Roles__c'})){
       
        if(resourceid !=null && resourceid !='')
        {
            res=[select id,Name,Roles__c from Resource__c where id=:resourceid limit 1];
            
        }
              }
        return res;
        
    }
    
    @AuraEnabled  
    Public static Project_Resource__c getResourceInfo(String resourceID)
    {
         List<Project_Resource__c> dataList;
        if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Project_Resource__c')
              &&  CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Project_Resource__c',new set<String>{'id','Name','sigmaerpdev2__Manufacturing_Run__c','sigmaerpdev2__Resource__c','sigmaerpdev2__Resource__r.Name','sigmaerpdev2__Resource__r.sigmaerpdev2__Roles__c','sigmaerpdev2__Interval__c','sigmaerpdev2__Start_Date__c','sigmaerpdev2__End_Date__c'})){
        
       
       dataList=new List<Project_Resource__c>();
        dataList=[select id,name,Manufacturing_Run__c,Resource__c,Resource__r.Name,Resource__r.Roles__c,Interval__c,Start_Date__c,End_Date__c from Project_Resource__c where Id=:resourceID limit 1000];
              }
        return dataList[0];
    }
    //code added to fetch existing Resources in respective MR Table view for Resource Planning Usage
    @AuraEnabled
    public static List<Project_Resource__c> fetchMRResource(String manfRunId)
    {
        system.debug('manfRunId>>>>'+manfRunId);
        List<Project_Resource__c> manuResource;
        if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Project_Resource__c') 
            &&  CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Project_Resource__c',new set<String>{'id','Name','sigmaerpdev2__Manufacturing_Run__c','sigmaerpdev2__Resource__r.Name','sigmaerpdev2__Resource__r.sigmaerpdev2__Roles__c','sigmaerpdev2__Interval__c','sigmaerpdev2__Start_Date__c','sigmaerpdev2__End_Date__c'}))
        {
            if(manfRunId !=null && manfRunId !='')
            {
                manuResource =[select id,name,Manufacturing_Run__c,Resource__r.Name,Resource__r.Roles__c,Interval__c,Start_Date__c,End_Date__c from Project_Resource__c where Manufacturing_Run__c=:manfRunId limit 1000];                
            }
        }
        return manuResource;
    }
    
}