SigmaCodebackup3rdSep/objects/OfferAppointmentDefaultRecord__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Initial_Record_Display__c</fullName>
        <label>Initial Record Display</label>
        <precision>16</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Offer Appointment Default Record</label>
</CustomObject>

SigmaCodebackup3rdSep/objects/Product_Order_Price_Book__c.object
<CustomObject>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>POPB-{0000}</displayFormat>
        <label>Product Order Price Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Customer</fullName>
                </value>
                <value>
                    <fullName>Credit Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tax(%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Sigma Orders</relationshipLabel>
        <relationshipName>Sigma_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Tax__c.object
<CustomObject>
    <description>This is built for Magento Platform integration. Do not delete.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Availability_Date__c</fullName>
        <label>Preferred Service Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_City__c</fullName>
        <label>Service City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Country__c</fullName>
        <label>Service Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_State_Province__c</fullName>
        <label>Service State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Street__c</fullName>
        <label>Service Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Warrenty_End_date__c</fullName>
        <formula>Sigma_orders__r.Service_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Warrenty End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Zip_Postal_Code__c</fullName>
        <label>Service Zip/Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sigma_orders__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Order_Price_Book__c.Sigma_Order__c</field>
                <operation>equals</operation>
                <valueField>$Source.Sigma_Order__c</valueField>
            </filterItems>
            <filterItems>
                <field>Product_Order_Price_Book__c.Order_Status__c</field>
                <operation>equals</operation>
                <value>Delivered</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Order_Price_Book__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Work Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Invoiced to Customer</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Another Visit Needed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax(%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Order Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/ServiceOfferAppoinment.cls
public with sharing class ServiceOfferAppoinment
{
     public static String addressBreakLenght = '';

    @AuraEnabled
    public static workOrderWrapper fetchOfferAppointment(Id recId)
    {
        /*Map<string,OfferAppointmentDefaultRecord__c> recordCount = OfferAppointmentDefaultRecord__c.getAll(); 
        OfferAppointmentDefaultRecord__c showRecord=recordCount.values();*/
        Work_Order__c work=[Select Id,Name,sigmaerpdev2__Is_Payment_Made__c,Account__c,sigmaerpdev2__Account__r.Name,Account__r.Customer_Type__c,Tax__c ,sigmaerpdev2__Work_Type__r.Name,Service_Street__c,
                       sigmaerpdev2__Account__r.AccountNumber,sigmaerpdev2__Work_Type__c,Service_Warrenty_End_date__c,sigmaerpdev2__TotalAmount__c,sigmaerpdev2__Paid_Amount__c,Service_City__c,Service_Country__c,
                       sigmaerpdev2__Work_Type__r.sigmaerpdev2__Service_Charge__c ,Sigma_orders__r.Total_Price__c,sigmaerpdev2__FFP_MR_Contact__c,Status__c,Service_State_Province__c,Service_Zip_Postal_Code__c,
                       sigmaerpdev2__Due_Amount__c,Net_Amount__c FROM sigmaerpdev2__Work_Order__c where Id =: recId LIMIT 1 For update];
        system.debug('work'+work);
        workOrderWrapper workWrap=new workOrderWrapper();
        workWrap.workOrderDetail=work;
      //  workWrap.defaultview= Integer.valueOf(showRecord.Initial_Record_Display__c);
        return workWrap;
    }
    
     @AuraEnabled
    public static List<Date> Getdates(Date startdate,Date enddate)
    {
         system.debug('startdate>>'+startdate);
         system.debug('enddate>>>>'+enddate);
        Date d1 = startdate;
		Date d2 = enddate;
		List<date> datesmonthYearSet = new List<date>();
        Integer noOfDays = startdate.daysBetween(enddate);
		system.debug('noOfDays=='+noOfDays);
		
        Integer i =0 ;
		while(i <= noOfDays)
	{
  		 date indDate = startdate.addDays(i);
   		 datesmonthYearSet.add(indDate);
   		i++;    
	}
system.debug('datesmonthYearSet=='+datesmonthYearSet);
return datesmonthYearSet;
   	
    }
    
    @AuraEnabled
    public static void SelectedDate(Id rec,Date SelDate)
    {
        system.debug('rec>>'+rec);
         system.debug('seldate>>>>'+seldate);
        
        Work_Order__c work=[Select Id,Name,Customer_Availability_Date__c from Work_Order__c where Id =: rec];
       
        work.Customer_Availability_Date__c=seldate;
         system.debug('work.Customer_Availability_Date__c>>'+work.Customer_Availability_Date__c);
            
        update work;
        
    
    }
    
    
    @AuraEnabled
    public static responseWrap fetchWorkOrderdDetails(Id recId)
    {
        responseWrap responseError = new responseWrap();
        Map<Id,string> wordOrderIds = new Map<Id,string>();
        list<Work_Order__c> listWO = [select id,Status__c from Work_Order__c where id=:recId];
        system.debug('listWO'+listWO);
        for(Work_Order__c woList : listWO){
            wordOrderIds.put(woList.id,woList.Status__c);
        }
        List<serviceAppointment> spList=[select id,ParentRecordId from serviceAppointment where ParentRecordId=:wordOrderIds.keyset()]; 
        system.debug('spList'+spList);
        for(serviceAppointment sp :spList){
            if(sp.ParentRecordId !=null && wordOrderIds.keyset().contains(sp.ParentRecordId)){
                responseError.status='Success';               
            }else{
                 responseError.status='Failure';
            }
        } 
        
        //if(wordOrderIds.keySet().size() > 0 && wordOrderIds.keySet() != null)
            return responseError; 
    }
    
    @AuraEnabled
    public static ServiceAppointment fetchServiceAppointment(Id recordId){
        ServiceAppointment sa =  [SELECT id,WorkTypeId,WorkType.name,Street,city,postalCode,country,state,EarliestStartTime,DueDate,ParentRecordId,ParentRecord.name,Status from ServiceAppointment Where Id =:recordId LIMIT 1 For update];
        return sa;
    }    
    
     public class responseWrap
    {
        @AuraEnabled public String type{get;set;}
        @AuraEnabled public String errorCode{get;set;}
        @AuraEnabled public String status{get;set;}
        @AuraEnabled public String serviceAppointmentId{get;set;}
        @AuraEnabled public String description{get;set;}
     
        
    }
    
   
    public class workOrderWrapper
    {
        @AuraEnabled public Work_Order__c workOrderDetail{get;set;}
        @AuraEnabled public Integer defaultview{get;set;}
        
        
    }
 
    
}