SigmaCodebackup3rdSep/objects/Payment_Request_Response_QS__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Request Response QSs</relationshipLabel>
        <relationshipName>Payment_Request_Response_QSs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sigma_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sigma Order</label>
        <referenceTo>Sigma_Order__c</referenceTo>
        <relationshipLabel>Payment Request Response QSs</relationshipLabel>
        <relationshipName>Payment_Request_Response_QSs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Payment Request Response QS</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Payment Request Response QS No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request Response QSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/PaymentCntrl.cls
public Class PaymentCntrl
{
  public String Token {get;set;} 
  public Boolean stripePaymentFlag {get;set;}  
  public Boolean payPalPaymentFlag {get;set;}    
  public String RecordId{get;set;}  
    public PaymentCntrl()
    {
        System.debug('Inside PaymentCntrl');
        Token =  ApexPages.currentPage().getParameters().get('token');
        System.debug('Inside PaymentCntrl Token  IS:: '+Token );  
        
       Sigma_Order__c so = [select id,name from sigmaerpdev2__Sigma_Order__c  ORDER BY CreatedDate DESC limit 1 ];       
        RecordId = so.id;
      /* Payment_Request_Response_QS__c pqs = [Select Id,Name,Account__c,Account__r.ParentId From Payment_Request_Response_QS__c where Token__c =:Token];
        System.debug('Inside PaymentCntrl pqs 01:: '+pqs );
         System.debug('InsidePaymentCntrl  pqs 01 :: '+pqs.Account__r.ParentId );  
        
        Account acc = [Select Id,Name,Type,Payment_Vendor__c From Account where Id =: pqs.Account__r.ParentId];
        System.debug('Inside PaymentCntrl accIs 02:: '+acc);
        System.debug('Inside  PaymentCntrl accIs 02:: '+acc.Payment_Vendor__c );  
        
        if(acc.Type != Null)
        {    
            if( acc.Type == 'Merchant' && acc.Payment_Vendor__c == 'Stripe') */
           // {
                stripePaymentFlag  = true;
           // }
           /* else if( acc.Type == 'Merchant' && acc.Payment_Vendor__c == 'Paypal' )
            {
               payPalPaymentFlag = true; 
            }
        }
               
        
        System.debug('stripePaymentFlag Is:: '+stripePaymentFlag);
        System.debug('Inside payPalPaymentFlag Is:: '+payPalPaymentFlag );
        */
    }
    
}