SigmaCodebackup3rdSep/objects/Project2__c.object
<CustomObject>
    <fields>
        <fullName>Interval__c</fullName>
        <label>Interval</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Actual_Billing_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Actual Billing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Actual_Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Actual Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Estimated Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Expected_Billing_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Expected Billing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Project_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Billing_Amount__c</fullName>
        <formula>Billing_Rate__c *  Actual_Effort__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Billing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Currency__c</fullName>
        <label>Billing Currency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Effort__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Estimated Effort</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Excepted_Billing_Amount__c</fullName>
        <formula>Billing_Rate__c  *  Estimated_Effort__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Excepted Billing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interval__c</fullName>
        <label>Interval</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hour</fullName>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Resource Name</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Allocate Resources</relationshipLabel>
        <relationshipName>Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocate Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>resource</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocate Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Currency__c</fullName>
        <label>Billing Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/projectresourcedata.cls
public with sharing class projectresourcedata
{
  @InvocableMethod
  public static void projectresourcedataobj(List<Id> LeadIds){
   
  Decimal totalestimateffort = 0;
  Decimal totalactualeffort=0;
  Decimal totalexpectedbillingamount=0;
  Decimal totalactualbillingamount =0;
  String billingcurrency;
  Id ResourceId;
  String interval; 
  List<Project2__c> ListProject = new List<Project2__c>();
  Set<Id>ProjectId =new Set<Id>();
  List<Project_Resource__c> ListProjectResource = new List<Project_Resource__c>();
    if(LeadIds.size() > 0){
      ListProjectResource=[Select id,name,Resource__c,Project2__c,Estimated_Effort__c,Billing_Currency__c,Actual_Effort__c,Actual_Billing_Amount__c,Excepted_Billing_Amount__c,Interval__c from Project_Resource__c where id IN:LeadIds];
      system.debug('ListProject>>'+ListProjectResource);
      for(Project_Resource__c ProRes :ListProjectResource){
        if(ProRes.Project2__c !=null)
        {
          ProjectId.add(ProRes.Project2__c);   
          interval = ProRes.Interval__c;         
        }

      }
    }


    if(ProjectId.size() > 0) {
      ListProject = [SELECT Id, Name,Interval__c,Total_Estimated_Effort__c,Total_Actual_Effort__c,Total_Expected_Billing_Amount__c,Total_Actual_Billing_Amount__c,(Select id,name,Resource__c,Project2__c,Estimated_Effort__c,Actual_Effort__c,Actual_Billing_Amount__c,Billing_Currency__c,Excepted_Billing_Amount__c,Interval__c from Project_Resources__r) FROM Project2__c WHERE Id IN : ProjectId];  
      system.debug('ListProject>>>'+ListProject);
      for(Project2__c pro :ListProject)
      {
          for(Project_Resource__c prores :pro.Project_Resources__r)
          {
                  
          totalestimateffort += ProRes.Estimated_Effort__c;
          totalactualeffort +=ProRes.Actual_Effort__c;
          totalexpectedbillingamount +=ProRes.Excepted_Billing_Amount__c;
          totalactualbillingamount += ProRes.Actual_Billing_Amount__c;
          billingcurrency += prores.Billing_Currency__c;
		  ResourceId = prores.Resource__c;
           
          }
        pro.Total_Estimated_Effort__c = totalestimateffort;
        pro.Total_Actual_Effort__c = totalactualeffort;
        pro.Total_Expected_Billing_Amount__c = totalexpectedbillingamount;
        pro.Total_Actual_Billing_Amount__c = totalactualbillingamount;
        pro.Interval__c = interval;
          
                
      }
      //update ListProject;
      
      try {
        update ListProject;
          } 
        catch(DmlException e) {
        System.debug('The following exception has occurred: ' + e.getMessage());
                }
            
      }
  //}
  }
}