SigmaCodebackup3rdSep/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Date__c</fullName>
        <label>Expected Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Net_Quantity__c</fullName>
        <label>Net Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Paid_Amount__c</fullName>
        <label>Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Fully Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Supplier__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Supplier, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Partial Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Partial Delivery</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount1__c</fullName>
        <label>Total Amount</label>
        <summarizedField>Purchase_Order_Product__c.Total_Amount__c</summarizedField>
        <summaryForeignKey>Purchase_Order_Product__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Net Buying Price</label>
        <summarizedField>Purchase_Order_Product__c.Buying_Price__c</summarizedField>
        <summaryForeignKey>Purchase_Order_Product__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>sub_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>sub Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/purchaseorderhandller.cls
/*=====================================================================================================
Author   : vidya minajigi
Company  : Mindlinks Solution Pvt Ltd.
Class    : purchaseorderhandller
Date     : 5/2/2020              
=======================================================================================================*/
public with sharing class purchaseorderhandller
{
    
    
   
    @AuraEnabled
    public static SoPaginationHelper fetchpurchaseorderList(Decimal pageNumber)
    {
        SoPaginationHelper r;
        
        if( CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Purchase_Order__c') && 
          CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Purchase_Order__c',new set<String>{'id','Name','sigmaerpdev2__Product_Supplier__c','sigmaerpdev2__Total_Amount__c','sigmaerpdev2__Order_Date__c','sigmaerpdev2__Expected_Date__c','CreatedById','sigmaerpdev2__Status__c','sigmaerpdev2__sub_Approval__c','sigmaerpdev2__Payment_Status__c','sigmaerpdev2__Paid_Amount__c','sigmaerpdev2__Net_Quantity__c','sigmaerpdev2__Product_Supplier__r.Name'})
          ){
            
              Integer pageSize = 10;
              Integer offset = ((Integer)pageNumber - 1) * pageSize;
              
              r =  new SoPaginationHelper();
              r.pageSizeSigma = pageSize;
              r.pageSigma = (Integer) pageNumber;
              r.totalSigma = [SELECT count() FROM Purchase_Order__c];
              
              r.purchaselist = [select id,Name,CreatedById,Product_Supplier__c,Product_Supplier__r.Name,Total_Amount__c,Total_Amount1__c,Order_Date__c,Expected_Date__c,Status__c,Payment_Status__c,sub_Approval__c,Paid_Amount__c,Net_Quantity__c from Purchase_Order__c
                             order by createddate desc limit :pageSize offset :offset];
             
          }
        
        return r;
        
    }
     @AuraEnabled
    public static String deletepurchaseorder(Id purchaseOrderId){
        if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev2__Purchase_Order__c') 
        && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev2__Purchase_Order__c',new set<String>{'id'}))
         {
              try{        
                 
                  List<Purchase_Order__c> delpurchaseOrderList = [select id from Purchase_Order__c where id = :purchaseOrderId];
                  delete delpurchaseOrderList;
                 
              }catch(Exception e){
                 
                  return null;
              }
          }
        return null;
    }
    }