SigmaCodebackup3rdSep/objects/Service_Appointments__c.object
<CustomObject>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Appointments</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Service Appoitments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Site_Visits__c.object
<CustomObject>
    <fields>
        <fullName>Service_Appointments__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Appointments</label>
        <referenceTo>Service_Appointments__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>Site_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Site Visits</relationshipLabel>
        <relationshipName>Site_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Visits</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Work Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Invoiced to Customer</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Another Visit Needed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Order Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/CancelorReschduleWO.cls
public class CancelorReschduleWO {
    
     @AuraEnabled
    public static Work_Order__c cancelWO(id recId,string rsn)
    {
    system.debug('recId?'+recId);
        system.debug('reasons>>>'+rsn);
       
        
        Work_Order__c work=[Select Id,Name,Status__c,Cancel_Reason__c from Work_Order__c where Id =: recId];
        if(work.Status__c=='Assigned'){
        work.Status__c='Cancelled';
        work.Cancel_Reason__c= rsn;
        }
       
       
        update work;
        
        
        
        if(work.Status__c=='Cancelled' ){
        Service_Appointments__c[] ser=[Select Id,Name from Service_Appointments__c where Work_Order__c=:recId];
        if (!ser.isEmpty()){
            delete ser;
           
            
        }
            
            Site_Visits__c[] sv=[Select Id,Name from Site_Visits__c where Work_Order__c=:recId];
            system.debug('sv???>>'+sv);
       		 if (!sv.isEmpty()){
				delete sv;        
        	}
   
        
        sigmaerpdev2__Work_Order_Assignment__c previousWOA = [SELECT Id, sigmaerpdev2__Technician__c FROM sigmaerpdev2__Work_Order_Assignment__c WHERE sigmaerpdev2__Work_Order__c=:recId LIMIT 1];
    	 system.debug('previousWOA???>>'+previousWOA);
            delete previousWOA;
        
        }
        
        
        
        return work;
    }
    
    @AuraEnabled
    public static void rescheduleWO(id recId)
    {
    system.debug('recId?'+recId);
        Work_Order__c work=[Select Id,Name,Status__c from Work_Order__c where Id =: recId];
        work.Status__c='Cancelled';
       
        update work;
        
        if(work.Status__c=='Cancelled'){
        Service_Appointments__c[] ser=[Select Id,Name from Service_Appointments__c where Work_Order__c=:recId];
            system.debug('ser>>>'+ser);
            if (!ser.isEmpty()){
            delete ser;
        }
        
            
            
               }
    
    }

}