SigmaCodebackup3rdSep/objects/Sigma_Order__c.object
<CustomObject>
    <fields>
        <fullName>Net_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sigma Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sigma Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sigma Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/OrderDetailsCntrl.cls
public class OrderDetailsCntrl
{
	public class OrderData
    {
        @AuraEnabled
        public String OrderNumber;
        @AuraEnabled
        public Decimal TotalAmount;
        @AuraEnabled
        public Decimal Tax;
        @AuraEnabled
        public Decimal NetAmount;
         
    }
	@AuraEnabled
	public static OrderData FetchOrderData(String OrderId)
	{
		Sigma_Order__c SO = [Select id,Name,Tax_Amount__c,Net_Amount__c,TotalAmount__c from Sigma_Order__c where id=:OrderId];
		
		OrderData OD = new OrderData();
		OD.OrderNumber = SO.Name;
		OD.TotalAmount = SO.Net_Amount__c;
		OD.Tax = SO.Tax_Amount__c;
		OD.NetAmount = SO.TotalAmount__c;
		return OD;
	}
}