SigmaCodebackup3rdSep/objects/Stock_In__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stock Receiving</relationshipLabel>
        <relationshipName>Stock_In1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received_Date_Time__c</fullName>
        <label>Received Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stock Receiving (Vendor)</relationshipLabel>
        <relationshipName>Stock_Receiving</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Stock Receiving</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Stock In Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Receiving</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/StockRecievingHandler.cls
public with sharing class StockRecievingHandler
{
    
    
    // Code For Stock Recieving
    @AuraEnabled
    public static SoPaginationHelper fetchStockRecievingList(Decimal pageNumber)
    {
        SoPaginationHelper r;
        
      /*  if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Stock_In__c',new set<String>{'id','Name','sigmaerpdev__Vendor__r.Name','sigmaerpdev__Location__r.Name','sigmaerpdev__Received_Date_Time__c','sigmaerpdev__Status__c'})
          ){ */
            
              Integer pageSize = 10;
              Integer offset = ((Integer)pageNumber - 1) * pageSize;
              
              r =  new SoPaginationHelper();
              r.pageSizeSigma = pageSize;
              r.pageSigma = (Integer) pageNumber;
              r.totalSigma = [SELECT count() FROM Stock_In__c];
              
              r.stockList = [select id,Name,Vendor__r.Name,Location__r.Name,Received_Date_Time__c,Status__c from Stock_In__c
                             order by createddate desc limit :pageSize offset :offset];
             
         // }
        
        return r;
        
    }
    @AuraEnabled
    public static ContentDocumentLink getproductimage(Id prodId)
    {
        ContentDocumentLink productimagecontent;
        //if(CRUD_FLS_CheckUtility.checkObjCRUD('ContentDocumentLink') && CRUD_FLS_CheckUtility.checkReadPermission('ContentDocumentLink',new set<String>{'id','ContentDocumentId','ContentDocument.FileExtension','ContentDocument.LatestPublishedVersionId','ContentDocument.LatestPublishedVersion.Title','SystemModstamp','LinkedEntityId','Visibility','ShareType'}))
        //{
            productimagecontent = [SELECT Id, ContentDocumentId,ContentDocument.FileExtension, ContentDocument.LatestPublishedVersionId,ContentDocument.LatestPublishedVersion.Title,SystemModstamp,LinkedEntityId,Visibility,ShareType FROM ContentDocumentLink WHERE LinkedEntityId =: prodId and ContentDocument.FileExtension IN ('jpg','png') order by SystemModstamp DESC limit 1];
        //}
        return productimagecontent;
    }
     @AuraEnabled
    public static String deletestock(Id StockId){
      //  if(CRUD_FLS_CheckUtility.checkReadPermission('Stock_In__c',new set<String>{'id'})
           //&& CRUD_FLS_CheckUtility.checkObjCRUD('Stock_In__c')
          //){
              try{        
                 
                  system.debug('aaa');
                  List<Stock_In__c> delStockList = [select id from Stock_In__c where id = :StockId];
                  delete delStockList;
                 
              }catch(Exception e){
                  System.debug('Exception in Delete>>>>>'+e.getMessage());
                  return null;
              }
          
        return null;
    }
    }