SigmaCodebackup3rdSep/objects/Tax__c.object
<CustomObject>
    <description>This is built for Magento Platform integration. Do not delete.</description>
    <fields>
        <fullName>Applies_To__c</fullName>
        <label>Applies To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Federal Tax</fullName>
                </value>
                <value>
                    <fullName>State Tax</fullName>
                </value>
                <value>
                    <fullName>Product Tax</fullName>
                    <isActive>false</isActive>
                    <label>Product Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia &amp; Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Merchant_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchant Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Merchant Account should be Customer</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Taxs (Merchant Account)</relationshipLabel>
        <relationshipName>Taxs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Chandigarh</fullName>
                </value>
                <value>
                    <fullName>Chhattisgarh</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Goa</fullName>
                </value>
                <value>
                    <fullName>Gujarat</fullName>
                </value>
                <value>
                    <fullName>Haryana</fullName>
                </value>
                <value>
                    <fullName>Himachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Jammu and Kashmir</fullName>
                </value>
                <value>
                    <fullName>Jharkhand</fullName>
                </value>
                <value>
                    <fullName>Karnataka</fullName>
                </value>
                <value>
                    <fullName>Kerala</fullName>
                </value>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                </value>
                <value>
                    <fullName>Maharashtra</fullName>
                </value>
                <value>
                    <fullName>Manipur</fullName>
                </value>
                <value>
                    <fullName>Meghalaya</fullName>
                </value>
                <value>
                    <fullName>Mizoram</fullName>
                </value>
                <value>
                    <fullName>Nagaland</fullName>
                </value>
                <value>
                    <fullName>Orissa</fullName>
                </value>
                <value>
                    <fullName>Pondicherry</fullName>
                </value>
                <value>
                    <fullName>Punjab</fullName>
                </value>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Sikkim</fullName>
                </value>
                <value>
                    <fullName>Tamil Nadu</fullName>
                </value>
                <value>
                    <fullName>Tripura</fullName>
                </value>
                <value>
                    <fullName>Uttarakhand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/CheckDuplicateTaxHandler.cls
public with sharing class CheckDuplicateTaxHandler{
     
     public void CheckDuplicateinsert(List<Tax__c> newTax){
         if(CRUD_FLS_CheckUtility.checkObjCRUD('sigmaerpdev__Tax__c')
         && CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Tax__c',new set<String>{'Id','sigmaerpdev__Name__c','sigmaerpdev__Status__c','sigmaerpdev__Country__c','sigmaerpdev__State__c','sigmaerpdev__Merchant_Account__c','sigmaerpdev__Merchant_Account__r.Name','sigmaerpdev__Applies_To__c'})){
         
            List<string> Country= new List<string>();
            List<string> State= new List<string>();
            List<string> AppliesTo= new List<string>();
            List<Id> taxId= new List<Id>();
            
            for(Tax__c tax : newTax){
            Country.add(tax.Country__c);
            State.add(tax.State__c);
            AppliesTo.add(tax.Applies_To__c);
            taxId.add(tax.Id);  
            }
            List<Tax__c> duplicateTaxList = [Select Id,Name__c,Status__c,Country__c,State__c,Merchant_Account__c,Merchant_Account__r.Name,Applies_To__c From Tax__c where Applies_To__c= 'State Tax' and Country__c IN: Country and State__c IN: State  and Applies_To__c IN: AppliesTo];
            
             if(!duplicateTaxList.isEmpty()){
                 
                 for(Tax__c taxList:newTax){
                     for(Tax__c taxList1:duplicateTaxList){
                         
                         if(taxList.Country__c == taxList1.Country__c && taxList.State__c == taxList1.State__c  && taxList.Applies_To__c == taxList1.Applies_To__c && taxList1.Status__c =='Active'){
                         
                          taxList.addError('Tax Already Exists for this State:'+taxList.State__c+',Country:'+taxList.Country__c+'Of this State Tax');
                         
                         }
                     }
                 }
                 
             }
             
             List<Tax__c> duplicateFedTaxList = [Select Id,Name__c,Country__c,State__c,Merchant_Account__c,Merchant_Account__r.Name,Status__c,Applies_To__c From Tax__c where Applies_To__c= 'Federal Tax' and Country__c IN: Country   and Applies_To__c IN: AppliesTo];
            
             if(!duplicateFedTaxList.isEmpty()){
                 
                 for(Tax__c FedtaxList:newTax){
                     for(Tax__c FedtaxList1:duplicateFedTaxList){
                         
                         if(FedtaxList.Country__c == FedtaxList1.Country__c   && FedtaxList.Applies_To__c == FedtaxList1.Applies_To__c && FedtaxList1.Status__c =='Active'
                            ){
                          FedtaxList.addError('Tax Already Exists for this Country:'+FedtaxList.Country__c+'Of this Federal Tax');
                         }
                         
                     }
                 }
                 
             }
        }
     }
        public void checkDuplicatesupdate(List<Tax__c> newTax){
            if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Tax__c',new set<String>{'Id','sigmaerpdev__Name__c','sigmaerpdev__Country__c','sigmaerpdev__State__c','sigmaerpdev__Merchant_Account__c','sigmaerpdev__Merchant_Account__r.Name','sigmaerpdev__Applies_To__c','sigmaerpdev__Status__c'}))
                {
         
            List<string> Country= new List<string>();
            List<string> State= new List<string>();
            List<string> AppliesTo= new List<string>();
            List<Id> taxId= new List<Id>();
            
            for(Tax__c tax : newTax){
            Country.add(tax.Country__c);
            State.add(tax.State__c);
            AppliesTo.add(tax.Applies_To__c);
            taxId.add(tax.Id);  
            }
            
            List<Tax__c> duplicateTaxList = [Select Id,Name__c,Country__c,State__c,Merchant_Account__c,Merchant_Account__r.Name,Status__c,Applies_To__c From Tax__c where Applies_To__c= 'State Tax' and Country__c IN: Country and State__c IN: State  and Applies_To__c IN: AppliesTo];
            
             if(!duplicateTaxList.isEmpty()){
                 
                 for(Tax__c taxList:newTax){
                     for(Tax__c taxList1:duplicateTaxList){
                         
                         if(taxList.Country__c == taxList1.Country__c && taxList.State__c == taxList1.State__c  && taxList.Applies_To__c == taxList1.Applies_To__c && taxList1.id!=taxList.id && taxList1.Status__c =='Active'){
                         
                          taxList.addError('Tax Already Exists for this State:'+taxList.State__c+',Country:'+taxList.Country__c+'Of this State Tax');
                         
                         }
                     }
                 }
                 
             }
             
             List<Tax__c> duplicateFedTaxList = [Select Id,Name__c,Country__c,State__c,Merchant_Account__c,Merchant_Account__r.Name,Status__c,Applies_To__c From Tax__c where Applies_To__c= 'Federal Tax' and Country__c IN: Country   and Applies_To__c IN: AppliesTo];
            
             if(!duplicateFedTaxList.isEmpty()){
                 
                 for(Tax__c FedtaxList:newTax){
                     for(Tax__c FedtaxList1:duplicateFedTaxList){
                         
                         if(FedtaxList.Country__c == FedtaxList1.Country__c   && FedtaxList.Applies_To__c == FedtaxList1.Applies_To__c && FedtaxList1.id!=FedtaxList.id && FedtaxList1.Status__c =='Active'){
                          FedtaxList.addError('Tax Already Exists for Country:'+FedtaxList.Country__c+'Of this Federal Tax');
                         }
                         
                     }
                 }
                 
             }
          }
        }           
}