SigmaCodebackup3rdSep/objects/Tax__c.object
<CustomObject>
    <description>This is built for Magento Platform integration. Do not delete.</description>
    <fields>
        <fullName>Applies_To__c</fullName>
        <label>Applies To</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Federal Tax</fullName>
                </value>
                <value>
                    <fullName>State Tax</fullName>
                </value>
                <value>
                    <fullName>Product Tax</fullName>
                    <isActive>false</isActive>
                    <label>Product Tax</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia &amp; Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Chandigarh</fullName>
                </value>
                <value>
                    <fullName>Chhattisgarh</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Goa</fullName>
                </value>
                <value>
                    <fullName>Gujarat</fullName>
                </value>
                <value>
                    <fullName>Haryana</fullName>
                </value>
                <value>
                    <fullName>Himachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Jammu and Kashmir</fullName>
                </value>
                <value>
                    <fullName>Jharkhand</fullName>
                </value>
                <value>
                    <fullName>Karnataka</fullName>
                </value>
                <value>
                    <fullName>Kerala</fullName>
                </value>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                </value>
                <value>
                    <fullName>Maharashtra</fullName>
                </value>
                <value>
                    <fullName>Manipur</fullName>
                </value>
                <value>
                    <fullName>Meghalaya</fullName>
                </value>
                <value>
                    <fullName>Mizoram</fullName>
                </value>
                <value>
                    <fullName>Nagaland</fullName>
                </value>
                <value>
                    <fullName>Orissa</fullName>
                </value>
                <value>
                    <fullName>Pondicherry</fullName>
                </value>
                <value>
                    <fullName>Punjab</fullName>
                </value>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Sikkim</fullName>
                </value>
                <value>
                    <fullName>Tamil Nadu</fullName>
                </value>
                <value>
                    <fullName>Tripura</fullName>
                </value>
                <value>
                    <fullName>Uttarakhand</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                    <default>true</default>
                    <label>Percentage</label>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/CheckDuplicateTaxHandlerTest.cls
@isTest 
public class CheckDuplicateTaxHandlerTest
{
    @isTest(SeeAllData=false)
    public static void CheckDuplicateTaxHandler1(){
        
        Id RIDloc = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Account customerAccount= new Account();
        customerAccount.Name= 'Test Merchant 5';
        customerAccount.Type = 'Customer';
        customerAccount.Email__c='raghavendrahgr@gmail.com';
        customerAccount.Web_Order_Type__c= 'Percentage';
        customerAccount.Web_Order_Value__c =40;
        customerAccount.State__c='Alabama';
        customerAccount.Country__c='USA';
        customerAccount.RecordtypeId = RIDloc;
        insert customerAccount;
        System.assertEquals(customerAccount.Type, 'Customer');
        
        List<Tax__c> taxlist = new List<Tax__c>();
        
        Tax__c tax = new Tax__c();
        tax.Name__c = 'Name1';
        tax.Status__c = 'Active';
        tax.Applies_To__c = 'Federal Tax';
        tax.Tax_Amount__c = 2;
        tax.Type__c = 'Percentage';
        tax.Country__c = 'USA';
        tax.State__c = 'Alabama';
        taxlist.add(tax);
        insert taxlist;
        
        System.assertEquals(tax.Type__c, 'Percentage');
        
        
        Tax__c tax1 = new Tax__c();
        tax1.Id= tax.Id;
        tax1.Name__c = 'Name1';
        tax1.Status__c = 'Active';
        tax1.Applies_To__c = 'Federal Tax';
        tax1.Tax_Amount__c = 2;
        tax1.Type__c = 'Percentage';
        tax1.Country__c = 'USA';
        tax1.State__c = 'Alabama';
        update tax1;
        
        System.assertEquals(tax1.Type__c, 'Percentage');
        
        List<Tax__c> StatetaxList = new List<Tax__c>();
        Tax__c Statetax = new Tax__c();
        Statetax.Name__c = 'Name3';
        Statetax.Status__c = 'Active';
        Statetax.Applies_To__c = 'State Tax';
        Statetax.Tax_Amount__c = 2;
        Statetax.Type__c = 'Percentage';
        Statetax.Country__c = 'USA';
        Statetax.State__c = 'Alabama';
        StatetaxList.add(Statetax);
        insert StatetaxList;
        
        System.assertEquals(Statetax.Type__c, 'Percentage');
        
        
        Tax__c Statetax1 = new Tax__c();
        Statetax1.Id= Statetax.Id;
        Statetax1.Name__c = 'Name3';
        Statetax1.Status__c = 'Active';
        Statetax1.Applies_To__c = 'State Tax';
        Statetax1.Tax_Amount__c = 2;
        Statetax1.Type__c = 'Percentage';
        Statetax1.Country__c = 'USA';
        Statetax1.State__c = 'Alabama';
        update Statetax1;
        System.assertEquals(Statetax1.Type__c, 'Percentage');
        
        
        CheckDuplicateTaxHandler dup = new  CheckDuplicateTaxHandler();
        dup.CheckDuplicateinsert(taxlist);
        dup.CheckDuplicateinsert(StatetaxList);
        dup.checkDuplicatesupdate(taxlist);
        dup.checkDuplicatesupdate(StatetaxList);
    }
}