SigmaCodebackup3rdSep/objects/Tax__c.object
<CustomObject>
    <description>This is built for Magento Platform integration. Do not delete.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia &amp; Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Chandigarh</fullName>
                </value>
                <value>
                    <fullName>Chhattisgarh</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Goa</fullName>
                </value>
                <value>
                    <fullName>Gujarat</fullName>
                </value>
                <value>
                    <fullName>Haryana</fullName>
                </value>
                <value>
                    <fullName>Himachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Jammu and Kashmir</fullName>
                </value>
                <value>
                    <fullName>Jharkhand</fullName>
                </value>
                <value>
                    <fullName>Karnataka</fullName>
                </value>
                <value>
                    <fullName>Kerala</fullName>
                </value>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                </value>
                <value>
                    <fullName>Maharashtra</fullName>
                </value>
                <value>
                    <fullName>Manipur</fullName>
                </value>
                <value>
                    <fullName>Meghalaya</fullName>
                </value>
                <value>
                    <fullName>Mizoram</fullName>
                </value>
                <value>
                    <fullName>Nagaland</fullName>
                </value>
                <value>
                    <fullName>Orissa</fullName>
                </value>
                <value>
                    <fullName>Pondicherry</fullName>
                </value>
                <value>
                    <fullName>Punjab</fullName>
                </value>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Sikkim</fullName>
                </value>
                <value>
                    <fullName>Tamil Nadu</fullName>
                </value>
                <value>
                    <fullName>Tripura</fullName>
                </value>
                <value>
                    <fullName>Uttarakhand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                    <default>true</default>
                    <label>Percentage</label>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/TaxUtility.cls
public with sharing class TaxUtility{

 public Double taxAmt{get;set;}
    public Double calculateTax(Double amt,String state,String country){
        if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Tax__c',new set<String>{'Id','sigmaerpdev__Name__c','sigmaerpdev__State__c','sigmaerpdev__Tax_Amount__c','sigmaerpdev__Status__c','sigmaerpdev__Type__c','sigmaerpdev__Country__c'}))
        {
        Tax__c tax;
            tax = [Select Id,Name__c,State__c,Tax_Amount__c,Status__c,Type__c,Country__c from Tax__c where id=:state];
        
        if(tax.Status__c == 'Active'){
            //calculate for percentage
            if(tax.Type__c== 'Percentage'){
                taxAmt= (amt*tax.Tax_Amount__c)/100;
            }
            //calculate for Flat
            else if(tax.Type__c== 'Flat'){
                taxAmt= (amt+tax.Tax_Amount__c);
            }
        }
        }
        return taxAmt;
    }

    //get the tax details against state
    public Double calculateTaxForCity(String state){

        //get the tax amount for the state
        system.debug('Incoming State :'+state);
        Double stateTax = 0.00;
        Tax__c tax;
        if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Tax__c',new set<String>{'Id','sigmaerpdev__Name__c','sigmaerpdev__State__c','sigmaerpdev__Tax_Amount__c','sigmaerpdev__Status__c','sigmaerpdev__Type__c','sigmaerpdev__Country__c'}))
        {
         tax = [Select Id,Name__c,State__c,Tax_Amount__c,Status__c,Type__c,Country__c from Tax__c where id=:state or State__c=:state LIMIT 1];
       
        if(tax.Status__c=='Active')
        {
           stateTax = tax.Tax_Amount__c;
        }
        }

        return stateTax;
    }
    
    //get the federal tax
    public Double getFederalTax(){
    Double federalTax = 0.00;        
        Tax__c tax;
       if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Tax__c',new set<String>{'Id','sigmaerpdev__Name__c','sigmaerpdev__State__c','sigmaerpdev__Tax_Amount__c','sigmaerpdev__Status__c','sigmaerpdev__Type__c','sigmaerpdev__Country__c'}))
        {
            tax = [Select Id,Name__c,State__c,Tax_Amount__c,Status__c,Type__c,Country__c from Tax__c where Name__c='Federal Tax' LIMIT 1];
            if(tax.Status__c=='Active'){
                federalTax = tax.Tax_Amount__c;
            }
       
        }
        return federalTax;
    }
    public Double getFederalTaxByCountry(String country){

        //get the tax amount for the state
        Double federalTax = 0.00;
        if(CRUD_FLS_CheckUtility.checkReadPermission('sigmaerpdev__Tax__c',new set<String>{'Id','sigmaerpdev__Name__c','sigmaerpdev__State__c','sigmaerpdev__Tax_Amount__c','sigmaerpdev__Status__c','sigmaerpdev__Type__c','sigmaerpdev__Country__c'}))
        {
        if(country!='' && country!=NULL && country!=null){
            Tax__c tax;
           
                tax = [Select Id,Name__c,State__c,Tax_Amount__c,Status__c,Type__c,Country__c from Tax__c where (id=:country or Country__c=:country) AND Name__c='Federal Tax' LIMIT 1];
                if(tax.Status__c=='Active'){
                    federalTax = tax.Tax_Amount__c;
                }
                     
        }
        }
        return federalTax;
    }
    
}