SigmaCodebackup3rdSep/objects/Work_Oder_Lines__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipLabel>Work Order Lines</relationshipLabel>
        <relationshipName>Work_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Order Lines</label>
    <nameField>
        <displayFormat>WRL-{YYYY}-{MM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Another_Visit_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Another Visit Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Work Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Invoiced to Customer</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Another Visit Needed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Order Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/InvoiceGenerationPdfController.cls
public with sharing class InvoiceGenerationPdfController {
    @AuraEnabled
    public static boolean generateInvoicePDF(String currentRecordRowIdString) {
        //String currentRecordRowId = (String)JSON.deserialize(currentRecordRowIdString, String.Class);
        system.debug('************ APEX CLASS - INVOICE_GENERATION_PDF_CONTROLLER***************');
        Utility.getInvoicePDFContent(currentRecordRowIdString);
        system.debug('Function Returned Successfully');
        return true; 
    } 
    @AuraEnabled
    public static String getPDFContAsBase64(String currentRecordRowId) {
        // system.debug('currentRecordRowId'+currentRecordRowId);
        return Utility.getPDFContentAsBase64(currentRecordRowId);
    }
    @AuraEnabled
    public static workOrderWrapper updateStatus(String currentRecordRowId){
        // List<sObject> ObjectList = new List<sObject>();
        //String currentRecordRowId = (String)JSON.deserialize(currentRecordRowIdString, String.Class);
        workOrderWrapper orderWrap = new workOrderWrapper();
        orderWrap.isWorkOrderEmpty = true;
        Work_Order__c RecordToUpdate;
        String [] workOrderFields = new String [] {'sigmaerpdev2__Status__c'};
            
            // Obtaining the field name/token map for the WorkOrder object
            Map<String,Schema.SObjectField> workOrderMap = Schema.SObjectType.Work_Order__c.fields.getMap();
        for (String fieldToCheck : workOrderFields) {
            // Check if the user has create access on the each field
            if (!workOrderMap.get(fieldToCheck).getDescribe().isAccessible()) {
                system.debug('Has no Access on WorkOrder Fields');
                return null;
            }
        }
        
        RecordToUpdate = [Select id,Status__c,Another_Visit_Needed__c from Work_Order__c where id=:currentRecordRowId Limit 1];
        
        List<Work_Oder_Lines__c> WoLineitemCheck;
        if(Schema.sObjectType.Work_Oder_Lines__c.fields.Name.isAccessible()){
            WoLineitemCheck = [SELECT Id,Name FROM Work_Oder_Lines__c where Work_Order__c = : currentRecordRowId];
        }
        else{
            system.debug('WorkOrderLineItem not Accessible');
        }
        
        
        if( !WoLineitemCheck.isEmpty()){
            orderWrap.isWorkOrderEmpty = false;
            system.debug('Work order Status '+RecordToUpdate.Status__c);
           
           if(RecordToUpdate.Another_Visit_Needed__c==true){

		   if(Schema.sObjectType.Work_Order__c.fields.Status__c.isUpdateable()){
				RecordToUpdate.Status__c = 'Another Visit Needed';
            }
		   }
		   
            else{
				 if(Schema.sObjectType.Work_Order__c.fields.Status__c.isUpdateable()){
				RecordToUpdate.Status__c = 'Invoiced to Customer';
            }
                system.debug('No Edit Access on Work_Order__c - Status__c Field');
            }
            Update RecordToUpdate;
           
            orderWrap.workOrderId = RecordToUpdate.ID;
        }
        return orderWrap;
        
    }
    
    public class workOrderWrapper {
        @AuraEnabled
        public ID workOrderId {get; set;}
        @AuraEnabled
        public Boolean isWorkOrderEmpty {get; set;}
    }
    
}