SigmaCodebackup3rdSep/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Order Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/objects/Work_Order_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>Work_Order__c</referenceTo>
        <relationshipName>Work_Order_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Order Assignment</label>
    <nameField>
        <displayFormat>WOA-{0000}</displayFormat>
        <label>Work Order Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SigmaCodebackup3rdSep/classes/DeleteWOAOnDateUpdate.cls
public with sharing class DeleteWOAOnDateUpdate {
    //******************************************************************************************************************************************************************************  
    //  Date: 23/05/2018  Author :Jyoshna  functionName:deleteWOAOnChangeOfPreferredDateTime() 
    // Function Desdription: This method is called from process builder when preffered dateTime is updated to delete Work_Order_Assignment__c
    //********************************************************************************************************************************************************************************
    
    @InvocableMethod 
    public Static void deleteWOAOnChangeOfPreferredDateTime(List<Work_Order__c> workorderId){
        System.debug('workorderId'+workorderId); 
        try{
            // Check if the user has delete access on the Work_Order_Assignment__c object
            if (!Work_Order_Assignment__c.sObjectType.getDescribe().isDeletable()) {
                return;
            }
            Work_Order_Assignment__c AllworkorderAssignmentRecords=[SELECT Id, Work_Order__c FROM Work_Order_Assignment__c where Work_Order__c=:workorderId[0].id Limit 1];
            delete AllworkorderAssignmentRecords;
            System.debug('WOA records deleted Successfully');
        }
        catch(Exception e){
            System.debug('Exception'+e);
        }
    }
    
}